### ISSUE TITLE
Multiple NanoVG/OpenGL uis conflicting

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#101]
I believe the DC and HDGLC(?) are not getting set/reset correctly 

some work here:

https://github.com/iPlug2/iPlug2/tree/graphics-winglcontexts

**Comment by olilarkin** [comment]
@austensatterlee do you know much about this?

**Comment by AlexHarker** [comment]
Should win IGraphicsTest be working right now? I get an exception on load to do with GL/NanoVG code.

**Comment by austenspwr** [comment]
Sorry for the late response here, what exactly is the nature of the issue? I'm not an expert in Windows GUI programming but I can certainly do some research and try to fix the issue.

**Comment by austensatterlee** [comment]
Sorry for the late response here, what exactly is the nature of the issue? I'm not an expert in Windows GUI programming but I can certainly do some research and try to fix the issue.

**Comment by austensatterlee** [comment]
I remember dealing with a similar issue with VOSIMSynth. If memory serves, I think fiddling with the window flags resolved the issue (maybe adding `WS_POPUP`?). I'll try messing around with it this weekend and creating a PR if it's not resolved by then.

**Comment by olilarkin** [comment]
addressed in ec1158ffd6661bb2c5615bf9eecf79683a8c40ad, although there is an occasional "UI goes black" issue which i have not tracked down
