### ISSUE TITLE
Switch to libremidi?

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#1012]
libremidi looks like a good alternative to RTMidi, supporting MIDI 2.0 and better suited to real time use: https://github.com/jcelerier/libremidi

**Comment by AlexHarker** [comment]
Do you want me to look as I am on a "MIDI bender"?

**Comment by olilarkin** [comment]
Up to you! note: also it's C++ 20

**Comment by olilarkin** [comment]
Closing, maybe another day
