### ISSUE TITLE
Control area after scaling

### ISSUE THREAD

**Issue by Kotozaurus** [iPlug2/iPlug2#103]
Control area for a mouse wheel moves incorrect after scaling. The problem here is IGraphicsWin.cpp line 332, in WndProc function:
`pGraphics->OnMouseWheel (info.x - r.left, info.y - r.top , info.ms, d);`
Solved by replacing on `pGraphics->OnMouseWheel (info.x - r.left / pGraphics-> GetDrawScale (), info.y - r.top / pGraphics->GetDrawScale (), info.ms, d);`

**Comment by AlexHarker** [comment]
Thanks for the catch and the fix. Written slightly differently, as we might need to account for ScreenScale() at some point, but fixed in the way you describe in ad48eb325c3f3c0e8544d896075b4a42b9dcea70.
