### ISSUE TITLE
Lanczos resampler uses hard-coded `4`s instead of appropriate varaible `A`

### ISSUE THREAD

**Issue by sdatkinson** [iPlug2/iPlug2#1036]
**Describe the bug**
The use of `4` on lines 206, 207, 219, 226, and 227 of [`LanczosResampler.h`](https://github.com/iPlug2/iPlug2/blob/2376d58e1d157c6b8f9b1bd3ac673bcaa5651649/IPlug/Extras/LanczosResampler.h#L70) appears incorrect. Instead, they should use [`A`](https://github.com/iPlug2/iPlug2/blob/2376d58e1d157c6b8f9b1bd3ac673bcaa5651649/IPlug/Extras/LanczosResampler.h#L73).

Changing `A` as-is (to e.g. `8`) results in very incorrect-sounding behavior!

**To Reproduce**

* Change `A` to `8`.
* Compile something using the `NonIntegerResampler`
* Bounce something at both native sample rate and something else.
* Something terribly wrong like this ensues:

![image](https://github.com/iPlug2/iPlug2/assets/12240186/385482d6-9652-48d2-a1ba-6a36f4ffed4d)

---

I'll have a PR along presently.

Fixing this bug as well as cranking `A` up to 12 fixes both https://github.com/sdatkinson/NeuralAmpModelerPlugin/issues/398 and  https://github.com/sdatkinson/NeuralAmpModelerPlugin/issues/400. However, I think that `A` should be chosen based on the needs of its use case, so I'm going to leave it at `4`. [Ideally, I wish it weren't hard-coded, but that's a bit more non-trivial due to the use of some static variables that bake in the assumption that it's not getting messed with a bit too hard for a quick fix.]

**Comment by olilarkin** [comment]
Nice! will check this and work out how to make A dynamic soon

**Comment by olilarkin** [comment]
@sdatkinson I am trying to test this with a sine wave input and not getting a lot of aliasing with your changes + A=12 (whatever host sample rate is). still looking at it

**Comment by olilarkin** [comment]
are you using IPLUG_SIMDE or the Scalar version?

**Comment by olilarkin** [comment]
Addressed by https://github.com/iPlug2/iPlug2/commit/4bfc3e15d67f0c7c930aab71d1bf0e551362a1c4
