### ISSUE TITLE
`RealtimeResampler` has errors

### ISSUE THREAD

**Issue by sdatkinson** [iPlug2/iPlug2#1038]
I've gotten some reports since shipping the resampler in https://github.com/sdatkinson/NeuralAmpModelerPlugin/releases/tag/v0.7.7 of a few buggy behaviors:

* When resampling from a DAW sample rate of 44.1k to a rendering sample rate of 48k, there's an oddly large latency--far more than the (approximately) `2*A` that should be required by the Lanczos resampler being used twice (up/down).
* The latency depends on the buffer size--something like 150 at a buffer size of 128, and 1150 at a buffer size of 1024.

I did some digging and I think I've figured out what's going on. The issues appear to be 

So if I've understood everything correctly, then here are the issues that cause the problem:
* [The latency calculation in `Reset()`](https://github.com/iPlug2/iPlug2/blob/40ebb560eba68f096221e99ef0ae826611fc2bda/IPlug/Extras/RealtimeResampler.h#L104) is wrong. Instead of `2 * mResamplerUp->GetNumSamplesRequiredFor(1)`, it should be `mResamplerUp->GetNumSamplesRequiredFor(mResamplerDown->GetNumSamplesRequiredFor(1))`.
* The [`while` loop](https://github.com/iPlug2/iPlug2/blob/40ebb560eba68f096221e99ef0ae826611fc2bda/IPlug/Extras/RealtimeResampler.h#L146) logic is wrong. Instead of `mResamplerUp->GetNumSamplesRequiredFor(outputLen) == 0` (i.e. only do resampling if you can make `outputLen` internal samples--which is the _larger_ value for the integer math!--it should be `mResamplerUp->GetNumSamplesRequiredFor(1) == 0`--run the code so long as there's anything for the first resampler to pop. (The contents of the while loop need to be ready to work with varying block sizes--which is expected for the integer math. The return values on the `PopBlock`s are also needed to be able to know how much you're working with on any given time throughout the function.
* Also a slightly minor issue, [`mScratchPtrs` is used for both the input and output to `func`](https://github.com/iPlug2/iPlug2/blob/40ebb560eba68f096221e99ef0ae826611fc2bda/IPlug/Extras/RealtimeResampler.h#L149C22-L149C22), which (invalidly) assumes that `func` can be done in-place. (Luckily, it's not a problem for my use case).
* The size of the arrays contained by `mScratchPtrs` is invalidly-set. Currently, [the arrays are set to be 2x the size of the max external block size (per channel)](https://github.com/iPlug2/iPlug2/blob/40ebb560eba68f096221e99ef0ae826611fc2bda/IPlug/Extras/RealtimeResampler.h#L90C10-L90C10), which means that the code may segfault if the rendering sample rate is more than 2x the outer sample rate.
* When `Reset()`ing, the first `mLatency` samples pushed through the first resampler need to also be processed by `func` and pushed into the second resampler so that the main loop doesn't see more than [`outputLen`]() samples (due to the `while` loop change). As-is right now, on the first call to `ProcessBlock`, approximately `A` samples are left unset in the `output` buffer, resulting a quick blip of some random noise. \[If we assume that `func` is a "normal" effect, then we can assume that it will output zeroes\]. Alternatively, if we wanted to just process more samples on the first time through `ProcessBlock`, we either need to be ready for that extra-big buffer the first time (e.g. something like `outputLen = ceil((mLatency + nFrames) / mUpRatio)`, or a ring buffer or something needs to be used in place of `mScratchPtrs` in the `ProcessBlock` while loop.

(All of this is for the Lanczos resampler; I've basically ignored the other interpolators.)

I've got something that I _think_ solves the problems and works as expected, but I'm not confident it's all there quite yet--there's a lot of moves I had to make (and I had to get familiar with the code as well, so my code is littered with comments & notes atm). 

I don't have something PR-ready yet, but I stubbed the Issue here: https://github.com/sdatkinson/NeuralAmpModelerPlugin/issues/411 and I'm working through the fixes on https://github.com/sdatkinson/NeuralAmpModelerPlugin/tree/issue-411

**Comment by olilarkin** [comment]
Really sorry that I was a bit eager to merge this class to iPlug2 master before it had been exhaustively tested. Looking at some of the comments in your iPlug2 fork it relates to some code that @baconpaul helped me with. I am even wondering right now if it's possible to use this technique without the 1-block additional latency.

To save your sanity, I feel like it might be best for you to work from his original lanczos resampler class and test:

https://github.com/surge-synthesizer/sst-basic-blocks/blob/main/include/sst/basic-blocks/dsp/LanczosResampler.h

https://github.com/surge-synthesizer/sst-basic-blocks/blob/2ea95c766a228d0c4ea53f956a80feccc9e6dcb1/tests/dsp_tests.cpp#L236

You could use that to implement the resampler in NAM DSPTools and avoid banging your head against the wall with any bugs that I have added as I tried to rework it into iPlug2 land

**Comment by olilarkin** [comment]
... think i have the solution for the latency

**Comment by sdatkinson** [comment]
Check out [my branch](https://github.com/sdatkinson/NeuralAmpModelerPlugin/tree/issue-411) and lmk if you have any questions--it helped me to start from your work and maybe my perspective can help in return :)

FWIW it's a somewhat complex algorithm, even with the actual resampler treated as a black box (though the Lacnzos class's push/pull interfaces are great and definitely helped me think more clearly about it) As you know, I was playing around with coding up something myself and didn't get there after a couple days of working on it :)

`issue-411`  "works" in the sense that I just got it running and things seemed good based on a cursory test & look around--but there's a bunch of FIXMEs and such in there that I need to check back on since I just barely got there before calling it a day :)

As far as working out of iPlug2 for this module or somewhere else, either is potentially fine. I'm personally comfortable with things "taking a detour" and living somewhere a little more private (like [`AudioDSPTools`](https://github.com/sdatkinson/AudioDSPTools)) before "working them up" to something that can reliably support more general use cases (since mine is only one use case out of many that I'm sure I haven't thought about...so I've probably got my own implicit assumptions that I haven't realized yet!)

At the very least, I hope that the things I bulleted out up top are helpful insights for you :)

**Comment by olilarkin** [comment]
i have checked your work and will do some more as I fix up that class. My WIP is here: https://github.com/iPlug2/iPlug2/commit/4d36d033fe3805d7514d092fa16c985a3f63e1ce

it should fix the latency

**Comment by sdatkinson** [comment]
Nice.

I do think that the `quantum` bit of stuff (and the magic `+2`) are fixed if your while loop condition is changed to what I did. After all, the logic isn't "do we have a clean full block to push into the encapsulated context?"; it's "has the encapsulated context processed everything it can?"--this gives the outgoing resampler as much as possible for it to be able to pop what the external context requires--and probably saves me those 2 samples of latency ;). (and while this technically makes the encapsulated `func()` lean towards eager execution, I don't think that's too bad on measure...but there's a chance I'm not thinking of something.)

Just added more changes to my fork's [`fix-resampler`](https://github.com/sdatkinson/iPlug2/tree/fix-resampler) -- see https://github.com/sdatkinson/iPlug2/commit/fa6a270be2004f17fc119f3e52064bf1e9b9cfd4

**Comment by olilarkin** [comment]
Cool i will try tomorrow

**Comment by baconpaul** [comment]
Great - do you need me to make changes to the upstream class or is this all resolved in client code?

happy the class is useful!

**Comment by olilarkin** [comment]
@baconpaul we're using a modified version of your class in iPlug2 so nothing for you to do.

@sdatkinson I tried your version and need to do a bit more testing, but it seems like a better way to solve the latency bug in RealtimeResampler than what i did. I found that I still had to add the magic number 2 to the reported latency to zero cancel a sine wave. I also left it on whilst I went out for lunch and came back to find that it had hit one of those std::runtime_errors in processblock(). That's something to investigate. Also, I'm wondering what is going happen in e.g FruityLoops which varies the block size of audio processing continuously, and is often problematic with code like this.

Unfortunately not going to have much time to look at it for awhile. You might want to use your iPlug2 fork if you are going to do a release in the near future.

**Comment by olilarkin** [comment]
@baconpaul also... thanks once again... once we've ironed out these problems, mainly introduced by my wrapper it seems like your class is still extremely useful to get decent quality resampling in NAM with low latency

**Comment by baconpaul** [comment]
Great glad it's useful. You know how to reach me if you want to make or upstream any changes!

**Comment by olilarkin** [comment]
OK i made a PR which hopefully addresses these things and doesn't add more problems in #1039

**Comment by olilarkin** [comment]
Closing this as I've merged the PR with the fixes (minus the example).
