### ISSUE TITLE
Faust example not working on Windows

### ISSUE THREAD

**Issue by dmsplugins** [iPlug2/iPlug2#104]
I recently cloned IPlug2 and have been able to build all example projects on windows10 with the exception of IPlugFaustDSP. I am sure that I need to configure the Dependencies/Extras/faust folder..... i'm just not sure how. I'm also curious as to what should go in the civetweb folder. When I open the VS solution for IPlug2FaustDSP, I get the following errors....
Error (active)    E1696    cannot open source file "faust/gui/UI.h"    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust.h    18    

Error (active)    E1696    cannot open source file "faust/gui/MidiUI.h"    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust.h    19    

Error (active)    E1696    cannot open source file "swell.h"    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust_edit.h    8    

Error (active)    E1696    cannot open source file "curses.h"    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust_edit.h    9    

Error (active)    E1696    cannot open source file "curses_editor.h"    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust_edit.h    10    

Error (active)    E0262    not a class or struct name    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust.h    36    

Error (active)    E0262    not a class or struct name    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust.h    36    

Error (active)    E1455    member function declared with 'override' does not override a base class member    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust.h    203    

Error (active)    E1455    member function declared with 'override' does not override a base class member    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust.h    211    

Error (active)    E1455    member function declared with 'override' does not override a base class member    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust.h    212    

Error (active)    E1455    member function declared with 'override' does not override a base class member    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust.h    213    

Error (active)    E1455    member function declared with 'override' does not override a base class member    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust.h    214    

Error (active)    E1455    member function declared with 'override' does not override a base class member    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust.h    216    

Error (active)    E1455    member function declared with 'override' does not override a base class member    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust.h    221    

Error (active)    E1455    member function declared with 'override' does not override a base class member    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust.h    226    

Error (active)    E1455    member function declared with 'override' does not override a base class member    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust.h    231    

Error (active)    E1455    member function declared with 'override' does not override a base class member    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust.h    236    

Error (active)    E1455    member function declared with 'override' does not override a base class member    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust.h    242    

Error (active)    E1455    member function declared with 'override' does not override a base class member    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust.h    243    

Error (active)    E1455    member function declared with 'override' does not override a base class member    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust.h    244    

Error (active)    E0020    identifier "Soundfile" is undefined    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust.h    244    

Error (active)    E0282    the global scope has no "dsp"    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust.h    317    

Error (active)    E0020    identifier "MidiUI" is undefined    IPlug2FaustDSP-vst2    C:\SDKs\iPlug2\IPlug\Extras\Faust\IPlugFaust.h    318

**Comment by olilarkin** [comment]
Hi David, 

I didn't yet get FAUST support working on windows. I will try and look at it soon

oli

**Comment by olilarkin** [comment]
I am going to rename this issue...

**Comment by dmsplugins** [comment]
Ok... Thanks

**Comment by dmsplugins** [comment]
I've built LLVM and faust with MSVC 2017, modified my property pages, and modified IPlugFaust_edit.h to exclude swell.h on Windows exactly like you did on the azure-pipelines branch.
I now get the following errors..........

1>IGraphicsWin.obj : error LNK2001: unresolved external symbol "void __cdecl UTF16ToUTF8(class WDL_String &,wchar_t const *)" (?UTF16ToUTF8@@YAXAEAVWDL_String@@PEB_W@Z)

1>IGraphicsWin.obj : error LNK2001: unresolved external symbol "void __cdecl UTF8ToUTF16(wchar_t *,char const *,int)" (?UTF8ToUTF16@@YAXPEA_WPEBDH@Z)

1>C:\SDKs\iPlug2\Projects\FaustProj\build-win\vst2\x64\bin\FaustProj.dll : fatal error LNK1120: 2 unresolved externals

**Comment by olilarkin** [comment]
I think if you include Iplugpaths.cpp You should be okay

**Comment by dmsplugins** [comment]
I'll give it a try.... thanks

**Comment by dmsplugins** [comment]
It does complile now. Thank you for your help.

**Comment by dmsplugins** [comment]
Both Release and Debug vst2 are building. Release runs fine and I'm able to modify the .dsp file and see results after compiling it with faust.exe with proper arguments (using iPlug2 architecture file) and then rebuilding the project.
The debug version builds without problem, but crashes the host when attempting to load/run the plugin.
I am linking to the dynamic faust lib. with llvm backend
While running in VS debugger, a null value is returned by createDSPFactoryFromString() in llvm_dsp_factory* FaustGen::Factory::CreateFactoryFromSourceCode() and an exception is thrown at the end of the function... after 0 is returned.
just prior to the exception being thrown,  the values of pFactory and mLLVMFactory are null; the value(0xffffffffffffffff) is assigned to the mDSPMutex Debuginfo attribute.
The very next thing that happens after 0 is returned is an exception is thrown with the following message
Exception thrown at 0x00007FFA4ED89AB5 (FaustTest.dll) in FaustTest.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF. (note: FaustTest.exe is Savihost ...... doesn't work in REAPER either)

I have checked and double checked the values that are being fed to createDSPFactoryFromString() and am fairly certain they are correct so I'm not sure why I'm getting a null pointer.
I have no idea how to address the mutex issue.

**Comment by dmsplugins** [comment]
I've gotten the JIT dsp compilation part of the project working.

**Comment by dmsplugins** [comment]
Using debug build of Faust dynamic library and making some changes to IPlug Faust.h, IPlugFaustGen.h, and IPlugFaustGen.cpp.

**Comment by olilarkin** [comment]
great! actually i was trying to get this working last night. Could you share your work on a fork? It's a shame the faust installer is built linking an old MSCV runtime... came to the conclusion i need to build llvm as part of the process to make sure everything has the write linkage

**Comment by dmsplugins** [comment]
I'm working on this now. I will fork and submit a PR. I am thinking of
putting out a zip of the Faust build since llvm takes so long to build.

**Comment by olilarkin** [comment]
if you can provide your build recipe i can build it using azure devops as part of the CI/CD process, in this yml https://github.com/iPlug2/iPlug2/blob/master/Scripts/ci/build_deps.yml

**Comment by dmsplugins** [comment]
[fauststuff.zip](https://github.com/iPlug2/iPlug2/files/2980154/fauststuff.zip)
Sorry it took so long to get this back to you. Hopefully it helps.

**Comment by olilarkin** [comment]
thanks, very helpful

**Comment by olilarkin** [comment]
progress here: https://github.com/iPlug2/iPlug2/tree/faust-win

**Comment by olilarkin** [comment]
This is now setup so that for FAUST on windows, you just use the faust installer, where since this morning, they now include a .dll

https://github.com/grame-cncm/faust/releases/download/2.15.11/Faust-2.15.11-win64.exe
