### ISSUE TITLE
Double taps on IOS go to OnGestureRecognized and don't map to OnMouseDblClick()

### ISSUE THREAD

**Issue by AlexHarker** [iPlug2/iPlug2#1048]
@olilarkin - what are your thoughts on the above?

**Comment by olilarkin** [comment]
Double tap is a OS defined gesture on IOS so this way double tapping responds the same way as it does elsewhere in the OS. Not 100% sure but the user might also be able to adjust the timing of double taps in the system settings

**Comment by olilarkin** [comment]
But adding gesture recognizers could be problematic for other interactions, so I didn't think it was a good idea to do it by default for all i controls

**Comment by AlexHarker** [comment]
Understood - that's useful clarification - I've gone about it a different way here using OnGesture() for the control and adding the recogniser to IGraphics, but I can't seem to get IOS to respond to the double taps - I see the Objective C style recogniser get attached, but its handler is never called.

**Comment by olilarkin** [comment]
can i close this or do you think it is something we should change?

**Comment by AlexHarker** [comment]
I need to ask you some questions so I can check if something is broken here, or if it is just my misunderstanding as I can't get it to work...

**Comment by AlexHarker** [comment]
closing due to implementation confusion at my end (no bug but it my approach couldn't work due to reliance on GetWantsGestures - which was non-virtual - this is now fixed in https://github.com/iPlug2/iPlug2/pull/1058)
