### ISSUE TITLE
MacOS OpenGLContext leaks ~4MB on window close

### ISSUE THREAD

**Issue by svantana** [iPlug2/iPlug2#1060]
OpenGL resources are init'ed on plugin window open but not released on close, resulting in a memory leak. This happens with both NanoVG and Skia backends, which strongly suggests that the error is in iPlug2.

How to verify:
Open and close the iPlugEffect editor in any mac host 50 times, and note in activity monitor that the host's memory has gone up by 200MB.

**Comment by olilarkin** [comment]
thanks!
