### ISSUE TITLE
WebUI example crashes when double-clicked

### ISSUE THREAD

**Issue by Vector-Hector** [iPlug2/iPlug2#1062]
**Describe the bug**
When double clicking the built WebUI example VST3 plugin, FL Studio will crash. 

**To Reproduce**
- Install the latest IPlug2 as described in the [Getting Started](https://github.com/iPlug2/iPlug2/wiki/02_Getting_started_windows)
- Build the IPlug2WebUI example
- Make sure FL Studio finds the plugin
- Add it to an FX slot
- Make sure the plugin is currently closed
- Double click the plugin

**Expected behaviour**
I expected it to just open and close very quickly.

**IMPORTANT DETAILS**
* What plug-in format does it relate to - Currently only tested on VST3
* What platform does it relate to - Currently only tested on Windows 11 with FL Studio 21
* What IGRAPHICS_BACKEND does it relate to, IGRAPHICS_NANOVG, IGRAPHICS_SKIA or ALL? - Not sure, I am pretty new. If there is a default in the WebUI example, then that. But I can look it up if you tell me how to.

**Additional context**
- This does not happen on non-WebUI examples as far as I have seen
- It also happens if the index.html can't be found, like by setting an invalid path

**Comment by Vector-Hector** [comment]
Adding this to the IWebView::OpenWebView callback of CreateCoreWebView2Controller fixed it for me:
```cpp
if (mWebViewWnd == nullptr) {
  return S_OK;
}
```

**Comment by Vector-Hector** [comment]
Not sure whether you accept pull requests / how you want them to be structured, so I won't do one.

**Comment by AlexHarker** [comment]
We do accept PRs - ideally after an issue, so please submit one - we wouldn't consider this complete until it was fixed in the main repo so I'm reopening this - I hope that's OK.
