### ISSUE TITLE
[CMake branch] Clang support on windows

### ISSUE THREAD

**Issue by MeijisIrlnd** [iPlug2/iPlug2#1084]
Hiya, when trying to use a Clang toolchain on Windows on the cmake branch, compilation fails due to `/Zi` being present, which under an msvc-like frontend, generates pdb files. 
I had a bit of a rummage around, and found that `/Zi` is hardcoded in the current `iplug_configure_target` implementation - I was able to get it working by checking if the compiler's cli is msvc-like or not, and if not, replacing `/Zi` with `-DEBUG` in clang's case. 
Not sure if this is a viable solution for `g++`, but it works with Clang on windows, I'll link the PR with the fix to this issue,
Hope it's at-all useful!

**Comment by olilarkin** [comment]
thanks for this. I've added it to the CMake branch WIP
