### ISSUE TITLE
CMakeLists for Examples/IPlugWebUI

### ISSUE THREAD

**Issue by MeijisIrlnd** [iPlug2/iPlug2#1086]
Hiya, unless I've made a very embarrassing oversight and it's on another branch (if it is don't tell me I'm not sure I can take it), there's no CMakeLists in the WebUI example. I've just finished setting it up on Windows, but I'm not enamoured with my solution (it involves relying on Nuget being *somewhere* on the user's path). I also haven't touched it on macOS yet, but I'm hoping to give that a go in the next few days, so in the meantime I'll open a draft PR and post here (and probably in the discord too) as things come up!

**Comment by olilarkin** [comment]
thanks for this. I've added it to the CMake branch WIP
