### ISSUE TITLE
ICaptionControl triangle is not adapting to a button size and moves relatively to right side

### ISSUE THREAD

**Issue by nezvers** [iPlug2/iPlug2#1107]
**Describe the bug**

**To Reproduce**
ICaptionControl triangle is not adapting to a button size. it is taking a horizontal fraction for it's bounds.
Already has a comment [` //TODO: This seems rubbish`](https://github.com/iPlug2/iPlug2/blob/6c639b97f568a0c3aea872ed2b1598037db482bb/IGraphics/IControl.cpp#L651)

**Expected behaviour**
Keep triangle size relative to IText height.
Keep triangle at the same relative distance from right side and relative to its own size.

**Screenshots**
![image](https://github.com/iPlug2/iPlug2/assets/26794315/86ce02ef-fc1a-4d99-a691-69e22eda5074)

**IMPORTANT DETAILS**
* What plug-in format does it relate to -  ALL?
* What platform does it relate to - ALL?
* What IGRAPHICS_BACKEND does it relate to - ALL?

**Additional context**

**Comment by olilarkin** [comment]
addressed in https://github.com/iPlug2/iPlug2/commit/c5e449ea0ad3983be62bd7ef9db6a737e7104607, thanks!
