### ISSUE TITLE
Changes to IGraphics Mac View breaks platform edit text positioning

### ISSUE THREAD

**Issue by AlexHarker** [iPlug2/iPlug2#1110]
**Describe the bug**
fe1ca6fe86e102a5af28f417b50bc3167f006aaa means that text is not correctly vertically aligned in some cases within the platform text edit.

The commit has two parts - one that shrinks the rectangle by 3 pixels on each side and the other that stops negative adjustments being applied - this second part creates the problem.

**To Reproduce**
Will repro for certain fonts at a given size.

**Expected behaviour**
Text is vertically centred.

**Screenshots**

Before and After

<img width="122" alt="Screenshot 2024-07-13 at 07 49 59" src="https://github.com/user-attachments/assets/1fb92b36-92cf-4f37-873f-3e4e433fa14d">

<img width="116" alt="Screenshot 2024-07-13 at 07 39 22" src="https://github.com/user-attachments/assets/c9032b78-83d8-45ca-88bd-7af8075ce487">

**IMPORTANT DETAILS**
Mac only - IGraphics with platform text entry.

**Comment by olilarkin** [comment]
reverted

**Comment by AlexHarker** [comment]
Thanks
