### ISSUE TITLE
NO_IGRAPHICS does not compile on a Mac

### ISSUE THREAD

**Issue by John-Crosby** [iPlug2/iPlug2#1112]
**Describe the bug**
When using NO_IGRAPHICS flag in preprocessor macros, compiling fails with errors.

**To Reproduce**
In IPlugEffect 
1. in config.h set #define PLUG_HAS_UI 0 
2. in IPlugEffect.cpp comment out all the GUI related code
3. in IPlugEffect-mac.xcconfig NO_IGRAPHICS // IGRAPHICS_NANOVG IGRAPHICS_METAL

**Expected behaviour**
Code should compile as it does on Windows

**Screenshots**
<img width="376" alt="Screenshot 2024-07-22 at 21 37 32" src="https://github.com/user-attachments/assets/5e4ff5a9-47e8-42ca-8900-290333889a12">

**IMPORTANT DETAILS**
* plug-in format ALL
* macOS
* None IGRAPHICS_BACKEND

**Additional context**
I belive this was ok in some earlier versions of the IPlug2

**Comment by olilarkin** [comment]
Are you sure you're not including an IGraphics header? The IPlugConvoEngine example seems to be fine

**Comment by John-Crosby** [comment]
Thanks Oli,
following IPlugConvoEngine example I commented out EXTRA_INC_PATHS =,
EXTRA_LIB_PATHS =, EXTRA_LNK_FLAGS and deleted IGRAPHICS folder from
Frameworks in XCode project.
Now it compiles as it should, with binary size of 510 KB instead of 2.8 MB
:-)

Maybe it would help someone to document steps for GUI-less plug or maybe
direct them to duplicate IPlugConvoEngine?

Thanks again,
Janez


V V tor., 23. jul. 2024 ob 10:22 je oseba Oli Larkin <
***@***.***> napisala:

**Comment by John-Crosby** [comment]
<img width="1316" alt="Screenshot 2024-07-23 at 13 21 02" src="https://github.com/user-attachments/assets/0d03e7ca-2c5e-463a-9206-ea573a2893cc">
