### ISSUE TITLE
GLAD config setup for 3.3, even though we use NanoVG GL2

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#112]
https://github.com/iPlug2/iPlug2/blob/master/Dependencies/IGraphics/glad/include/glad/glad.h#L7

**Comment by olilarkin** [comment]
possibly causing a crash with forced FBO on parallels VM

**Comment by AlexHarker** [comment]
Crash goes away with the correct setup.

**Comment by olilarkin** [comment]
addressed on https://github.com/iPlug2/iPlug2/tree/graphics-gl2gl3glad, just need to test
