### ISSUE TITLE
iPlug2-based plugins have sizing/visual issues in my own VST3 host

### ISSUE THREAD

**Issue by VirtualDAW** [iPlug2/iPlug2#1121]
I tried out some iPlug2-based plugins in my own VST3 host (Windows 10; 64bit), which were built using this iPlug2 framework.

They seem not to load correctly in my own VST3-host.
The sizing is somehow invalid and the User Interface shows only the sand clock cursor 
My host fully supports DPI awareness through manifest. 

The plugin initialization seems to be completed, since the plugin thread runs the process() methods and even produces valid audio output. But its impossible to access the UI when the mouse is the hourglass wait cursor and when its disturbed.

Many other synths (non-iPlug2 plugins) work without problems in my host.

So what could be the reason? Thank you!

**Comment by olilarkin** [comment]
Have you tried debugging it? It should be easy to build one of the examples and pause the debugger when you see the hourglass.

**Comment by VirtualDAW** [comment]
thank you for your answer,
I built IPlugDrumSynth.sln, and it first showed the behaviour, which I experienced with the other iplug2-plugins. 
However, I managed to run it directly from my DLL-host, then now also both iplug2-based plugins work in my host without problems. Seems to be a IPC-related problem in my external EXE-host version.
Solved!

**Comment by VirtualDAW** [comment]
A little bit strange is still, that sometimes (in both cases of my host) the plugin opens correctly and sometimes it still has the hours glass. 
During debugging it does not hang, it correctly processes the "process()" method calls and creates valif output.
Often it helps, if another plugin was run before; But normally that should not be necessary.
Where should I search during debugging ?

**Comment by VirtualDAW** [comment]
After some tests, the plugin is waiting here: 
https://github.com/iPlug2/iPlug2/blob/master/IGraphics/Platforms/IGraphicsWin.cpp#L2271

**Comment by VirtualDAW** [comment]
After a lot of debugging I found, that in case of the hourglass freezing situation, 
the invalidate+redraw part here:
https://github.com/iPlug2/iPlug2/blob/master/IGraphics/Platforms/IGraphicsWin.cpp#L264
is never reached, although WM_VBLANK is notified a lot.

The CALLBACK IGraphicsWin::WndProc is called all the time and the wgl context was correctly initialized.

i'm still investigating the logs.

**Comment by VirtualDAW** [comment]
Finallly I got it done!  Something in the message loop of my host module avoided time-critical handling of the messages. Now all the iplug2-plugins (which I tested; incl. IPlugDrumSynth) work fine in my host!

**Comment by olilarkin** [comment]
Great news! is your host open source btw?

**Comment by VirtualDAW** [comment]
If you want, I can get back to you, if I finished a BETA version of the final product. Yet there's no final User Interface; Only a simulated one for 2 tracks.
