### ISSUE TITLE
IVKnobControl GetParam() gets wrong param and displays wrong value

### ISSUE THREAD

**Issue by Eugene-Y** [iPlug2/iPlug2#113]
It may be a couple of issues, but for now I didn't have time to investigate deeper.

I want to display params values under the knobs, so I do something like this:
GetParam(pId1)->InitDouble("param 1", 0.01, 0.0, 1.0, 0.001);
GetParam(pId2)->InitDouble("param 2", 0.01, 0.0, 1.0, 0.001);
...
pG->AttachControl(new IVKnobControl(rect1,  pId1, "param 1", true));
pG->AttachControl(new IVKnobControl(rect2,  pId2, "param 2", true));

Then the first knob is ok, but the second displays only 0 if param val is < 0.5 and 1 if >= 0.5

Moreover, I've noticed that GetParam() in IVKnobControl::Draw() returns wrong param for all controls but the ones connected to a param with id == 0. 
It's easy to check: just reorder the 1st and the 2nd params in the EParams enum.

Win10, x64 debug build, default project settings, current master branch.

**Comment by AlexHarker** [comment]
Hi @Eugene-Y,

Hard to tell what's going on from your code here, because there isn't enough. I'm assuming pId1 and pId2 are constants, and different and that the plug has at least this many params?

I've just copy pasted the lines of code you have here into IPlugEffect and added relevant rects and everything works fine, so I suspect you have some kind of coding error that we can't see from your post.

**Comment by Eugene-Y** [comment]
Hi @AlexHarker , I'll try to reproduce the issue with clean new project and comment the results here.

**Comment by olilarkin** [comment]
i'm not totally happy with the IVControls, and i've got a branch where i'm reworking it a bit...

https://github.com/iPlug2/iPlug2/tree/graphics-vcontrols

**Comment by Eugene-Y** [comment]
@AlexHarker  @olilarkin  my bad, guys, I've found the error on my side. The controls do work properly.

**Comment by olilarkin** [comment]
no problem, i love clicking the close issue button.....

**Comment by AlexHarker** [comment]
I'm only sad I din't get to click this one :-(
