### ISSUE TITLE
IGraphics dependencies download and build script don't work

### ISSUE THREAD

**Issue by johannesmenzel** [iPlug2/iPlug2#114]
Hello. I have a problem to download the IGraphics deps with the sh-script.

It fails at line 68, with the error 

`download-igraphics-libs.sh: line 68: cd: download-igraphics-libs.sh: Not a directory.`

line 68 is:

`cd "${0%/*}"`

and even though I'm a bit familiar with sh and bash, i cannot figure out what it should be.

**Comment by olilarkin** [comment]
Hi johanees,

what path are you executing the script from? does it have a space in it?

i'm currently modifying this stuff to get it working via continuous integration.

for windows, you can download the built libs via this zip...

https://github.com/iPlug2/iPlug2/releases/download/setup/IPLUG2_DEPS_WIN.zip

latest mac one is broken, should be fixed soon

**Comment by johannesmenzel** [comment]
`cd "dirname ${0}`

**Comment by johannesmenzel** [comment]
The build script is also not working because of some missing directories and files.

I'll try the compiled for now.

**Comment by AlexHarker** [comment]
What platform? - on Mac you can just run the build script which also downloads. The download script is only needed on windows.`

Perhaps we need better naming?

**Comment by olilarkin** [comment]
i am actively modifying these scripts to get it working with CI and probably making the download script cross-platform

**Comment by olilarkin** [comment]
and not downloading with the mac one

**Comment by AlexHarker** [comment]
OK - so the build script needs to downloads taking out....

**Comment by johannesmenzel** [comment]
Unfortunately, I'm on windows.

**Comment by AlexHarker** [comment]
OK - I recently managed to build on windows with no issue, but I think it's best for old to get the scripts in the right state and then we can all test again.
