### ISSUE TITLE
Snapping on IVKnobControl

### ISSUE THREAD

**Issue by codecat** [iPlug2/iPlug2#125]
Is it possible to enable snapping on `IVKnobControl` so that integer values are a bit nicer to pick?

For example, a knob that only allows 3 options currently allows the knob to be set in between 2 options, but obviously that won't change anything as the closest integer value is used instead.

**Comment by olilarkin** [comment]
These controls are not finished,  i’ve done quite a bit of work on a branch.  Things like this are better discussed on Slack or via email, Hence why I have closed the three related issues
