### ISSUE TITLE
Missing include file aeffectx.h for VST2 builds

### ISSUE THREAD

**Issue by codecat** [iPlug2/iPlug2#126]
I get the following error when building a VST2 version of my plugin:

```
1>d:\dev\iplug2\iplug\vst2\iplugvst2.h(20): fatal error C1083: Cannot open include file: 'aeffectx.h': No such file or directory (compiling source file ..\..\..\IPlug\VST2\IPlugVST2.cpp)
```

Am I missing a dependency?

**Comment by BartW123** [comment]
See README.md in \Dependencies\IPlug\VST2_SDK (and README.md in \Dependencies\IPlug\VST3_SDK as well, for VST3's). You can get the necessary files (including the VST2 ones as well) from the "VST 3 Audio Plug-Ins SDK" package at https://www.steinberg.net/en/company/developers.html. 

IF you're not already aware, VST2 has now been deprecated by Steinberg, and licensing restrictions apply if you want to release VST2's - see https://forum.cockos.com/showthread.php?t=212853 and https://forum.juce.com/t/steinberg-closing-down-vst2-for-good/27722.

Cheers,
Bart

**Comment by codecat** [comment]
Thanks for the heads up! I always thought that the VST3 SDK was also able to generated VST2's, but I guess I was wrong, huh..
