### ISSUE TITLE
Making SerializeState a const function is problematic in some cases

### ISSUE THREAD

**Issue by alsms** [iPlug2/iPlug2#127]
SerializeState has been changed to being a `const` function in a recent update. This is problematic in some cases, for example when locking a WDL_Mutex is necessary before the serialization.

**Comment by AlexHarker** [comment]
Hi - that's a change I made.

As a mutex does not change the externally visible state of an object from the outside I believe the conceptually correct approach (and the one I am taking) is to mark the mutex as mutable in the class definition.

The issue with const-correctness seems to me to be that it needs to be followed all the way through a system, and that can be a bit tricky, but I do feel that serialising the state of the plugin shouldn't cause the state of the plugin to change. Therefore, the other roadblocks I had when porting objects were ones that I simply needed to follow through. It is a slightly different question whether all programmers will know how to do that, of course.

If you have other cases I can reconsider this, but I'd rather promote what I think is better practice and to protect against writing a method here that changes the state of the plugin.
