### ISSUE TITLE
IGraphicsNanoVG::EndFrame() leaks memory

### ISSUE THREAD

**Issue by alsms** [iPlug2/iPlug2#128]
I observed a small mount of memory being leaked inside IGraphicsNanoVG::EndFrame(), which seems to be rooted in calling `nvgEndFrame(mVG)`. The allocations are represented as 64 byte allocations in the XCode Leaks Instrument. Because this method is called frequently memory is leaked **continuously**.

I see this problem especially well, if I let a custom control always return `true` inside the `isDirty` method, so that rendering happens without pausing.

I'm on OS X 10.14.1, XCode 10.1 and commit  62af1ac.

![i1](https://user-images.githubusercontent.com/8740854/52553608-54340700-2de4-11e9-9e6b-22c4af7b2527.png)
<img width="1286" alt="i2" src="https://user-images.githubusercontent.com/8740854/52553643-73cb2f80-2de4-11e9-8033-021db4cc5231.png">

**Comment by AlexHarker** [comment]
Thanks - that might be a bit hard to track down - could be in the NVGMetal implementation (rather than IPlugQueue code).

Looking at memory is a task on the to do list, so I'll try to look at this as part of that when I get to it.

**Comment by olilarkin** [comment]
MetalNanoVG in iPlug2 is slightly behind. Possibly this is fixed here:
https://github.com/ollix/MetalNanoVG/commit/0384f3e54d390aa8580c35e0631ec582bb3cf7b5

**Comment by alsms** [comment]
I did another experiment yesterday which showed that that in most cases this might not be a big problem. When rendering stops for a few seconds (3-5 seconds), the memory is being released again. So memory seems not to be leaking, but freeing it just seems to be posponed to a "good" moment. If rendering happens continuously, however, the "good" moment does not come, so memory consumption seems to grow continuously.

**Comment by olilarkin** [comment]
I am closing this as i don't see any evidence of leaks in your screenshots, or when i run the allocations test myself. i will try again when i upgrade to mojave
