### ISSUE TITLE
Plugin fails to compile when using LICE if IPlug_include_in_plug_hdr.h is included *after* IControl.h

### ISSUE THREAD

**Issue by ddf** [iPlug2/iPlug2#130]
This came up for me because I'm converting an iPlug1 plugin that includes my main plugin header in order to cast the delegate to my plugin class in order to call some specific functions. In the cpp for one of my IControl classes I include my control's header first and *then* include my plugin's header. This causes IControl to be included first (from the control's header) and then IPlug_include_in_plug_hdr.h is included.

The build error comes from the declaration of FillRect in IGraphicsLice.h: only virtual member functions can be marked 'override'.

It looks like what's happening is that since IControl.h was included first, IGraphics.h is *not* included after IGraphicsLice_src.h, which means `#define FillRect SWELL_FillRect` is still active.

I can fix the issue two ways. Either including my plugin header *first* in my control cpp files, or by adding this after `#include "IGraphics.h"` in IGraphicsLice.h:

```
#ifdef FillRect
#undef FillRect
#endif
```

**Comment by AlexHarker** [comment]
This SWELL stuff is really really annoying as anywhere that swell.h gets included this infects things. The best approach is to fix it *immediately* after including swell.h in any headers. I'll look into doing this. there are a few other macros like this to catch also.

The problems can also arise if you have swell.h included somewhere for some other reason.

**Comment by AlexHarker** [comment]
I think I've addressed this here - can you check on this branch?

https://github.com/iPlug2/iPlug2/tree/swell-clashes

**Comment by AlexHarker** [comment]
Now on master

**Comment by ddf** [comment]
appears to work now, thanks!
