### ISSUE TITLE
Windows native text input flickers when used with NanoVG

### ISSUE THREAD

**Issue by ddf** [iPlug2/iPlug2#133]
I have a TextBox control (https://github.com/ddf/SpectralHarp/blob/v2.0.0/TextBox.cpp) that subclasses ICaptionControl which calls PromptUserInput in OnMouseDown. Most of the time the native text input can only be seen as a flickering cursor. The box is there and works, but seems to be getting repeatedly drawn over by the TextBox UI. *Sometimes* it works properly, but I wasn't able to isolate why this is the case. It seemed possibly related to having another element in the layout continually drawing (by calling SetDirty from it's Draw method) or to the fact that there is a static UI element that renders under the TextBox.

**Comment by ddf** [comment]
From what I can tell, it is the code in IGraphicsWin.cpp that responds to WM_PAINT which is causing this problem because when the mouse is over the text box, Windows wants that rect to be repainted. Since the rect overlaps my TextBox and also the static element underneath the text box, these are included in the rects passed to pGraphics::Draw. I don't know enough about Windows to know why the native text box then doesn't paint over the IGraphics data.

FWIW this does not happen when using Cairo or LICE.

**Comment by AlexHarker** [comment]
I think the difference is that OpenGL is directly accessing the window so the normal concepts of "over" and"under" don't apply. There is some windows stuff for revalidating an area of the display (so it is not drawn), but I will need to check it. I believe that this kind of issue *can* happen on Mac, but only with Cairo, so ideally we'd look at all of it together.

**Comment by olilarkin** [comment]
Some changes have recently been made which may affect this, with the igraphics vsync stuff

**Comment by olilarkin** [comment]
This has been addressed in https://github.com/iPlug2/iPlug2/commit/156f679c21b20ba74fa68853acee58a8c4d99182#diff-20fd113c0c2dd4027c46483cbfc0f83b

WS_CLIPCHILDREN and WS_CLIPSIBLINGS were added to CreateWindow calls
