### ISSUE TITLE
VST3: Under Win10 in BitWig 2.5 beta 7  ITimeInfo::mSamplePos is always -1.0000000

### ISSUE THREAD

**Issue by janhase88** [iPlug2/iPlug2#134]
if you can reproduce:
it works in Bitwig 2.4.3 and it works with VST2 in beta 7 . In 2.5 beta 6 there was something with transport:

Regression Fixes
VST3 plug-ins could receive the wrong transport playback state flags (playing or recording)

...maybe its connected to mSamplePos not changing? because it works in 2.4.3 i suppose the bug is in bitwig...i sent an email @ bitwig

**Comment by nickallen74** [comment]
This should be fixed in the next build and the final 2.5

**Comment by olilarkin** [comment]
As I understand it this is not an iplug issue, closing
