### ISSUE TITLE
Fix nanosvg / nanovg handling of compound shapes

### ISSUE THREAD

**Issue by madronalabs** [iPlug2/iPlug2#135]
I made some outlined letters in a drawing program and exported them to SVG. These look good in the SVG renderer built into XCode but using IGraphicsPathBase::RenderNanoSVG() the path directions are wrong: holes are not where they should be and a really ugly backwards edge antialiasing happens for clockwise paths.

The nanosvg parser does not attempt to set fill rules for NSVGshapes based on the geometry; it just copies whatever's in the XML attributes. So inspecting the geometry is needed to set the winding directions properly. 

Andrew Belt seems to have solved the issue in VCVRack. The relevant glue code is here: https://github.com/VCVRack/Rack/blob/v1/src/svg.cpp

More discussion here: https://github.com/memononen/nanosvg/issues/58

I'm happy to work on a fix a bit later but right now I am just going to use the text renderer instead.

**Comment by AlexHarker** [comment]
NanoSVG seems to have a few issues. I'd be happy to switch it for something better when we have the change.

FWIW - any reason you are not using DrawSVG? That will be robust to future changes in the SVG parsing.

**Comment by madronalabs** [comment]
I am using DrawSVG() which calls RenderNanoSVG().

**Comment by madronalabs** [comment]
Text wasn't working well so I fixed the NanoSVG render—see my PR

**Comment by olilarkin** [comment]
addressed in adfdfbac4fccbea23151ec8d357b4f704fd77d9d
