### ISSUE TITLE
Enable font loading from .ttc collections

### ISSUE THREAD

**Issue by madronalabs** [iPlug2/iPlug2#138]
It looks like stb_truetype can load fonts from .ttc collections so hopefully this will be easily doable in all backends. My immediate need is to fall back to system fonts for text in CJK scripts; these are all in .ttc on Mac and Windows.

**Comment by olilarkin** [comment]
You can also use freetype with nanovg by defining IGRAPHICS_FREETYPE if that’s any use

**Comment by AlexHarker** [comment]
This will be coved by #36 (but hasn't been done yet). However, I'm closing to clean-up the issues list
