### ISSUE TITLE
CornerResizer layoutOnResize leads to assertion errros

### ISSUE THREAD

**Issue by alsms** [iPlug2/iPlug2#139]
The examples show that a corner resizer is attatched inside the layout function (`mLayoutFunc = [&](IGraphics* pGraphics) { pGraphics->AttachCornerResizer(kUIResizerSize, false);...`). If the boolean parameter `layoutOnResize` of method `AttachCornerResizer` is set to `true`, then an assertion error will occur, because the layout function is now called multiple times and another corner resizer is being attatched to the control, but only one is allowed.

**Comment by olilarkin** [comment]
This is by design. You need to check pGraphics->NControls() at the top of your layout function to see if controls have been added yet. If so, modify or remove existing controls accordingly

**Comment by alsms** [comment]
I see, thanks. It would be good to document this somewhere, because I think I am not the last one to report this as an issue. If you need help, I can do this. Just ping me in the slack channel.

**Comment by olilarkin** [comment]
we need help with the documentation for sure https://github.com/iPlug2/iPlug2/projects/2
