### ISSUE TITLE
When an IControl DrawArea which is ontop of another DrawArea, is set dirty the underlying DrawArea is set dirty as well

### ISSUE THREAD

**Issue by janhase88** [iPlug2/iPlug2#140]
in order for my graph to not consume too much cpu when drawing many thousand lines i split the graphdisplay in many icontrols which then get setdirty sequencially. ontop is another icontrol which handles mouseinput and draws a hud. when that hudicontrol is set dirty the underlying graphdisplayparts are also set dirty. here is an example class:

  /////////////
  /// multiple icontrols (UnderLyingLayers), that change color when setdirty, 
//are drawn next to each other. An Icontrol (OntopLayer) is ontop the 10 IControls and 
//draws a rectangle border that changes color on mouseover.
  /// on mouse over (ontoplayer setdirty) the UnderlyingLayers get setdirty() as well
  /// but the underlyinglayers shouldnt be affected by setdirty of the OnTopLayer

```javascript
class SetDirtyTest {
  ////To Implement:
  // plug.h: SetDirtyTest SDT;
  // plug.cpp => mLayOutFunc: SDT.AttachGraphics(pGraphics, b, -1);

public:
  class UnderLyingLayers;
  class OnTopLayer;

  int NumColorRects = 10;
  std::vector<UnderLyingLayers*> ColorFields;
  OnTopLayer *OTL;

  SetDirtyTest() {
    ColorFields.resize(NumColorRects);
  }

  void AttachGraphics(IGraphics *pGraphics, IRECT bounds, int paramidx) {
    pGraphics->HandleMouseOver(true);

    for (int c = 0; c < NumColorRects; c++) {
      IRECT PartRect = IRECT(bounds.L + (bounds.W() / NumColorRects * c), bounds.T, bounds.L + (bounds.W() / NumColorRects * (c + 1)), bounds.B);
      ColorFields[c] = new UnderLyingLayers( pGraphics, &PartRect,paramidx);
      pGraphics->AttachControl(ColorFields[c]);
    }

    OTL = new OnTopLayer(pGraphics, &bounds, -1);
    pGraphics->AttachControl(OTL);
  }

  class UnderLyingLayers : public IControl {
  public:

    IRECT Bounds;
    UnderLyingLayers(IGraphics* pgraphics, IRECT *bounds, int paramidx) : IControl(*bounds, paramidx) {
      mIgnoreMouse = true; Bounds = *bounds; }

    virtual void Draw(IGraphics& Graphics) override{ Graphics.FillRect(IColor::GetRandomColor(),Bounds,0);}
};


  class OnTopLayer : public IControl {
  public:

    IRECT Bounds;
    OnTopLayer(IGraphics* pgraphics, IRECT *bounds, int paramidx) : IControl(*bounds, paramidx) { Bounds = *bounds;}

    virtual void Draw(IGraphics& Graphics) override { Graphics.DrawRect(IColor::GetRandomColor(), Bounds, 0,50);  }

    virtual void OnMouseOver(float x, float y, const IMouseMod& mod) override{
      mMouseIsOver = true;  SetDirty(false);
    }
  };

};
```

**Comment by olilarkin** [comment]
IGraphics doesn't have depth testing on controls.  I believe you could achieve what you want by overriding IsHit() on the control underneath: https://github.com/iPlug2/iPlug2/blob/master/IGraphics/IControl.h#L289

Alternatively,  you could check out the new layer functionality in IGraphics:

https://github.com/iPlug2/iPlug2/blob/master/IGraphics/Controls/Test/TestLayerControl.h

**Comment by janhase88** [comment]
WOW the new layer system is absolutly AMAZING!!!!! Thx so much Oli!!!! ...oh i am so happy right now...just added a layer to the underlying icontrol and it works, the ontop icontrol is still setting the underlying dirty, but instead of redrawing it it just uses the cached layer *jumping happily around

```javascript
  class UnderLyingLayers : public IControl {
  public:
    ILayerPtr Layer;
    IRECT Bounds;
    UnderLyingLayers(IGraphics* pgraphics, IRECT *bounds, int paramidx) : IControl(*bounds, paramidx) {
      mIgnoreMouse = true; Bounds = *bounds; }

    virtual void Draw(IGraphics& Graphics) override{

      //Graphics.FillRect(IColor::GetRandomColor(),Bounds,0);

      if (!Graphics.CheckLayer(Layer))
      {     
        Graphics.StartLayer(Bounds);
        Graphics.FillRoundRect(IColor::GetRandomColor(), Bounds, Bounds.W() / 4.0);      
        Layer = Graphics.EndLayer();
      }
      Graphics.DrawLayer(Layer);
    }
};
```

**Comment by olilarkin** [comment]
You can thank @AlexHarker

**Comment by AlexHarker** [comment]
Technically the area underneath is never set dirty, but all items are redrawn in the area of the control that is set dirty. Due to clipping etc. the underlying control may not be fully redrawn (it may also be redrawn in different parts more than once on a draw cycle). Anyway - as Oli says - layers are the way to keep expensive things around. Glad you like them? Seems like this one can probably be closed up?

**Comment by janhase88** [comment]
Yes i love them!!!!...i had to restructure everything in my plugin today and now everything is soo soo much easier and i save a ton of cpu and so many new possibilities, Thanks Alex!!!!!!!! .... ja saw the clipping as well, now. issue can be closed :-)
