### ISSUE TITLE
When Rectangles are drawn perfectly aligned, on windowresize the background becomes visible "in between" them

### ISSUE THREAD

**Issue by janhase88** [iPlug2/iPlug2#141]
this example draws 10 blue filled rectangles next to each other ontop of a red background. when the plug is loaded and drawscale =1, they align perfectly and the whole everything is blue. on resizing on the borders of the rects the red background shines through. how much it shines through is different if the rectangles are drawn from within a layer or not. on mouseclick in this examples it switches between drawing from a layer and plain direckt drawing to make the difference visible.

***i assume because the rects on rescaling get floating values and because there are no halfpixels nano does stuff it normally is supposed to do but not in this case. maybe some new type like IRECT_ALWAYS_INT would be a good idea, to serve both purposes?

```c++
///to test: pGraphics->AttachControl(new IRectUnionTest(b));
class IRectUnionTest : public IControl {
public:
  std::vector<IRECT> RectArray;
  std::vector<ILayerPtr> LayerArray;
  IRECT bounds;
  bool DrawLayer = false;

  IRectUnionTest(IRECT Bounds) :IControl (Bounds) {
    bounds = Bounds;
    RectArray.resize(10);
    LayerArray.resize(10);
  }
 
  virtual void Draw(IGraphics& Graphics) override {

    Graphics.FillRect(COLOR_RED, bounds, 0);
   
    for (int c = 0; c < RectArray.size(); c++) {

      RectArray[c] = IRECT(bounds.L + (bounds.W() / RectArray.size() * c), bounds.T, bounds.L + (bounds.W() / RectArray.size() * (c + 1)), bounds.B);

      if (DrawLayer) {
        if (!Graphics.CheckLayer(LayerArray[c]))
        {
          Graphics.StartLayer(RectArray[c]);
       
            Graphics.FillRect(COLOR_BLUE, RectArray[c]);

          LayerArray[c] = Graphics.EndLayer();
        }
        Graphics.DrawLayer(LayerArray[c]);
        LayerArray[c]->Invalidate();
      }
      else {
        Graphics.FillRect(COLOR_BLUE, RectArray[c]);
      }
    }
  }

  virtual void OnMouseDown(float x, float y, const IMouseMod& mod) override {
    DrawLayer = !DrawLayer;
  }
};
```

**Comment by AlexHarker** [comment]
I'll try to check this out - this sort of thing is stuff I've mostly worked on, but I thought I'd caught any errors. The issue here is that there are various levels of anti-aliasing (so yes half or fractional pixels exist), and clipping and also pixel alignment going on for drawing and clipping areas. This was designed to avoid edge effects (see https://github.com/iPlug2/iPlug2/issues/13), but obviously I've missed something. There is also possible numerical error when I pixel align accounting for scaling (where the pixels of the original UI are no longer aligned with real pixels).

Testing on cairo would be appreciated if you are set up to do this to see if this is a conceptual problem or something to do with the drawing API.

**Comment by AlexHarker** [comment]
OK - it was easier to get running than I thought. I think this is at least in part a conceptual issue actually as I think if each rectangle was in its own control this would work.

I think if you call GetPixelAligned(Graphics.GetDrawScale() * Graphics.GetScreenScale()) on each IRECT before drawing this fixes the issue for no-layer based drawing. This makes sure all rects are aligned to actual screen pixels (there's almost certainly a case for making this simpler to do by a least having a method to get screen pixel scale). However, with layers this doesn't work very well with NanoVG (it works better with Cairo but it isn't 100% perfect). I'll try to investigate further, but using separate layers for this kind of thing is somewhat of an edge case and I'm not 100% that there is an easy fix.

**Comment by janhase88** [comment]
woah! for getting it to work outside of layers i modified the rect before drawing like this : 

     double L = int(RectArray[c].L * drawscale) / drawscale;
        double R = int(RectArray[c].R * drawscale) / drawscale;
        double T = int(RectArray[c].T * drawscale) / drawscale;
        double B = int(RectArray[c].B * drawscale) / drawscale;

       RectArray[c] = IRECT(L, T, R, B);

which will "internally" result in  that the rect LTRB are always int at any drawscale. then i recognized that its not working like this with layers . so in startlayer() i tested to pass r.w() and r.h()  into createapibitmap() without aligning pixels before, and in createapibitmap scale*w and scalw*h i erased the std::round. then startlayer created the layer exactly as the rect put into it. when the inputrect was modified like *above, the tiling was working inside layers - but then other things start to happen on the edge when drawing lines smaller then 1 pixel(i think i saw this, but am not 100% sure)..but this didnt solve it satisfyingly...

**Comment by AlexHarker** [comment]
Your solution without layers is similar to mine although it isn't clear whether it takes into account both draw scale and screen scale (for retina), because I can't see where draw scale comes from. In fact GetPixelAligned always pushes outwards (not rounding) so it is isn't quite right for what you need (you could get single pixel overlaps) The whole point of GetPixelAligned() is to take some of the pain out of this sort of thing for you, but it might be that another function with rounding is required (truncation is less representative of what the rect actually is).

For layers it gets much more complex, because the rounded etc. is designed to make sure you can draw right the way to the edge of the layer you have requested. The changes you've made will probably break that. I need to look at that again to see what is going on in more detail.

I'll take another pass at this when I get a free moment.

**Comment by AlexHarker** [comment]
So - this is what I'd propose for alignment without layers (which works):

`inline IRECT Align(const IRECT &r, float scale = 1.f)
    {
        IRECT par(r);
        
        par.Scale(scale);
        par.L = std::round(par.L);
        par.T = std::round(par.T);
        par.R = std::round(par.R);
        par.B = std::round(par.B);
        par.Scale(static_cast<float>(1.0/static_cast<double>(scale)));
        
        return par;
    }

                Graphics.FillRect(COLOR_BLUE, Align(RectArray[c], Graphics.GetDrawScale() * Graphics.GetScreenScale()));

`

Layers don't work with that

**Comment by janhase88** [comment]
yes, its just GetDrawScale(), didnt knew what getscreenscale was for, so thanks for clearing that up.
nice that works, thank you! 
excactly, i had it working with layers, but needed to truncate everything in PixelAlign, with your solution it works with layers without truncating like this:

in IGraphicsNanoVG.cpp:
```c++
APIBitmap* IGraphicsNanoVG::CreateAPIBitmap(double width, double height)

{
 
//now takes doubles and doesnt roundf the result of (width * scale) 
//havent checked top/down tiling, assume same is applicable for height * scale

 const double scale = GetBackingPixelScale();
  
return new NanoVGBitmap(this, mVG, width * scale, std::round(height * scale), GetScreenScale(), GetDrawScale());

}
```
IGraphics.cpp:
```c++
void IGraphics::StartLayer(const IRECT& r)

{
//i put r straight through because the Aligned Rect is handed to startlayer

 PushLayer(new ILayer(CreateAPIBitmap(r.W(), r.H()), r), true);
}
```
and in the example:
```c++
Graphics.StartLayer(Align(RectArray[c], Graphics.GetDrawScale() * Graphics.GetScreenScale()));

 Graphics.FillRect(COLOR_BLUE, Align(RectArray[c], Graphics.GetDrawScale() * Graphics.GetScreenScale()));
```

this might be a different issue, but is related, i think:
above changes excluded, back to your original code: with drawing the rect without layers - your solution works there very well - now i would expect, that when the rects are drawn like this within layers that are bigger then the united rects, then they shouldnt "interfere" with the rect bounds inside and therefore that shouldnt cause overlapping/spacing as well, but it does. i assume it is probably intended, that content, which is drawn within a layer, is displayed excactly as content thats not in a layer, except the layerbounds cut the content?... i discovered when layers get sequenceally invalidated in my plug, where the cursor jumps to the next layer and the former live drawn layer (invalidating it on each drawcycle) is now drawn from cache, there occurs pixelshifting with the whole layer  right in the moment it gets drawn first time from cache, after that it stays in pixelshifted position until invalidated again. the shift occurs only, once when it switches from livedrawing  to cached and only if drawscale is not 1 or 2 or 0.5. the shift is one pixel and goes sometimes left sometimes right sometimes not. when drawscale is 1 or 2 or 0.5 it fluently switches between live drawing and cached drawing without shift. so i assume, that when drawscale is not 1 or 2 or 0.5, when the layer gets drawn rightafter it was invalidated, it gets somewhat differently drawn as when redrawn from cache. havent written an exclusiv example for this precisely to retest, but the fact, that it doesnt happen when drawscale is 1, leads me to believe that, that this is a issue. might that be possible and might that be related to why the aligned rects drawn in biggerlayers still cause overlapping/gapping, even though previously aligned with your function?

i updated the example with some info and ready to test the biggerlayer vs normal thing if needed:

```c++

class IRectUnionTest : public IControl {
public:
  std::vector<IRECT> RectArray;
  std::vector<ILayerPtr> LayerArray;
  IRECT bounds;
  IBlend Blend;
  bool DrawLayer = false;

  IRectUnionTest(IRECT Bounds) :IControl(Bounds) {
    bounds = Bounds;
    RectArray.resize(10);
    LayerArray.resize(10);
    Blend.mWeight = 0.5;
  }

  virtual void Draw(IGraphics& Graphics) override {

    Graphics.FillRect(COLOR_RED, bounds, 0);

    for (int c = 0; c < RectArray.size(); c++) {

      RectArray[c] = IRECT(bounds.L + (bounds.W() / RectArray.size() * c), bounds.T, bounds.L + (bounds.W() / RectArray.size() * (c + 1)), bounds.B);

      if (DrawLayer) {

        if (!Graphics.CheckLayer(LayerArray[c]))
        {
          IRECT BiggerRect = IRECT(RectArray[c].L - 10, RectArray[c].T - 10, RectArray[c].R + 10, RectArray[c].B + 10);
          Graphics.StartLayer(BiggerRect);

          Graphics.FillRect(COLOR_BLUE, Align(RectArray[c], Graphics.GetDrawScale() * Graphics.GetScreenScale()), &Blend);

          LayerArray[c] = Graphics.EndLayer();
        }

        Graphics.DrawLayer(LayerArray[c]);
        LayerArray[c]->Invalidate();
      }
      else {
        Graphics.FillRect(COLOR_BLUE, Align(RectArray[c], Graphics.GetDrawScale() * Graphics.GetScreenScale()), &Blend);
      }

      DrawInfo(Graphics, c);
    }
  }

  inline IRECT Align(const IRECT &r, float scale = 1.f)
  {
    IRECT par(r);
    par.Scale(scale);
    par.L = std::round(par.L);
    par.T = std::round(par.T);
    par.R = std::round(par.R);
    par.B = std::round(par.B);
    par.Scale(static_cast<float>(1.0 / static_cast<double>(scale)));
    return par;
  }

  inline void DrawInfo(IGraphics &Graphics, int c) {
    if (DrawLayer)
    {     
      Graphics.DrawRect(COLOR_GRAY, IRECT(LayerArray[c]->Bounds().L, LayerArray[c]->Bounds().T + LayerArray[c]->Bounds().H() / 10 * 8, LayerArray[c]->Bounds().R, LayerArray[c]->Bounds().T + LayerArray[c]->Bounds().H() / 10 * 9), &Blend, 1);
      Graphics.DrawText(IText(bounds.H() / 10, COLOR_WHITE), "Layer", IRECT(bounds.L + 10, bounds.T + 10, bounds.R + 50, bounds.T + 30));
    }
    else {
      Graphics.DrawRect(COLOR_GRAY, IRECT(RectArray[c].L, RectArray[c].T + RectArray[c].H() / 10 * 8, RectArray[c].R, RectArray[c].T + RectArray[c].H() / 10 * 9), &Blend, 1);
      Graphics.DrawText(IText(bounds.H() / 10, COLOR_WHITE), "Normal", IRECT(bounds.L + 10, bounds.T + 10, bounds.R + 50, bounds.T + 30));
    }
  }

  virtual void OnMouseDown(float x, float y, const IMouseMod& mod) override {
    DrawLayer = !DrawLayer;
  }
};
```

**Comment by AlexHarker** [comment]
OK - thanks for pointing to the sources of the issue. Unfortunately your fixes are likely to cause problems with other things (such as efficiency or possibly other edge effects)> However, by changing all the std::round class to std::Ceil I've fixed up layers.

You still need to do the alignment of the rect yourself, but it now should work with or without layers, so please pull from master and discard your changes to check.

I'll think about naming for this kind of alignment stuff and I think probably IGraphicsTest should have a method to align/snap a rect to the nearest screen pixels - might need to talk to @olilarkin before I finalise all of that, however.

**Comment by AlexHarker** [comment]
OK - I've just added IGraphics::GetPixelSnapped() to do this more simply.

I think this can now be closed - is that right?

**Comment by janhase88** [comment]
hmm am super happy, that my input might have helped with this. and thanks for your help, Alex! ... i am not using git yet, so i am not uploading my changes anywhere (to afraid to mess things for you guys, yet)...
where did you change std::round to ceil ?? ... yes, i think it can be closed :-)

**Comment by AlexHarker** [comment]
See these commits:

https://github.com/iPlug2/iPlug2/commit/ea2d1402232f46bc5803df2fe89f9eb7bdbb52aa

https://github.com/iPlug2/iPlug2/commit/8171706dcb5dfcf4946a2fba48518b6029614aaf
