### ISSUE TITLE
macOS 32 bit build fails in IGraphicsMac_view.mm

### ISSUE THREAD

**Issue by hor-net** [iPlug2/iPlug2#142]
When building the 32bit version of mac plugin the build fails with a c++11-narrowing error thrown on lines 723 and 724 of IGraphicsMac_view.mm

the two offsets are defined as double, the should be CGFloat instead, this fixes the problem.

**Comment by olilarkin** [comment]
can you make a PR? i can't compile 32 bit any more

**Comment by AlexHarker** [comment]
sounds like a warning that is being promoted to an error.

**Comment by hor-net** [comment]
Sent the pull request:  
https://github.com/iPlug2/iPlug2/pull/143

**Comment by AlexHarker** [comment]
I fixed this slightly differently using static_casts - can you test?

**Comment by olilarkin** [comment]
closing this as i am fairly sure Alex's fix will have solved it

**Comment by AlexHarker** [comment]
Thanks Oli - I did test against 32bit here and it made it work.
