### ISSUE TITLE
Make build scripts parameterized

### ISSUE THREAD

**Issue by alexliesenfeld** [iPlug2/iPlug2#148]
For licensing reasons some cannot ship VST2 and AAX with the plugin. Currently these are hardwired in the build scripts and it is an additional overhead to remove these lines from the build scripts and it is harder to maintain these files over time. 

It would be good if these scripts could be parameterized to include only the specified plugin formats in the build.

**Comment by olilarkin** [comment]
the new mac installer script here does this:
https://github.com/iPlug2/iPlug2/tree/installer_script/Examples/IPlugEffect/scripts

Would you like to submit a PR for modifications to the windows equivalent?

**Comment by alsms** [comment]
In the next 3 weeks I won't be able to find some time for it but I will revisit this issue thereafter and will start working on it if it is still open.

**Comment by alsms** [comment]
@olilarkin In `make_installer-mac.sh` of the branch `installer_script` a new distribution.xml file is created each time the script is executed. In the Windows counterpart I am currently working on I just replace the relevant entries from the ISS file depending on the parameters passed to the script. This allows the user to make personalized adjustments to the ISS file and installers. For consistency, which approach should we choose? Replacing relevant entries in the installer description files or recreating them from scratch?

**Comment by alsms** [comment]
Submitted pull request #218

**Comment by olilarkin** [comment]
this is done on the iPlug2OOS template. when complete will update main examples scripts

https://github.com/iPlug2/iPlug2OOS
