### ISSUE TITLE
IGraphics Layers causing deadlock with latest Metal NanoVG

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#152]
Trying to update to the latest Metal NanoVG on this branch https://github.com/iPlug2/iPlug2/tree/graphics-updatenvg

Latest version switches to use ARC, but there are some other modifications too. With IGraphics layers controls enabled in IGraphicsTest i get deadlocks. Possibly related to this commit: https://github.com/ollix/MetalNanoVG/commit/e206b0b8f0dcf38a92d111a331383780bbbf87cf

**Comment by olilarkin** [comment]
https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/MTLBestPracticesGuide/TripleBuffering.html

**Comment by AlexHarker** [comment]
I tried to fix this with dfcbf77354e8e22adc692cf8f2024973120c9562 but it doesn't seem to work fully.

Can you merge master into the update NBG branch (there are a few conflicts that it'd be better for you to check than me) and then I'll test again?

**Comment by AlexHarker** [comment]
I believe be53a37b806cae660caa611580a80be77a762615 fixes this!

**Comment by olilarkin** [comment]
Fixed
