### ISSUE TITLE
Crashes on application quit with nanoVG

### ISSUE THREAD

**Issue by madronalabs** [iPlug2/iPlug2#160]
When I quit any plugin or app made with iGraphics / nanovg I'm getting frequent crashes.

IGraphicsMac::CloseWindow() calls [view removeFromSuperview] which in turn calls IGraphicsMac::CloseWindow() again. Can this be right? It makes this code possibly harder than necessary to reason about. It also looks like there is potentially a race condition on mView.

The crash occurs in IGraphics::RemoveAllControls(), where it looks like the IGraphics object is in the process of being freed because the member variables point to garbage.

**Comment by olilarkin** [comment]
yes, i've been getting this too, intermittantly, but fairly regularly. commenting [view removeFromSuperview] hasn't solved things

**Comment by AlexHarker** [comment]
I've seen this a lot - I think Randy is right - there is some logic that looks like it prevent are-etrancy issues, but it is possible that there is a threading/race condition issue.

**Comment by olilarkin** [comment]
Something still funny here. This might help...

https://github.com/iPlug2/iPlug2/commit/2526e838c7515b16e3c66e3edd7dae7f2712c675

**Comment by AlexHarker** [comment]
Where are the new crashes? This might be a separate issue.

**Comment by AlexHarker** [comment]
I have no crashes here.

**Comment by madronalabs** [comment]
I get the nanovg / semaphore crash regularly in iGraphicsStressTest.

**Comment by olilarkin** [comment]
Do you still get that with the tip?  Since I modified nanovgmtl?

**Comment by madronalabs** [comment]
Yes, I frequently get a crash in Nanovg_mtl.m, line 1104:
  dispatch_release(mtl->semaphore);


Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

**Comment by olilarkin** [comment]
i just had one too

**Comment by AlexHarker** [comment]
If the crash is always in Nanovg_mtl.m then this is a different issue to the one we started with.

**Comment by olilarkin** [comment]
yeah i think there are two issues

**Comment by AlexHarker** [comment]
Probably be53a37b806cae660caa611580a80be77a762615 fixes this?

**Comment by olilarkin** [comment]
closing this because we think it is fixed. if the crash appears again reopen
