### ISSUE TITLE
Possible Typo in IGraphicsStructs.h

### ISSUE THREAD

**Issue by dmsplugins** [iPlug2/iPlug2#175]
"void FlashCircleClickAnimationFunc(IControl* pCaller);" appears as an undefined function in IGraphicsStructs (line 54). 
In IControl.cpp (line 43), "void FlashCircleAnimationFunc(IControl* pCaller)" is defined and is then later called by "FlashCircleClickActionFunc" on line 58. Is this just a typo?

**Comment by olilarkin** [comment]
good catch
