### ISSUE TITLE
Standalone with Cairo on Mac crashes

### ISSUE THREAD

**Issue by drakfluga** [iPlug2/iPlug2#176]
Building standalone with Cairo on Mac and running the app crashes on resizing and/or closing the app with the following:

Assertion failed: (s->stack->next != NULL), function CGGStackRestore, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreGraphics/CoreGraphics-1249.2/CoreGraphics/Context/CGGStack.c, line 77.

macOS 10.14.3, Xcode 10.2

**Comment by olilarkin** [comment]
can't reproduce on 10.13

**Comment by drakfluga** [comment]
Hm. I'll try a clean repo and/or test on some more machines tomorrow.

**Comment by AlexHarker** [comment]
Any update? - I can't reproduce here on 10.12.6 either. 

This might be a Mojave issue with Cairo in Quartz mode.

**Comment by AlexHarker** [comment]
Also - a larger stack trace would be useful to check this is Cairo related.

**Comment by AlexHarker** [comment]
Please reopen if you can reproduce - so far no-one has been able to.
