### ISSUE TITLE
Knobs on Cubase keep resetting

### ISSUE THREAD

**Issue by codecat** [iPlug2/iPlug2#183]
Everytime I release the mouse button, the parameter resets to its default value. Only happens on Cubase, works fine in FL Studio. Have not tested on Mac yet.

See video: https://youtu.be/nxndEUPEZQc

This happens on the IPlugEffect example as well.

* Cubase Elements on Windows 10.0.15 Build 136
* Latest master branch commit as of reporting this issue

**Comment by codecat** [comment]
Thanks for the quick fix! It seems like only a partial fix though - the issue remains, but it's fixed visually: https://www.youtube.com/watch?v=EPjEJUcyfdo

**Comment by olilarkin** [comment]
i see, i mean hear :-(

**Comment by AlexHarker** [comment]
VST2 or 3?

**Comment by codecat** [comment]
VST3

**Comment by AlexHarker** [comment]
Thanks - will take a look - I presume this is still the case?

**Comment by codecat** [comment]
I haven't tried for a while, sorry :/

**Comment by AlexHarker** [comment]
Really good catch - this was a result of my zealous code culling in VST3 over the Christmas break, which Oli then merged in later. I shouldn't have left it unchecked, but I clearly took out some code that looked unnecessary, but that was very much necessary for correct host communication.

It is fixed here:
2b858e33a127e022d7a4d376451c56201d037c8b
