### ISSUE TITLE
vst3 chunk cant be loaded in Win Bitwig after deactivating/reactivating AudioEngine

### ISSUE THREAD

**Issue by janhase88** [iPlug2/iPlug2#203]
i recently updated to a newer vst sdk (vstsdk3613_08_04_2019_build_81) and since then in Bitwig the chunks can not be loaded anymore

![2019-04-23-18-43-14](https://user-images.githubusercontent.com/46456607/56599934-e718cb00-65f7-11e9-9d8f-69d5284f492f.png)

[Put_In_IPlugEffect.zip](https://github.com/iPlug2/iPlug2/files/3245066/Put_In_IPlugEffect.zip)

*updated example , because some things changed in iplug [02.06.2019]

**Comment by janhase88** [comment]
[SerializationTest built vsts.zip](https://github.com/iPlug2/iPlug2/files/3103807/SerializationTest.built.vsts.zip)

**Comment by AlexHarker** [comment]
I can't reproduce on Reaper or Bitwig using a Mac.

When I break in IPlugVST3State::GetState() and IPlugVST3State::SetState() in Reaper then the methods return correctly and the text string is restored. 

I did set #PLUG_DOES_STATE_CHUNKS 1 in config.h - I assume you are doing that, but you didn't mention it in the code you sent.

You mention updating the VST3 SDK - did you also update IPlug2 to the latest?

**Comment by janhase88** [comment]
it is working in reaper here as well vst2/3. plug does chunk is 1 - yes. i also updated iplug2.

**Comment by janhase88** [comment]
you probably tested with bitwig 2.5.1 RC5 ? i just tried that and there it works - should have tested that - only tried 2.5. so on the next release everything should be fine. issue can be closed, right?

**Comment by janhase88** [comment]
[Put_In_IPlugEffect.zip](https://github.com/iPlug2/iPlug2/files/3245055/Put_In_IPlugEffect.zip)
*updated example , because some things changed in iplug

**Comment by AlexHarker** [comment]
Is this still happening with the latest version of iPlug 2?

**Comment by janhase88** [comment]
yes, i retested yesterday [02.06.2019] with the latest iplug2 version and bitwig 3 beta 4.

**Comment by janhase88** [comment]
retested now with bitwig 3.02 - seems to work now
