### ISSUE TITLE
CornerResizer Disappears when PlugWindowSize is drecreased "to fast" (Ableton/Bitwig/Win10)

### ISSUE THREAD

**Issue by janhase88** [iPlug2/iPlug2#208]
tested with IPlugEffect:

In Bitwig: when the PlugWindow is resized to fast the corner resizer disappears. when closed and reopenend plugwindow is scrambled - deactivating/activating plugin resets issue.

in Ableton: basically same thing, except that when the plugwindow is reopened the corner resizer reappears

![2019-04-28-16-19-33](https://user-images.githubusercontent.com/46456607/56865915-ba87f900-69d3-11e9-92e1-69f103f36173.gif)

**Comment by AlexHarker** [comment]
The corner resize hasn't disappeared here - somehow you've managed to resize the window without the internal content resizing.

**Comment by AlexHarker** [comment]
[so the corner resize is off screen]

**Comment by asedev** [comment]
What about a forced full repaint in the OnMouseUp event?

**Comment by AlexHarker** [comment]
It's not a repaint issue I don't think - I suspect that the resizing hasn't occurred correctly. I'll test on windows when I'm back in the UK with more time.

**Comment by AlexHarker** [comment]
Can anyone confirm that this only happens when you release at the end of a mouse gesture? If I run windows in parallels and try to reproduce I don't get the issue unless I release the mouse at the end of the movement. When I hold the button down everything is fine.

**Comment by AlexHarker** [comment]
OK - think I've got this.

Is anyone set up to build and test VST3 / AAX on windows?

I've got a branch to test with here: https://github.com/iPlug2/iPlug2/tree/graphics-resizing-fixes

Confirmation this fixes VST2 on windows would also be welcome.

**Comment by AlexHarker** [comment]
Actually - it is AAX that is the priority.

**Comment by janhase88** [comment]
yes, it appeared when the mouse was released.
 i tested your fix as vst2/vst3 in bitwig and as vst2 in ableton on windows and i cant reproduce the issue anymore. no matter how fast i resize - it seems to work now

**Comment by AlexHarker** [comment]
Good - I just need to check AAX and some things on Mac and I'll get it pulled in as soon as I can.

**Comment by AlexHarker** [comment]
Fixed by 4ca76ca55d4c3c56d9e90f45a0c9c8e7ab4330f7
