### ISSUE TITLE
MidiEffects does not work on VST3?

### ISSUE THREAD

**Issue by slvmnd** [iPlug2/iPlug2#236]
Trying to create a midi effect (midi in, midi out, no audio processing).

On a mac, after downloading the VST3 SDK, I was able to compile a VST3 plugin from the IPlugInstrument example and load it into Ableton 10.1. However, when trying to do the same with the IPlugMidiEffect Ableton says "The VST3 plug-in could not be opened".

Are midi effects supported on VST3 with iPlug2? Or could this be a problem with Ableton?

**Comment by slvmnd** [comment]
Update: building a VST2 plugin using VST2 headers, the resulting vst can be loaded into Ableton! However, Ableton seems to recognise it as an audio effect, so that it can only be placed after a synth, not before it..

**Comment by olilarkin** [comment]
Hello, I believe this is due to Ableton's relatively new VST3 support - It doesn't seem to support plug-ins with no audio I/O.  by adding I/O I was able to make the plug-in work ( send MIDI to a synth) IPlugMidiEffect works in Cubase 10 and Reaper.
