### ISSUE TITLE
Win Vst2 PluginWindow doesnt resize correctly, if OnUIOpen is overriden

### ISSUE THREAD

**Issue by janhase88** [iPlug2/iPlug2#241]
When OnUIOpen is overriden it doesnt resize correctly on closing/reopening the PluginWindow 

tested with vst2 under Windows10 in Ableton 10.0.1, Reaper v5.965 and Bitwig 3 beta 5
*note that behaviour in Bitwig differs from Ableton and Reaper, when OnUIOpen is not implemented

 in IPlugEffect.h:
virtual void OnUIOpen() override;

In IPlugEffect.cpp :
void IPlugEffect::OnUIOpen() {
SendCurrentParamValuesFromDelegate();
}

![2019-06-12-20-40-50_4](https://user-images.githubusercontent.com/46456607/59379038-f8f43000-8d55-11e9-82ef-88729be1313e.gif)

**Comment by AlexHarker** [comment]
If you look at the signature for OmnUIOpen you should see this:

/** If you override this method you must call the parent! */
  void OnUIOpen() override;

So - I don't really consider this a bug - although we could add another virtual method for users and mark OnUIOpen as final to prevent developers from making this mistake.

@olilarkin - thoughts?

**Comment by janhase88** [comment]
okay nice. i looked at the signature and was not getting what is ment by "call the parent" .. its too vague for my level of understanding.. a more precise description would help here, but also giving devs another onuiopen method would be nice.

**Comment by olilarkin** [comment]
I think we have a lot of methods, already so I am going to close this
