### ISSUE TITLE
Not all plugin formats populate ITimeInfo correctly

### ISSUE THREAD

**Issue by AlexHarker** [iPlug2/iPlug2#247]
As it say on the tin

**Comment by olilarkin** [comment]
is this still an issue?

**Comment by AlexHarker** [comment]
Yes - I think VST3 doesn't do anything here and possibly not AXX, but if you search through you can maybe see which ones - if you want to take a look you might be better placed to fix this one - on AU(v3) it was being prepared but not pushed into the plug so it was an easy fix.

**Comment by hor-net** [comment]
Easy fix, I'developing a sequencer right now, I'll try to push a PR in the next days

**Comment by hor-net** [comment]
Just checked the latest master branch and it seems fixed indeed, both VST3 and AAX has SetTimeInfo call and are working, this can be probably closed

**Comment by AlexHarker** [comment]
Yes - not sure what I thought was missing, but it looks like it was an AUv2 only issue, which I fixed.
