### ISSUE TITLE
Fonts don't load correctly with IGraphicsCanvas

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#254]

**Comment by olilarkin** [comment]
I see times new roman, until i dirty the control

**Comment by AlexHarker** [comment]
Hmmm. I thought I'd fixed that, but maybe I didn't - it's to do with the way canvas lazily loads fonts. I'll check it. What are you testing with (plugin)?

**Comment by olilarkin** [comment]
IPlugEffect

**Comment by AlexHarker** [comment]
OK - lines 433-434 of IGraphicsCanvas.cpp were designed to fix this, but now don't seem to work. This could be a change in Chrome, or it could be that we are drawing differently somehow. Essentially, we stuff the font into the CSS but Chrome loads it lazily, so the idea is to make it load immediately *before* we need it, thus making it ready on the second call to draw.

I thought that we'd be OK if the first call to use the text was in a different call to the javascript loop, but either that is no longer the case (the font loading is done in the same loop as the first draw call) or that's no longer sufficient to ensure the font is loaded.

**Comment by AlexHarker** [comment]
Looks like CSS fonts are asynchronously loaded and we can't rely on when they'll be finished. This is probably a change in Chrome to when I tried to fix this before, but it is a significant challenge, as any drawing to layers with fonts also needs fixing if we wait. I'll keep thinking.
