### ISSUE TITLE
IGraphicsWeb binds dblclick and mousedown events

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#257]
ends up confusing icontrols with mousedowns received and dblclicks for the same events

**Comment by olilarkin** [comment]
https://github.com/iPlug2/iPlug2/tree/graphics-web_dblclick

**Comment by AlexHarker** [comment]
So - there are some important things to note here:

1 - double click on web means after the mouse up for the second click (not the same as on desktop)
2 - the only way to get a double click at the same point as on desktop is to emulate, which means system settings have no effect on double click length etc. (not ideal)
3 - other options are:
A - map a different kind of action to double clicking on web
B - accept that double clicks will also cause mousedown/up events before the double click, but prevent double clicks being sent to controls that treat double clicks like single clicks

None of this is ideal, but that's how browsers work - thoughts?

**Comment by AlexHarker** [comment]
The branch we have implements 2 - is there an issue with pulling it in?

**Comment by olilarkin** [comment]
closed by b3c76d7bf5e752873e2952a91c1d46b9b9d324d8
