### ISSUE TITLE
Faust example on Mac crashes host

### ISSUE THREAD

**Issue by dmsplugins** [iPlug2/iPlug2#271]
Yesterday, I built debug vst2 versions of the Faust example project on Mac and windows. The windows version works fine. The Mac version successfully builds but can't find/open stdfaust.lib. Using git, I see that this behavior first appeared with the merge that allows projects to be built outside the iPlug2 folder.

**Comment by olilarkin** [comment]
strange... on master it works for me, VST2 in Reaper. I have seen crashes with the IPlugFaustDSP plugin a lot in Live

**Comment by dmsplugins** [comment]
For me, if I build a debug version without debugging in Xcode, Reaper crashes while scanning plugins the first time after building the project. For vst3, VST3PluginTestHost crashes (for the same reason) when attempting to load the plugin. I don't know why it works for you but not me.
When building the project with Xcode set to start Reaper and debug,it stops in IPlugFaustGen.cpp at  ::dsp *FaustGen::Factory::CreateDSPInstance(int nVoices) with the following...

BEGIN IPLUG CHANNEL IO PARSER --------------------------------------------------
Channel I/O #1 - 2-2
               - input bus count: 1, output bus count 1
               - channel count on input bus 1: 2
               - channel count on output bus 1: 2
               - input channel count across all buses: 2, output channel count across all buses 2

1 I/O configs detected
Total # in chans: 2, Total # out chans: 2 

END IPLUG CHANNEL IO PARSER --------------------------------------------------
FaustGen: attempting to load /Users/david/SDKs/iPlug2/Projects/FaustExample/projects/../FaustExample.dsp
FaustGen-Faust1: Compile options: -double -I ../../../Dependencies/Build/mac/share/faust -I /Users/david/SDKs/iPlug2/Projects/FaustExample/projects/../ 
FaustGen-Faust1: Invalid Faust code or compile options : ERROR : unable to open file stdfaust.lib

I have found that if I modify common-mac.xcconfig by changing:
FAUST_DEFS = SWELL_COMPILED FORCE_WIN32_CURSES FAUST_EXE=\"$(BUILT_LIBS_PATH)/bin/faust\" DEFAULT_FAUST_LIBRARY_PATH=\"$(BUILT_LIBS_PATH)/share/faust\"
to
FAUST_DEFS = SWELL_COMPILED FORCE_WIN32_CURSES FAUST_EXE=\"/Users/david/SDKs/iPlug2/Dependencies/Build/mac/bin/faust\" DEFAULT_FAUST_LIBRARY_PATH=\"/Users/david/SDKs/iPlug2/Dependencies/Build/mac/share/faust\"
It works fine.
$(BUILT_LIBS_PATH) is not passed as an argument to Faust properly on my system.
MacOs Mojave - Version 10.14.5
Xcode and command line tools -Version 10.2.1 (10E1001)
Im new to using a Mac and there is much I don't know yet.
For example.. Why does libfaust.dylib get copied to the bundle; Is it not possible or practical to link to it from its location in the Dependencies folder?

**Comment by dmsplugins** [comment]
Backslashes in the above pasted FAUST_DEFS are missing. I didn't copy/paste it correctly. In my xcconfig file, they are there.

**Comment by olilarkin** [comment]
I believe this should be temporarily fixed with 381ec3b1f2ab57a5bae676b2855eb5d37b77f498, need to find a better way to specify the path to faust executable in /iPlug2/Dependencies/Build/mac/bin/faust
