### ISSUE TITLE
Canvas IPlugControls example is blank

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#288]
https://iplug2.github.io/CANVAS/IPlugControls/

Do not know why

**Comment by Pomax** [comment]
all the canvas examples seem to fail in FF citing:

> uncaught exception: abort("abort(\"both async and sync fetching of the wasm failed\"). Build with -s ASSERTIONS=1 for more info."). Build with -s ASSERTIONS=1 for more info.

The only possibly useful mention of how to fix that (which might or might not apply, of course) is https://plrang.com/blog/webassembly-both-async-and-sync-fetching-of-the-wasm-failed-issue/

**Comment by olilarkin** [comment]
Some of them work for me, e.g. https://iplug2.github.io/CANVAS/IGraphicsStressTest/, which platform/is it the latest firefox?

**Comment by Pomax** [comment]
Ah, you're right, I spoke too soon. The ones I tried didn't work so I blindly assumed the rest wouldn't either >_>

**Comment by Pomax** [comment]
Hmmm interesting thing: the first time I run https://iplug2.github.io/CANVAS/IGraphicsStressTest/ in firefox (win10, ff nightly), it works. But if I reload the page, it also throws that `uncaught exception: abort("abort(\"both async and sync fetching of the wasm failed\"). Build with -s ASSERTIONS=1 for more info."). Build with -s ASSERTIONS=1 for more info.` error.

**Comment by AlexHarker** [comment]
This issue is to do with loading the ForkAwesome and FontAudio fonts. The canvas fails if they are loaded even if they are not drawn. I will investigate further, but when removed everything (except those fonts) renders correctly)

**Comment by AlexHarker** [comment]
IGraphicsCanvas::AssetsLoaded() is failing here (FontExists() must fail when it shouldn't) and then the canvas never draws. If I make that return true then the fonts draw correctly. I'll look into it further.

**Comment by AlexHarker** [comment]
The issue looks to be that that the characters I'm using to measure to see if the font is loaded aren't defined in those fonts, so it appears like they never load, and hence the GUI never draws.

**Comment by Pomax** [comment]
As a former web-font-parser developer, I can strongly recommend using the canvas font loading API instead (https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/font has some example code for that).

**Comment by AlexHarker** [comment]
Thanks for this - I've now implemented this in a3fff63396d7e67b4f5f51c182b3d78bc0125a43 and this issue is resolved
