### ISSUE TITLE
mTimeInfo Adress is not changed by SetTimeInfo() 

### ISSUE THREAD

**Issue by janhase88** [iPlug2/iPlug2#292]
As i get it SetTimeInfo() is supposed to change the Adress of mTimeInfo (in IPlugProcessor.h) to the  Adress we pass with SetTimeInfo(myTimeInfo);

i think for this to work mTimeInfo needs to be declared as a Pointer:
https://stackoverflow.com/questions/2171041/how-to-change-address-of-variable/2171063#2171063

the other option would be we declare our "custom" ITimeInfo as Pointer and assign to it the Adress of mTimeInfo  and instead of SetTimeInfo()  we would have GetTimeInfo() in IPlugProcessor.h => ITimeInfo* GetTimeInfo() { return &mTimeInfo ; }

**Comment by AlexHarker** [comment]
I don't see an issue here. SetTimeInfo() is a method that should be called from the plug-in format class to set the time info field. It doesn't change an address - it changes values, but it is passed by reference.

If you are just writing a plugin you shouldn't be calling SetTimeInfo() at all. If you are writing a new plugin format or adapting a pre-existing one you might need to call it.

To get info about timing in a plugin you should be using GetSamplePos() / GetTempo() / GetSamplesPerBeat() / GetTimeSig().

If those don't give you what you need then access mTimeInfo directly, although you shouldn't write to it, only read (perhaps there is a case for a setter here, but it should get set each block, so this isn't really an issue.

So - it looks like you've misunderstood what it is designed to do (true it isn't documented) and I'm closing for now.

**Comment by janhase88** [comment]
yes, totally got it wrong, somewhat i had in memory i couldnt access mTimeInfo in  iplug1 ... anyway thx for clearing that up.
