### ISSUE TITLE
IWebsocketEditorDelegate copies memory unnecessarily

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#3]
https://github.com/olilarkin/wdl-ol-private/blob/iplugquake/IPlug/Extras/WebSocket/IWebsocketEditorDelegate.cpp#L62
https://github.com/olilarkin/wdl-ol-private/blob/iplugquake/IPlug/Extras/WebSocket/IWebsocketEditorDelegate.cpp#L76
https://github.com/olilarkin/wdl-ol-private/blob/iplugquake/IPlug/Extras/WebSocket/IWebsocketEditorDelegate.cpp#L89

etc

**Comment by AlexHarker** [comment]
I've looked at this several times and I don't see how the copy can be avoided. At some point you need to take data that comes into a method as non-contiguous (several params, one of which is a pointer to some data you want to send). You then need to send that through the web socket as a single contiguous block of data - how would you avoid the copy without having the data come into the original method contiguous.

The underlying call is mg_websocket_write() which needs a contiguous data chunk. 

Am I missing something?

**Comment by olilarkin** [comment]
yes. addressed in 91ad05e
