### ISSUE TITLE
macOS 10.13 does not work with default settings

### ISSUE THREAD

**Issue by kzantow** [iPlug2/iPlug2#302]
Unable to run any build with macOS 10.13. One stack trace is:

![image](https://user-images.githubusercontent.com/3009477/64500638-dac59f80-d272-11e9-9245-e8d58e5906a9.png)

Change to IGRAPHICS_GL2 or IGRAPHICS_GL3 don't work (in a VM, though, this is likely to be related):

![image](https://user-images.githubusercontent.com/3009477/64500924-1f9e0600-d274-11e9-92b4-b2b3db2ebb18.png)

The latest source seems switching to CAIRO or SKIA currently doesn't work at all:

![image](https://user-images.githubusercontent.com/3009477/64502149-4ad72400-d279-11e9-9bac-8e6b38a73a2c.png)

... will reopen this when I can get to even build again...

**Comment by olilarkin** [comment]
I would never expect to get nanovg or skia gpu working in a virtual machine.From your screenshot of Cairo it looks like you haven’t installed it in the correct location

**Comment by olilarkin** [comment]
You can see that although the error is about the font the nano VG context is null. We should probably add an assertion on that earlier on

**Comment by kzantow** [comment]
Yes, 3d acceleration is available in the VM and I've seen the GL contexts work.

For the missing `cairo/cairo.h`, I cloned fresh, `cd Dependencies/IGraphics`, `./download-igraphics-libs.sh` so if something isn't in the right spot, I'm not sure what I've done wrong.

Also note I closed this for now as the "font" issue isn't what's pictured here, I was just documenting  things as I went.
