### ISSUE TITLE
SKIA with IGRAPHICS_GL2/3 fails to create a valid context on macOS 10.14.6

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#307]
sure this worked previously

https://github.com/iPlug2/iPlug2/blob/master/IGraphics/Drawing/IGraphicsSkia.cpp#L322

**Comment by olilarkin** [comment]
strangley with address sanitizer turned on it works

**Comment by AlexHarker** [comment]
This may be the same as #309

**Comment by AlexHarker** [comment]
Was the same bug as above - also fixed by 9ecc7d224bb345c8cc80216183394226a990dae3
