### ISSUE TITLE
Skia with GL now crashing on Mac OS 10.12.6

### ISSUE THREAD

**Issue by AlexHarker** [iPlug2/iPlug2#309]
Just updated the dependency build and when I build an APP now I crash on:

line 325 of IGRAphihcsSkia.cpp     assert(mScreenSurface);

This was previously working fine with older builds.

**Comment by AlexHarker** [comment]
Looking deepper the backendRenderTarget is not valid so likely the same as the other issue.

**Comment by AlexHarker** [comment]
OK - so this is a weird one. I've tracked back and the code doesn't work with the current skia build even at points it worked in the past. However, if I put some padding before backendRenderTarget (e.g. int pad = 0;) it works. 

If I don't then once that's been constructed then fbinfo has been zero-ed out (that shouldn't happen it's being passed in by const reference.

I'm almost certain that this is some kind of issue to do with the skia build in relation to the build of the application - possibly we have different versions of header files in comparison to the build, or different compilation settings that still allow it to link but with issues. Anyway, I think this needs to be solved outside of the plug code by looking at these issues.

@olilarkin - any ideas?

**Comment by AlexHarker** [comment]
Ah - think I may have this. SK_METAL is only defined in our source if we are building for metal but it can change the definition of classes and structs which will have been build with SK_METAL in the skia build. (Also we don't define SK_GL, but possibly we should). I expect when we moved to a skia build supporting metal this broke.

We need to make sure we have the same options for build in our plugin.

**Comment by olilarkin** [comment]
Does it stop the crash for you? I made the same observation but still got problems

**Comment by AlexHarker** [comment]
See https://github.com/iPlug2/iPlug2/tree/graphics/skia-mac-gl

**Comment by AlexHarker** [comment]
Try that branch and let me know if that sorts your crash or not.

**Comment by AlexHarker** [comment]
OK - made a small change after reading the skia build system - I believe this is now correct and fixes my 10.12 issues.

**Comment by AlexHarker** [comment]
Fixed by 9ecc7d224bb345c8cc80216183394226a990dae3
