### ISSUE TITLE
Instruments example crash 

### ISSUE THREAD

**Issue by enricocupellini** [iPlug2/iPlug2#311]
- (the local repository is updated to origin/master), MacBook Pro 13', 2016, MacOSX 10.14.4, Xcode 10.2.
- open example project "IPlugInstrument" and modify the header IPlugInstrument_DSP at line 10 by adding enum cases (I found the issue is present for enum cases greater than 8).
This is my enum:
`enum EModulations
{
  kModGainSmoother = 0,
  kModSustainSmoother,
  kM2,
  kM3,
  kM4,
  kM5,
  kM6,
  kM7,
  kM8,
  kM9,
  kM10,
  kM11,
  kM12,
  kM13,
  kM14,
  kM15,
  kM16,
  kM17,
  kM18,
  kM19,
  kM20,
  kNumModulations,
};`

- run the target "macOS-APP".
- Crash at launch, inside "Smoothers.h", line 78  (com.apple.audio.IOThread.client (9): EXC_BAD_ACCESS (code=EXC_I386_GPFLT)).
- the crash at launch is almost regular on my machine (~ 3 times over 4 launches)

**Comment by olilarkin** [comment]
thanks @enricocupellini , i wasn't resizing the modulation scratch buffer correctly

**Comment by AlexHarker** [comment]
Oli got there just before me!
