### ISSUE TITLE
Knob value resets when continuing dragging after releasing mouse [VST3, Windows]

### ISSUE THREAD

**Issue by gmcgoldr** [iPlug2/iPlug2#312]
When I adjust a knob value and release the mouse button while still dragging, I consistently observed the knob setting itself to zero. For example, if a knob is at 10%, and I click and drag until it is at 50%, then release the click while still dragging, the knob will end up at the 0% state.

**Comment by AlexHarker** [comment]
Could you add details of your host/OS? This is reminiscent of #183, but that was (as far as I am aware) fixed quite some time ago. I presume you are on the latest version of master?

**Comment by gmcgoldr** [comment]
I am running this on Windows 10 1903, using Ableton. I cloned iPlug2 a few days ago from master, the last commit I have in there is from Sept. 24.

I checked #183 as per your comment and it looks the same as what I'm experiencing. Just for the sake of sanity I double checked that the fix 3add4564d92638c6a160bcab7910d6c009e85e13 is in my code base and it is.

I might be able to take some time to look into this, though I'm not sure how much progress I'll make. How do you normally debug these issues? I can't imagine running this with a debugger...

**Comment by AlexHarker** [comment]
OK - this should now be resolved (along with general VST3 behaviour) in 60de5cbfa465947cc9e2b954b908d7be99885fbc.

Thanks for the report.
