### ISSUE TITLE
Building AUv2 fails

### ISSUE THREAD

**Issue by Bertsz** [iPlug2/iPlug2#316]
This happened with the IPlugInstrument example out of the box. While there are no problems building the standalone app and the vst3 version, the AudioUnit 2 version seems to fail.

I did some digging around and this path in the build settings under other rez flags doesn't seem to exist on my computer:
`/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Versions/A/Headers`
The headers folder at the end doesn't, to be specific.

This the build error message:

`failed to find AUComponent/AUComponent.r
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AudioUnit.framework/Headers/AudioUnit.r:18: ### Rez - noErr (0) during open of "AUComponent.r".
Fatal Error!
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AudioUnit.framework/Headers/AudioUnit.r:18: ### Rez - Fatal Error, can't recover.
AUComponent.r: ### Rez - Since errors occurred, /Users/vm/Library/Developer/Xcode/DerivedData/IPlugInstrument-bnkwvakgncaduvfychxdutzjvqwa/Build/Intermediates.noindex/IPlugInstrument-macOS.build/Debug/AU.build/ResourceManagerResources/Objects/IPlugAU.rsrc's resource fork was not completely updated.
Command Rez failed with a nonzero exit code`

Ultimately changing the include path here
https://github.com/iPlug2/iPlug2/blob/3add4564d92638c6a160bcab7910d6c009e85e13/IPlug/AUv2/IPlugAU.r#L12

to `#include <AudioUnit.r>` fixed the build process for me.

**Comment by olilarkin** [comment]
Thanks, this is with xcode 11 right?

**Comment by Bertsz** [comment]
Oh I forgot to mention that.
Yes I'm on Mojave 10.14.6 and xcode 11

**Comment by olilarkin** [comment]
could you try pulling from master and see if efee29009ed9687fb36a48c41c4bc45d8bac6f30 fixes it, seems to still work on xcode 10 with path changed

**Comment by Bertsz** [comment]
Yes, this fixed it for me.
Thanks for looking into this

**Comment by olilarkin** [comment]
great
