### ISSUE TITLE
AAX windows memory corruption

### ISSUE THREAD

**Issue by TBProAudio** [iPlug2/iPlug2#324]
ProTools: 2019.6.0
IPLUG2 latest

Any ideas what I'm doing wrong?

**Comment by olilarkin** [comment]
probably nothing... may be a bug

**Comment by JackEagle12345678** [comment]
anyone else testing on PT on Win10?

**Comment by jonata** [comment]
I am also having problems with AAX on Windows 10. Maybe it is related. As of slack conversation:

> Hi there. I am trying to build AAX on windows, but it keeps crashing Pro Tools. I tried the IPlugEffect to make sure, and it is crashing, for example, when I drag the plugin to another insert (screenshot showing just before the crash dragging from A to B...). Pro Tools logs doesnt show anything. I am using the latest code from github, Pro Tools Dev. Any clue? Thanks!

![Untitled](https://user-images.githubusercontent.com/908065/66059655-c04db180-e512-11e9-9666-d2aaa1dc3edf.png)

Debugging mode, it crashes on 

`CreateGLContext, mHGLRC = wglCreateContext(dc);`

then

`"Access violation reading location 0xFFFFFFFFFFFFFFFFFFFF8"`

I updated AAXLibrary with vs2019 and rebuild it, but still crashing

Changed to IGRAPHICS_CAIRO, now break in TimerProc function 

AAX works just fine on macOS

**Comment by JackEagle12345678** [comment]
Just compiled with IGRAPHICS_LICE:
plug start works, removal crashes in _CrtIsValidHeapPointer
So it seems that something is wrong with the plug memory management, new and delete on different stacks...
Very curious :-(

**Comment by olilarkin** [comment]
yep... seems a few things are not right. I get crashes related to the timer and IPlugAAX::mParamIDS ptrl list. some kind of memory corruption happening

**Comment by jonata** [comment]
IGRAPHICS_LICE did not help :(

**Comment by TBProAudio** [comment]
OK, I fixed the issue:

IPlugAAX.cpp

insert after line 289 :
if (numSamples > GetBlockSize()) // TBPROAUDIO 03102019 if numSamples > block size adjust internal buffers and inform plug
  {
    SetBlockSize(numSamples);
    OnReset();
  }
