### ISSUE TITLE
AAX windows memory corruption2

### ISSUE THREAD

**Issue by TBProAudio** [iPlug2/iPlug2#329]
Oli,
i saw your change but in some cases this is not enough. For compatibility reason add.  OnReset(); is helpful to be called if nFrames != mblocksize. BTW this is true for most (just checking AU) formats (VST2/VST3/AAX).
So I still insist on something like this:

```
if (numSamples > GetBlockSize()) 
  {
    SetBlockSize(numSamples); 
    OnReset();
  }
```

Or we put a OnReset in SetBlockSize...
Or did I miss the point?

**Comment by olilarkin** [comment]
you are correct
