### ISSUE TITLE
Can IMidiQueue  be replaced with IPlugQueue?

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#33]

**Comment by madronalabs** [comment]
I love tidying. I'll give it a try.

**Comment by AlexHarker** [comment]
@madronalabs - have you taken a look at this at all?

I've just glanced at it but what I see is:

- IMIDIQueue doesn't appear to have any thread safety
- IPlugQueue is a fixed size queue, whereas IMIDIQueue can grow and shrink freely.
- IMIDIQueue uses a system of moving memory around that seems inefficient and unnecessary - it looks like it never loops and instead moves all the data around.

I pretty sure it can be done fairly easily with mostly gains, if we can live with the fixed size queue.

**Comment by madronalabs** [comment]
All seems reasonable. I added the Resize method, see my PR

**Comment by AlexHarker** [comment]
@madronalabs - probably Resize() should also clear, as it might resize downwards and that could invalidate the counters. Pulled it in, but it seems like that could be unsafe right now.

**Comment by AlexHarker** [comment]
I have what I think is a rough version working here:

https://github.com/iPlug2/iPlug2/tree/IMIDIQueue-removal

this is ready for testing, but I have a couple of things to go through with Oli, plus a need to fix the counter issue on Resize() mentioned above.

**Comment by olilarkin** [comment]
I am going to close this and keep IMidiQueue for now. I have too many things that depend on it. Will keep your branch elsewhere and may revisit it at some point
