### ISSUE TITLE
IControl "mGrayed"... should be replaced

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#333]
I would prefer to have mEnabled. Control should not necessarily be gray if disabled! 

mEnabled would be of course the opposite status of mGrayed... but having an mDisabled seems weird.

this would be a breaking change of course

**Comment by AlexHarker** [comment]
I don't see an issue with mDisabled. It would also change method calls, but changing names might be easier to get right.

I wouldn't object to mEnabled though, but be good to get the changes all in one go and get the break out of the way.

**Comment by AlexHarker** [comment]
I've put a proposal up on this branch as I think #332 and this should be done together and the changes of names I've done are coherent.

https://github.com/iPlug2/iPlug2/tree/graphics/icontrols-bitfield

Changes can be applied to master as required - two commits might be good for clarity

**Comment by olilarkin** [comment]
After some playing with the bitfield, i think it's too much of a breaking change. Sorry for the time you put into that. Here is a PR, with just the Gray -> Disabled stuff

https://github.com/iPlug2/iPlug2/pull/352

**Comment by AlexHarker** [comment]
No problem - as long as we are working though the issues/PR list ;-)

**Comment by olilarkin** [comment]
fixed in 17919adf3e886868f3c5cefb1f8dcf9511ede2e5
