### ISSUE TITLE
IPlugInstrument: unhandled exception pVoice-> was nullptr  - when buffersize > 1024 (vst3/vst2 Winx64 reaper) 

### ISSUE THREAD

**Issue by janhase88** [iPlug2/iPlug2#340]
hey,

i tried to test IPlugInstrument vst3 Winx64 in reaper. it breaks with an unhandled exception when playing a note in VoiceAllocator.cpp in 
Line 535: if(pVoice->GetBusy() => pVoice-> was nullptr.

Error doesnt occur in Bitwig.

**Comment by olilarkin** [comment]
I just tried it and have no such issue. Can you confirm with master tip?

**Comment by janhase88** [comment]
i just retested with newest master and error is still there. BUT i found that it only occurs, when the buffersize is > 1024 samples (next buffersize i tested was 1536, so i assume everything bigger than 1024)

**Comment by AlexHarker** [comment]
This is because mTimbreBuffer has a fixed size of 1024.

It's marked as "// would be allocated dynamically in a real example"

but this seems unsafe - @olilarkin what do you want to happen here?

**Comment by AlexHarker** [comment]
The calll that causes the buffer overrun is IPlugInstrument_DSP.h line 59:

mInputs[kVoiceControlTimbre].Write(mTimbreBuffer, startIdx, nFrames);
