### ISSUE TITLE
UI: Resizing with Lice crashes instantly on windows

### ISSUE THREAD

**Issue by gvampgh** [iPlug2/iPlug2#342]
As discussed at slack channel
![grafik](https://user-images.githubusercontent.com/48643530/66566403-2b2b6800-eb65-11e9-8eb4-70afa5303f85.png)

**Comment by AlexHarker** [comment]
Fixed by a5f4a138f18a54945fdbc95b12e7cc1aa984f413.

There is more work to do to make resizing look smooth, but this at least fixes the crash.
