### ISSUE TITLE
Attaching IGraphics iPlug1-style has problems

### ISSUE THREAD

**Issue by AlexHarker** [iPlug2/iPlug2#345]
The starting point for this is #344 

Unfortunately after I mocked up a fix for this which involves having the graphics always attach themselves (so AttachGraphics becomes private and IGraphics a friend of its delegate) I ran into another issue.,

In this case NanoVG cannot load fonts without a context, which on Mac we don't get till later - @olilarkin might know how to approach this, but I'm wondering if AttachGraphics is viable anymore?

**Comment by AlexHarker** [comment]
The fix works with Cairo so I will post on a branch for discussion.

**Comment by AlexHarker** [comment]
See https://github.com/iPlug2/iPlug2/tree/graphics/attachment

**Comment by olilarkin** [comment]
Transient graphics was introduced to fix the problems with nanovg.  

Here is an alternative approach

https://github.com/iPlug2/iPlug2/tree/graphics/attachment2

will have a think about what is best

**Comment by AlexHarker** [comment]
I don't mind if it fixes it, but it is worth noting that in this case SetDelegate gets called each and every time LayoutUI is called (calling OnInit / OnResize / OnRescale on the control), whereas previously (and on the branch I posted) I think there will only ever be one call per control attachment

**Comment by olilarkin** [comment]
I'm thinking perhaps we just remove "the old way"
