### ISSUE TITLE
Extended host detection

### ISSUE THREAD

**Issue by TBProAudio** [iPlug2/iPlug2#355]
I have now completed the review of the TBPROAUDIO IPLUG1 implementation compared to the current IPLUG2. And I want to share our findings/changes with the IPLUG2 project. Most of the findings are plug format related (PDC, side chain, multi channel, automation etc).

So here is my first request: extended host detection
1) kHostWaveLabElements seems to be superfluous as kHostWaveLab is already there
2) It would be nice to have at least following hosts in the list: 
  kHostReason,			
  kHostGoldWave5x,	
  kHostWaveform,		
  kHostAudacity,		
  kHostAcoustica,		
  kHostPluginDoctor,
  kHostiZotopeRX,		
  kHostSAVIHost,		
  kHostBlueCat

This extension impacts mainly IPlugConstants.h and IPlugUtilities.h. I could provid pre-patched files for easy merge.
This extension would help to support correct PDC handling and other nasty things (mainly VST2 related) in much more DAWs:-)

**Comment by AlexHarker** [comment]
If you have this can code can you fork and apply the changes on branch and then make a pull request please?

I will leave @olilarkin to answer about removing things, but I would suggest not doing this, and I suspect that kHostWaveLab and kHostWaveLabElements report as different hosts.

**Comment by TBProAudio** [comment]
Thanks I make a pull request
