### ISSUE TITLE
GetHostName

### ISSUE THREAD

**Issue by TBProAudio** [iPlug2/iPlug2#356]
This function was already in IPLUG1, for compatibility reason.
Addition to IPlugPluginBase.h:

```
/** Get the host name as string
   * @param str string into which to write the host name */
   void GetHostStr(WDL_String& str) const { char chostname[265]; GetHostNameStr(GetHost(), chostname); str.Append(chostname); } // TBPROAUDIO 30092019

```

**Comment by AlexHarker** [comment]
Thanks for looking at all of this. We are grateful for all the ideas, but could you submit this as a pull request and not an issue please? We can always modify the code for style/naming, but it is much harder for us to copy out of the web browser/find the right file etc.

**Comment by TBProAudio** [comment]
Thanks I make a pull request
