### ISSUE TITLE
Support custom preset manager

### ISSUE THREAD

**Issue by TBProAudio** [iPlug2/iPlug2#358]
It would be nice to remove some **const** attributes to implement custom preset management in the plugin.
Affected IplugBase.h/cpp

```
bool SerializeParams(IByteChunk& chunk);
virtual bool SerializeState(IByteChunk& chunk) { TRACE; return SerializeParams(chunk); }
bool SaveProgramAsFXP(const char* file);
```
and IPLUGAAX.h/cpp:
```
AAX_Result GetChunkSize(AAX_CTypeID chunkID, uint32_t* pChunkSize);
AAX_Result GetChunk(AAX_CTypeID chunkID, AAX_SPlugInChunk* pChunk);

```

**Comment by AlexHarker** [comment]
Thanks for looking at so many aspects of plug 2.

I'm afraid that in terms of const correctness these things should not change the state of your plug-in, so they were put there for a reason. If you need to call onto other methods it is highly likely that they also need to be const.

If you have things that are not considered true state (such as a mutex) then you can use the mutable keyword in the class declaration to allow you to modify them with const calls, but removing the const on these methods will promote bad practice in terms of programming, and not give protection where I believe it should be there.
