### ISSUE TITLE
VST2: setlatency

### ISSUE THREAD

**Issue by TBProAudio** [iPlug2/iPlug2#359]
Well, PDC is a pretty complex topic and and took us many years to find a suitable solution as each DAW reacts differently on setlatency.

Our finding here is as follows:
Some like setlatency in OnProgramChange: kHostStudioOne, kHostFL, kHostWaveform
Others in ProcessBlock: kHostProTools and kHostAbletonLive
Most of the others in OnIdle: Steinberg, Reaper, Logic just to name a few.

So the requested change affects IPlugVST2.cpp (as the other formats have a direct way to inform the host about latency change)

```
void IPlugVST2::SetLatency(int samples)
{
  mAEffect.initialDelay = samples;
  IPlugProcessor::SetLatency(samples);
  bool ret = mHostCallback(&mAEffect, audioMasterIOChanged, 0, 0, 0, 0.0f); // Notify host about latency changes 
}
```
To manage the PDC stuff in a smart way we implemented the class IExtPDCHandler:

```
#ifndef EXTPDCHANDLER_H
#define EXTPDCHANDLER_H

class IExtPDCHandler
{
public:

  enum IPlugState
  {
    kOnProgramChange = 0,
    kProcessBlock,
    kOnIdle
  };

  IExtPDCHandler(){}
  ~IExtPDCHandler() {}

  void InformHostAboutPluginDelayChange(Plugin* mPlug, int msamples, IPlugState _state)
  {
    switch (_state)
    {
      case kOnProgramChange:
      {
        if (mPlug->GetHost() == kHostStudioOne || mPlug->GetHost() == kHostFL || mPlug->GetHost() == kHostWaveform)   // StudioOne/FL Studio/Waveform need to set latency here otherwise nonfunction or crash
        {
          if (mPlug->GetLatency() != msamples) mPlug->SetLatency(msamples);
        }
      }
      break;
      case kProcessBlock:
      {
        if (mPlug->GetHost() == kHostProTools || mPlug->GetHost() == kHostAbletonLive)                              // Protools and Ableton here
        {
          if (mPlug->GetLatency() != msamples) mPlug->SetLatency(msamples);
        }
      }
      break;
      case kOnIdle:
      {
        if (mPlug->GetHost() == kHostProTools)                                                                      // exclude PT here for sa
        {
        }
        else                                                                                                        // all other here e.g. Reaper/Steinberg/Logic
        {
          if (mPlug->GetLatency() != msamples) mPlug->SetLatency(msamples);
        }
      }
      break;
      default:
      {
        assert(0);
      }
      break;
    }
  }
};
#endif
```
It is used in **ProcessBlock**: InformHostAboutPluginDelayChange(this, main_plugin_delay, kProcessBlock);
**OnIdle**: InformHostAboutPluginDelayChange(this, main_plugin_delay, kOnIdle);
and 
**OnParamChange**: InformHostAboutPluginDelayChange(this, main_plugin_delay, kOnProgramChange);

Please feel free to use the provided code as you like:-)

**Comment by AlexHarker** [comment]
As in the other threads, if you are making code suggestions it will be much faster for us to review if you work on a branch of a fork and then make a pull request.

I've left all these open for now, but we would be able to review and address much quicker if they were pull requests.

Thanks!

**Comment by TBProAudio** [comment]
Thanks I make a pull request
