### ISSUE TITLE
Review of Text in all APIs

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#36]
i have some code for this

**Comment by AlexHarker** [comment]
This is now basically supported, although no support for styles yet. At some point later we need to review all text support, but that's a separate issue. I'll close this once I can figure out styles

**Comment by AlexHarker** [comment]
I've broadened this, because actually various things aren't supported in various drawing APIs

**Comment by AlexHarker** [comment]
As part of this I need to look at the division of measuring/drawing and the fact that measuring is not const, but possibly should be.

**Comment by AlexHarker** [comment]
Need to consider #137 and #138 in this work.

**Comment by AlexHarker** [comment]
Font loading now basically done. Still to to:

Robust font loading in edge cases
Figure out how to get custom fonts to load with LICE/.SWELL (might just be an Inof.plist issue)
Positioning/Sizing of text in AGG and Canvas
Text appearance (kerning and hinting) in all Draw APIs
Look at the quality setting in Text

**Comment by AlexHarker** [comment]
Current TODO list:

Robust font loading in edge cases
Matching of native textedits
Look at the quality setting in IText
Details of text sizing and positioning across APIs
Details of appearance (quality/kerning/hinting) across APIs)

**Comment by AlexHarker** [comment]
Replaced by #508
