### ISSUE TITLE
PARAMS_MUTEX never calls ProcessBlock in Windows App / crashes

### ISSUE THREAD

**Issue by gvampgh** [iPlug2/iPlug2#372]
As the title says, when PARAMS_MUTEX is defined/activated in the config, ProcessBlock method is never called in windows standalone app (easy to see in IPlugEffect example). Also it would cause methods like SetChannelLabel to crash (channel number out of boundary). So, atm PARAMS_MUTEX is not reliable.

**Comment by gvampgh** [comment]
Ok, I found from the other thread that it has to be defined in the props file, done & works. I'm sure that this will be a common pitfall. Closed.

**Comment by AlexHarker** [comment]
Yes - something for the documentation, but unfortunately this is also a general programming issue (different/non-matching defines in different compilation units), so it can't be fixed by restructuring instead.
