### ISSUE TITLE
Implement Drop Shadow for all IGraphics Backends [was workast #TZBM]

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#38]
https://github.com/olilarkin/wdl-ol-private/blob/master/IGraphics/IGraphics.h#L461

**Comment by olilarkin** [comment]
metal on discrete GPUs fixed in d77d9a9e3f272ac0af6d564ccd49154f912c8717 yey

**Comment by AlexHarker** [comment]
Awesome!
