### ISSUE TITLE
Slack channel invite is dead.

### ISSUE THREAD

**Issue by wrightwriter** [iPlug2/iPlug2#380]

**Comment by olilarkin** [comment]
thanks, fixed

**Comment by olilarkin** [comment]
https://join.slack.com/t/iplug-users/shared_invite/enQtNDIyNjk0NDY2ODAwLWE4Zjc1MTk3NWQzMDRlY2YyOTllMWQyMDY2YjRjMjBmYTMwYzBiMTIwNDM0YWY0MmM5NTBmYWJmMjBkYzRkZDc
