### ISSUE TITLE
VST3 Wrapper expects higher channel count configuration to be the last one in PLUG_CHANNEL_IO 

### ISSUE THREAD

**Issue by hor-net** [iPlug2/iPlug2#381]
The VST3 wrapper always expect the highest count of channels to be the lat one in PLUG_CHANNEL_IO in config.h, for example if I write:

2-2 1-1

The plugin is always mono, this is because in line 46 of IPlugVST3_ProcessorBase.h the config index is always the last one:

`int configIdx = NIOConfigs() - 1;`

**Comment by AlexHarker** [comment]
This is also because of the lack of SetBusArrangements implementation at the moment, which @olilarkin is working on. As I understand it the number of buses for a VST3 should stay consistent, but the number of channels on each bus can change.

**Comment by olilarkin** [comment]
fixed in eb67bf0feef73da66252b8992cebd10110a0ea71
