### ISSUE TITLE
Standalone App: Crash with windows DirectSound 

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#387]
On Windows with the IPlugControls example:
* Choose a DirectSound output device
* Choose the Microsoft GS Wavetable Synthesizer as MIDI Output

Then, if you click "X" to close the application, it reliably crashes because:
WM_DESTROY
-> IPlugAPPHost::sInstance = nullptr
* sets IPlugAPPHost::sInstance := nullptr
* then calls ~IPlugAPPHost()
-> RtMidiOut::closePort()
-> MidiOutWinMM::closePort()
-> waits in into Windows land for something related to
   MicrosoftGSWavetableSynth

At this point, the following happens in audio land:
* Callback from DirectSound
-> RtApiDs::callbackEvent()
-> IPlugAppHost::AudioCallback(...)
-> accesses IPlugAppHost::sInstance, which is already nullptr
-> crash

**Comment by AlexHarker** [comment]
It looks like things are a bit funky here - the midi callback is getting the instance in a different way to the audio callback - a few possibilities here, including a bail on all these callbacks for when the app is exiting.

I'm pretty sure this wouldn't happen if the pointer was passed as user data to the audio (as with the midi callback. Might make sense to exit audio first, also, although it shouldn't matter.

**Comment by AlexHarker** [comment]
Please test this:

https://github.com/iPlug2/iPlug2/tree/APP/exiting

1 - the app currently waits 1 more vector than APP_N_VECTOR_WAIT  before processing
2 - do we want a fade out before we quit?

**Comment by olilarkin** [comment]
fixes the crash.

1) _this->mVecElapsed >= APP_N_VECTOR_WAIT ?
2) probably a good idea

**Comment by AlexHarker** [comment]
Fixed in 9a21da1ac737d8f46cdcadb567ff8329369a47e0
