### ISSUE TITLE
Build errors - .h not found 

### ISSUE THREAD

**Issue by fornof** [iPlug2/iPlug2#388]
/Users/rob/Projects/cpp/iPlug2/IPlug/VST2/IPlugVST2.h:20:10: 'aeffectx.h' file not found
/Users/rob/Projects/cpp/iPlug2/IPlug/VST2/IPlugVST2.cpp:12:10: In file included from /Users/rob/Projects/cpp/iPlug2/IPlug/VST2/IPlugVST2.cpp:12:
/Users/rob/Projects/cpp/wdl-ol/VST_SDK/audioeffect.h:37:10: 'pluginterfaces/vst2.x/aeffect.h' file not found

It is not in the VST_SDK source that is included with https://www.steinberg.net/en/company/developers.html

**Comment by asedev** [comment]
The "missing" files are part of the VST2 SDK which is not available any longer. Steinberg deprecated it last year and if you do not have a license from Steinberg you are not allowed to build any VST2 plugin.

**Comment by olilarkin** [comment]
what he said...
