### ISSUE TITLE
Standalone App in MacOs no audio playback

### ISSUE THREAD

**Issue by mrmatzek** [iPlug2/iPlug2#393]
When running the standalone APP version in MacOS i cannot get any audio out of the created plugin. However, VST/AU version and APP windows works fine.

**Comment by olilarkin** [comment]
If you require audio input on macOS 10.14.6+, tick the "Audio Input" checkbox in "Hardened Runtime" on the app "Sigining and Capabilities" page

**Comment by mrmatzek** [comment]
Oh damn! I missed that. 
Sorry, for creating an issue for that! I noticed later, that iPlug2 questions are also places in that WDL forum. Really sorry for that. You do a great job!!!
