### ISSUE TITLE
VST3 InformHostOfParameterDetailsChange() doesn't update the name exposed to the DAW

### ISSUE THREAD

**Issue by Bertsz** [iPlug2/iPlug2#395]
Changing the name of a IParam at runtime works as expected on AUv2 and VST2.
However on VST3 the name the DAWs I tested (FL Studio and Reaper on windows) display still remains unchanged.
Even after calling InformHostOfParameterDetailsChange() which only seems to be implemented in IPlugVST3 anyways.

**Comment by olilarkin** [comment]
Host issue, feel free to investigate

**Comment by Bertsz** [comment]
Are you sure this is a host issue?
This is also happening in the VST3PluginTestHost
