### ISSUE TITLE
FPS dropdown

### ISSUE THREAD

**Issue by dev-plvlml** [iPlug2/iPlug2#412]
Hi,
I've noticed a serious FPS dropdown from 30 down to 6 that has been introduced between commits [48946ff](https://github.com/iPlug2/iPlug2/commit/48946ff802bf3c3fb7289055ffed5480b5a431f6) and [1808690](https://github.com/iPlug2/iPlug2/commit/18086909c11a240ee99328d61c773ddba7eba89e). It happens even to the examples, while config.h always demands 60 FPS. The app and vsts also have begun to load much more slower.
Is is a known bug, or is there some workaround?

**Comment by olilarkin** [comment]
What operating system are you running?

The examples now have IGRAPHICS_VSYNC defined in the .props file which gets a solid 60 FPS on Windows 10 on most machines I have tried on.

This setting doesn't work with Windows 7.

If you remove IGRAPHICS_VSYNC, you should get back to the old behaviour

**Comment by dev-plvlml** [comment]
Thank you a lot, removing IGRAPHICS_VSYNC solved the problem!
I'm running Windows 7.
