### ISSUE TITLE
Dialog opening callback/event

### ISSUE THREAD

**Issue by amiramitai** [iPlug2/iPlug2#426]
[https://github.com/iPlug2/iPlug2/blob/master/IGraphics/IGraphicsEditorDelegate.h#L39](https://github.com/iPlug2/iPlug2/blob/master/IGraphics/IGraphicsEditorDelegate.h#L39)
void* OpenWindow(void* pHandle) final;
Is there any special reason for this final? I'm opening my own SDL window whenever my plugin is being presented and I need a way to detect the window opening.

**Comment by olilarkin** [comment]
If you're doing your own graphics, not using IGraphics, you don't need IGraphicsEditorDelegate. You can set the preprocessor macro NO_IGRAPHICS and override IEditorDelegate::OpenWindow

https://github.com/iPlug2/iPlug2/wiki/How-to-use-a-different-GUI-framework

**Comment by amiramitai** [comment]
I'd like to use the regular IGraphics for the parameters control as a separate console and have an extra window for all the other renderings.

**Comment by olilarkin** [comment]
That sounds like a wild idea. You could create your SDL window by overriding OnUIOpen()

https://github.com/iPlug2/iPlug2/blob/master/IGraphics/IGraphicsEditorDelegate.h#L51

**Comment by amiramitai** [comment]
Perfect! thanks!
