### ISSUE TITLE
IGRAPHICS_VSYNC doesn't work on Windows 7 - need to fallback to WM_TIMER

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#428]
- either we don't support win 7 or find a fix, or fallback to WM_TIMER

**Comment by asedev** [comment]
In general, I would skip Win 7 support. But it still might be a good idea to have VSYNC and WM_TIMER supported in parallel. WM_TIMER is the safe fallback, not depending on any third party graphics systems. It might be not so smooth but reliable and good enough for all not heavily animated UIs.

**Comment by Youlean** [comment]
Well, Windows 7 still has 25% of market share so it is hard to ignore it.

**Comment by baktery** [comment]
I don't have Win7 installed so I can't try it.

Why do you say that it doesn't work?

Checking the sources, IGRAPHICS_VSYNC has already a path when vsync functions are not available in the system. It will simulate it, will sleep about 16ms and will send the WM_VSYNC msg

https://github.com/iPlug2/iPlug2/blob/3b1acf88b98820a9e79d59de0eb7d19ffbf0649e/IGraphics/Platforms/IGraphicsWin.cpp#L2100

Am I right or is there anything else out there related with Win7? 



P.S. mVBlankShutdown should be set as volatile here:

https://github.com/iPlug2/iPlug2/blob/3b1acf88b98820a9e79d59de0eb7d19ffbf0649e/IGraphics/Platforms/IGraphicsWin.h#L150

**Comment by olilarkin** [comment]
trust me it doesn't work and the fallback that is there doesn't work :-)

we could/should fall back to the old WM_TIMER approach, which won't get a smooth 60FPS.

**Comment by sstillwell** [comment]
I seem to recall that Windows 7 has VSYNC...but ONLY if you're using an Aero theme...Classic themes disable it, and there is no other way to turn VSYNC on or off separately.

**Comment by flutomax** [comment]
GUI does not work in Windows 7.

**Comment by olilarkin** [comment]
Thank you for that

**Comment by olilarkin** [comment]
branch here to fallback

https://github.com/iPlug2/iPlug2/tree/graphics/vsyncwin7

**Comment by olilarkin** [comment]
I have merged this fallback to WM_TIMER branch.

@baktery could you elaborate on your comment about the volatile keyword?

**Comment by baktery** [comment]
It's just to force the compiler to do not optimize the read access of the mVBlankShutdown variable using a register instead of always reading it from memory, here for example:

https://github.com/iPlug2/iPlug2/blob/3b1acf88b98820a9e79d59de0eb7d19ffbf0649e/IGraphics/Platforms/IGraphicsWin.cpp#L2114

The variable is set to true from another thread.

At this time it seems like there is no any problem with it, the compiler optimization is not producing an infinite loop, but who knows in the future?

**Comment by olilarkin** [comment]
thanks. this issue is now "fixed" It would still be better if we could use vsync on windows7, chromium seems to manage it so it should be possible
