### ISSUE TITLE
Check ObjC memory management [was workast #TK8D]

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#43]
Should thoroughly check for leaks using various tools in Xcode, since there's been quite a lot of changes

**Comment by olilarkin** [comment]
IPlugPaths will currently be leaking... release pool needs to go back there

https://github.com/iPlug2/iPlug2/blob/master/IPlug/IPlugPaths.mm

**Comment by AlexHarker** [comment]
In theory it will only leak if there is no auto release pool running on the calling thread, but doing our own release pools will ensure we reduce memory usage and don't leak in any scenario.

It is substantially easier to use auto release pool blocks and I've started doing that work on the objective C men management branch. It's a bit less clear which graphics calls need these but putting these in should be the way forward.

https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmAutoreleasePools.html#//apple_ref/doc/uid/20000047

**Comment by olilarkin** [comment]
I think we should possibly use ARC for IGraphicsView.mm, as we are doing on iOS

https://github.com/iPlug2/iPlug2/tree/graphics/mac_arc

**Comment by AlexHarker** [comment]
Is this issue still relevant? - it's a bit vague and I'm not exactly sure what needs to be done for it. Testing relies on hitting all the right methods, which won't be hit necessarily by a basic IGraphics usage.
