### ISSUE TITLE
macOS-AUv2 example crashes on load in JUCE AudioPluginHost

### ISSUE THREAD

**Issue by madronalabs** [iPlug2/iPlug2#437]
**To Reproduce**
- build AUv2
- create an instance in AudioPluginHost

`assert(nConnected > -1);` on line 1658 of IPlugAU.cpp fails. On creation in AudioPluginHost no inputs or outputs are connected. `pOutBus->mNHostChannels` is -1.  

Mac OS 10.15.2, AudioPluginHost compiled from currrent JUCE release

**Comment by olilarkin** [comment]
Seems JUCE AU hosting doesn't call kAudioUnitProperty_StreamFormat to initialise the bus where other AU hosts do do this.

If I comment the test here ```//if (actualNumChannels != requestedNumChannels)```

https://github.com/juce-framework/JUCE/blob/master/modules/juce_audio_processors/format_types/juce_AudioUnitPluginFormat.mm#L754

Then the kAudioUnitProperty_StreamFormat gets set, and pOutBus->mNHostChannels is correct

**Comment by AlexHarker** [comment]
The JUCE AUWrapper also doesn't (or didn't use to) call reset on the plugins at the right time. The question in this case is do we consider (or know) that this is a bug.

Can we catch it elsewhere in a way that doesn't mess up performance?

**Comment by olilarkin** [comment]
So this causes a crash in Waveform and Luna DAWs.

can hack around it like this in IPlugAU.cpp

```      if (nConnected == -1) {
        pOutBus->mNHostChannels = pOutBufList->mNumberBuffers;
        nConnected = 2;
      }
//      assert(nConnected > -1);
```

**Comment by olilarkin** [comment]
Fixed.

I had replaced an IPMIN() macro in iPlug1 with std::min, but in the iPlug1 code it was comparing a signed int (-1) with an unsigned int (2). In any case MIN was wrong, it should have been finding the max of the two values. In iPlug1 it was returning 2 erroneously which turned out to be the right answer 

#define IPMIN(x,y) ((x)<(y)?(x):(y))
