### ISSUE TITLE
Add GetHSL method for IColor

### ISSUE THREAD

**Issue by hor-net** [iPlug2/iPlug2#441]
The IColor struct already provides a GetFromHSLA method to create a color from Hue, Saturation and Luminance, but if you want to create a new IColor based on and existing IColor HSL properties you cannot do it.

I think adding a method to get current IColor HSL can be useful in this regard.

**Comment by olilarkin** [comment]
7a6222b8293e187516ec792e8a8df4ffdfe268b8
