### ISSUE TITLE
IParam::GetDisplayForHost and IParam::Int return two different values for integer parameters

### ISSUE THREAD

**Issue by hor-net** [iPlug2/iPlug2#443]
**Describe the bug**
IParam::GetDisplayForHost has a call to round for integer parameters, while IParam::Int does not so a value like 1.8 is returned as 1 and displayed as 2

**To Reproduce**
Create an int parameter, assign it to a draggable control that also display its value, you can easily see the issue

**Expected behaviour**
I expect both IParam::Int and IParam::GetDisplayForHost to return the same values when used with integer parameters

**IMPORTANT DETAILS**
* What plug-in format does it relate to - VST2, VST3, AUv2, AUv3, AAX, APP or ALL? ALL
* What platform does it relate to - Windows/macOS/iOS/Linux or ALL? ALL
* What IGRAPHICS_BACKEND does it relate to, IGRAPHICS_NANOVG, IGRAPHICS_SKIA or ALL? ALL

**Additional context**

**Comment by AlexHarker** [comment]
An actual integer parameter should not be able to have a value of 1.8 at all.
I can see from the code how this would occur with InitDouble() but not InitInt(), but I may be missing something from just reading the source.

Please could you provide example code for the plug-in constructor/graphics creation, so I can understand the issue better?

**Comment by AlexHarker** [comment]
I've tried but I cannot reproduce when I change kGain in iPlugEffect to integer and I set an assert to check that the values are always the same - please provide code or more detailed instructions for this issue.

**Comment by hor-net** [comment]
Hi Alex, you are right indeed, the params uses InitDouble. It was code ported from IPlug1 where InitInt was just a call to InitDouble with a step set to 1, I had a look to the IParam code and and noticed that now there is a "stepped" flag that completely changes the behaviour of the "Set" method. This seems to make it coherent with the display. Sorry again for wasting your time.

**Comment by AlexHarker** [comment]
No problem - I'll close if you're happy? Indeed using the kFlagStepped is the way if you want this kind of behaviour, otherwise you'll get the closest integer to display.
