### ISSUE TITLE
OnMouseDrag() does not update mMouseIsOver flag 

### ISSUE THREAD

**Issue by pressplay123** [iPlug2/iPlug2#446]
**Describe the bug**
Happens with controls inheriting from IKnobControlBase or other IControl base classes if the child class depends on the parent functions. When dragging the mouse the mMouseIsOver flag is not updated which can result in a wrong drawing.

**To Reproduce**
Drag control + mouse up + do not move cursor. When the cursor is moved again OnMouseOut() will reset the flag and the control will draw correctly again. You can observer this behaviour in IPlugControls example.

**Expected behaviour**
Don't have to move cursor, the state is already updated before.

**Comment by pressplay123** [comment]
The following solves the issue from within the derived class, but it should be the responsibility of the base class in my opinion (or perhaps IGraphics as the caller?):
```
void OnMouseDrag(float x, float y, float dX, float dY, const IMouseMod& mod) override
{
    IKnobControlBase::OnMouseDrag(x, y, dX, dY, mod);
    if (!mRECT.Contains(x, y))
    {
        mMouseIsOver = false;
    }
}
```

**Comment by AlexHarker** [comment]
I'm not sure what the correct behaviour is. Let's take a case where your mouser reveals a numeric value - then you drag on the control - arguably then the drawing should not change just because you have left the control area.

I can see the issue, because the mouse is technically no longer over the control, but I'm not sure that the default behaviour should respect that when dragging. Of course, you can override in custom classes for different behaviour.

@olilarkin - any thoughts on this?

**Comment by pressplay123** [comment]
An alternative solution would be to update mMouseIsOver in OnMouseUp. This was my original idea and it would satisfy both my specific use case and your example. But in a strict technical sense this would still be wrong because the update would happen too late.

If there was a mMouseDragged member variable you wouldn't have to rely solely on mMouseIsOver in use cases like in your example. But that is another story...

**Comment by AlexHarker** [comment]
Oh - sorry - I misread the above. What you are describing is a bug. When cursor hiding is on it doesn't apply as the cursor is returned to the click point whilst/after dragging, but this should be fixed a different way in my opinion to your first suggestion.

I agree that the correct fix is to update in relation to mouse up, but the correct place is probably in IGraphics::OnMouseUp() where if a control is captured it should be checked for mouseOver. This prevents controls from being responsible for this kind of thing, which they shouldn't need to be.

**Comment by AlexHarker** [comment]
Worth knowing that this is an IPlug 1 bug, and there's a vague chance that a developer might feel that if someone has been dragging on their control, and they've released the mouse if they stop perhaps the control should stay in the mouse over state until they move and start doing something else. Be good to get Oli's thoughts before we change anything.

**Comment by pressplay123** [comment]
You can see it in the IPlugControls example when dragging a switch (which is pointless of course). The result is just a slightly different shade of gray and therefore the effect is barely noticeable. But ok, I'm curious about the outcome of this. 👍

**Comment by olilarkin** [comment]
IIRC IControl::mMouseIsOver is something i added because i was tired of having to implement OnMouseOver()/OnMouseOut() every time just to draw something different when mouse was over. If you think it's better to let developers add that themselves, we could get rid of it

**Comment by pressplay123** [comment]
mMouseIsOver is awesome, it just needs to updated when the mouse is released.

**Comment by AlexHarker** [comment]
The issue here is:

1 - Mouse Over a Control (On MouseOver() is called)
2 - Drag the Control ending up outside the controls (OnMouseDrag() is called OnMouseOut() is not called)
3 - Release the Mouse (OnMouseUP() is called OnMouseOut() is still not called)
4 - Move the mouse (only now is MouseOut() called)

So - arguably OnMouseOut should be called at step 2 or 3 (I think 3 is the best place) but it isn't. Do you agree?

**Comment by asedev** [comment]
From my perspective, the only correct default behavior of OnMouseOver and OnMouseOut would be to work in any case. Whether the control is dragged or not.
If a developer does not want this behavior one can write a custom control.

**Comment by janhase88** [comment]
I think mMouseIsOver is super useful for the reason you stated Oli. I would also appreciate something like mX and mY, because if you want to get the mouseover xy in  Draw you still would need to implement onMouseover and add your own xy variables.

**Comment by AlexHarker** [comment]
@asedev - The issue with calling OnMouseOut() when dragging is that often the throw of the control for controlling it is larger than the area onscreen, but conceptually you are still interacting with it, so I disagree with this as default behaviour. There are also complexities when dealing iwht hidden cursors (which still move a bit) and touch interactions. It's a little bit different if you have a slider that moves exactly with the cursor, but generally mouse overs going to be used to indicate (possible) interaction with the control, which in this case is still going on, so I think that default behaviour is going to be wrong more than it's going to be right, despite the naming.

On the other hand, when you are dragging you have the position, so you can always customise to know that you are out of bounds if that is important to you.

**Comment by pressplay123** [comment]
I can make the issue more complicated by adding that if you drag one control and stop with the mouse cursor above another control the second control should be immediately set as "mouse is over". But I must admit that this is not as important as the original issue and I guess it would be more difficult to implement, too.

**Comment by AlexHarker** [comment]
That's a good point - and no I think that should work correctly, and probably isn't that hard.

**Comment by olilarkin** [comment]
fixed on master, thanks alex
