### ISSUE TITLE
VST2: missing DAW latency reporting aka broken PDC

### ISSUE THREAD

**Issue by TBProAudio** [iPlug2/iPlug2#447]
**Description:**
If the plugin generates an internal latency (e.g. a Convo engine), it must report this to the VST2 host, otherwise the tracks will not be synchronized with the plugin. IPlug2 / VST2 is currently not reporting any latency changes to DAW via mHostCallback.

**To Reproduce:**
Add SetLatency to e.g. ProcessBlock, DAW does not recognize new latency, no PDC.

**Expected behaviour:**
VST2 plugin should report latency to VST2 host in order to enable proper PDC.

Pull request is under preparation

**Comment by olilarkin** [comment]
fixed by bd5887f
