### ISSUE TITLE
Text size for text entry doesn't resize..

### ISSUE THREAD

**Issue by dmsplugins** [iPlug2/iPlug2#451]
...At least not under all conditions. One of the first things I noticed when building the IPlugControls example project was how nice the ICaptionControl's text and text entry looks - even when it is resized.
 I have two controls that I am working on that accept text entry in a plugin (mostly bitmap gui) where pGraphics->AttachCornerResizer(EUIResizerMode::Scale) is called in the constructor. I am building on Mac (Xcode 10.3) from a branch in my fork called "presetwork" that is current with the master branch of Iplug2 as of a week ago other than a few changes I made and sent in a pull request for. One is a parameter display similar to ICaptionControl and the other is a preset menu.
 At first, I tried PromptUserInput() from both Control and IGraphics, then CreateTextEntry(); none of which worked properly when resized. After reading a little, I see that mText is used for text properties in text entry and apparently doesn't rescale along with the display text even though mText is used for it as well. I tried rescaling mText.size in my class, but that didn't work out too well. I finally did something just to see if it would work .... and it does, but is less than ideal because I'm just copying from PromptUserInput() and then calling it.
 In both my parameter display and preset menu, I create a separate IText object called mTextEntryProps, then in the parameter display....

`void OnResize() override
  {
    float scale = GetUI()->GetDrawScale();
    mTextEntryProps.mSize = mText.mSize * scale;
  }
  
  void OnMouseDown(float x, float y, const IMouseMod& mod) override
  {
    const IParam* pParam = GetParam();
    IParam::EParamType type = pParam->Type();
    
    if ( type == IParam::kTypeEnum || type == IParam::kTypeBool)
    {
      GetUI()->PromptUserInput(*this, mValueRECT);
    }
    else
    {
      WDL_String currentText;
      pParam->GetDisplayForHost(currentText, false);
      SetValue(GetParam()->Value());
      GetUI()->CreateTextEntry(*this, mTextEntryProps, mValueRECT, currentText.Get());
    }
  }`

In the preset menu, I added...

`void OnResize() override
  {
    float scale = GetUI()->GetDrawScale();
    mTextEntryProps.mSize = mText.mSize * scale;
  }
  
  void OnMouseDown(float x, float y, const IMouseMod& mod) override
  {
    if (mod.R)
    {
      const char* pname = dynamic_cast<IPluginBase*>(GetDelegate())->GetPresetName(mCurrPresetIdx);
      GetUI()->CreateTextEntry(*this, mTextEntryProps, mRECT, pname, kNoValIdx);
    }
    else
    {
      OpenMenu();
    }
    
    SetDirty(false);
  }`

It would probably be a lot simpler and better to modify PromptUserInput() and I could do it and send it in a PR, but I'm not sure if it would have a negative impact on anything else in IPlug2. Could you please have a look at this and see what you think?

**Comment by AlexHarker** [comment]
Thanks for this. You are right that this shouldn't be solved in controls, but should be in IGraphics or possibly the platform descendants..

What platforms are you testing on?

**Comment by dmsplugins** [comment]
So far just on Mac... 64bit vst2, vst3, AUv2, and app.
Here is something that I am trying on a local branch at the moment....

`void IGraphics::CreateTextEntry(IControl& control, const IText& text, const IRECT& bounds, const char* str, int valIdx)
{
  mInTextEntry = &control;
  mTextEntryValIdx = valIdx;
  
  IText textEntryProps = text;
  float scale = GetDrawScale();
  textEntryProps.mSize = text.mSize * scale;
    
  int paramIdx = valIdx > kNoValIdx  ? control.GetParamIdx(valIdx) : kNoParameter;

  /*if (mTextEntryControl)
    mTextEntryControl->CreateTextEntry(paramIdx, text, bounds, control.GetTextEntryLength(), str);
  else
    CreatePlatformTextEntry(paramIdx, text, bounds, control.GetTextEntryLength(), str);*/
  
  if (mTextEntryControl)
    mTextEntryControl->CreateTextEntry(paramIdx, textEntryProps, bounds, control.GetTextEntryLength(), str);
  else
    CreatePlatformTextEntry(paramIdx, textEntryProps, bounds, control.GetTextEntryLength(), str);
}`

It seems to work

**Comment by AlexHarker** [comment]
Thanks for continuing to look at this - I don't think that's the right fix yet, because IPlugControls was scaling correctly as it adds a custom text entry control (rather than the platform one), so probably this would cause that to fail.

So far this is where I'm at (if you could confirm that would be good):

It looks like the Mac platform text entry doesn't scale the text properly.
It looks like the Mac platform text entry *does* scale the bounds off the dit box correctly
I haven't yet tested on windows or web
Because the custom text control is subject to scaling through IGraphics it looks correct at all times.

**Comment by AlexHarker** [comment]
OK - if you check out this branch I think you'l see the correct thing (isn) for Mac text entries.

It has better vertical positioning and accounts for draw scale, but windows/linux/web need looking at.

**Comment by AlexHarker** [comment]
That branch is now merged into master, so you can also test there now. I think there is still work to do on win/web.

**Comment by dmsplugins** [comment]
Ok..... I'll try it out on my Mac and PC and let you know how it works.

**Comment by dmsplugins** [comment]
Works Great on Mac (vst2, vst3, AUv2, and app)!!
I'll try it out on Windows and let you know.

**Comment by dmsplugins** [comment]
I just built a vst2, vst3, and app on Windows10. The text entry text scales correctly.
The display text (using NANOVG) and the text entry text renders nicer on the Mac though. It's a bit grainy on my Windows machine (HP laptop). 
 I am attaching a copy of the project I was testing with. It's just a GUI mock-up of another plugin I'm working on. The parameters only affect volume. I am using it on on my "presetwork" branch (Pull Request #438) to convert some controls from IPlug1 to IPlug2 and to try to improve and make easier, the creation of presets. I would like to submit several of the controls in TestCntrls.h in a future pull request.

[ControlsTest.zip](https://github.com/iPlug2/iPlug2/files/4173757/ControlsTest.zip)

**Comment by dmsplugins** [comment]
By the way Thanks!!

**Comment by AlexHarker** [comment]
I'm closing this because the scaling issue is fixed on win/Mac and has not beeb completed platform native for web yet (but you can use ITextEntryControl which I've also fixed up)
