### ISSUE TITLE
IVSlider ignores roundess parameter in IVStyle object

### ISSUE THREAD

**Issue by hor-net** [iPlug2/iPlug2#465]
**Describe the bug**
IVSlider ignores the roundness parameter of IVStyle

**To Reproduce**
Create an IVSlider control and use a style object with roundness specified, the track of the slider is still drawn as a rectangle

**Expected behaviour**
I expect the slider's track to have rounded corners

**IMPORTANT DETAILS**
* What plug-in format does it relate to: ALL
* What platform does it relate to: ALL
* What IGRAPHICS_BACKEND does it relate to: ALL

**Comment by olilarkin** [comment]
added in ee9b85cfac495eb9bde4447ab9afa9bd6fbbb322
