### ISSUE TITLE
Add alignment for IRECTs

### ISSUE THREAD

**Issue by hor-net** [iPlug2/iPlug2#468]
It would be very useful to have a way to align an IRECT to another, horizontally and vertically. 

Example: 

I want two IRECTs next to each other to be vertically aligned in their middle, i could call a method on the IRECT to align passing the other one as reference and get back an IRECT whose coordinates are changed so that now it's middle aligned with the other one.
The same goes for bottom, top, center, left and right align.

**Comment by olilarkin** [comment]
added in 32a0e5279bf9986eeddde9c1d6b0393823e8ad86
