### ISSUE TITLE
generating plugin parameters from Faust code

### ISSUE THREAD

**Issue by ahihi** [iPlug2/iPlug2#472]
hi,

just getting started with iPlug2 and working from the iPlugFaustDSP example... i was wondering if it's possible to automatically generate the parameters for my plugin based on the Faust code, like e.g. `faust2juce` does?

i am happy to have a shot at implementing this myself, but i figured i'd ask first in case it's been done already :)

**Comment by olilarkin** [comment]
hello, iirc, as long as you have defined enough params the method IPlugFaust::CreateIPlugParameters() should set them up correctly

**Comment by ahihi** [comment]
what's the appropriate place to call this method? i tried putting it in the constructor of the Plugin-extending class but my VST3 fails to load:

![Screenshot 2020-03-15 at 03 11 08](https://user-images.githubusercontent.com/738615/76693271-fa4ae400-666a-11ea-9d92-045c07bc7805.png)

**Comment by olilarkin** [comment]
you can do something like this:

```MyTambura::MyTambura(const InstanceInfo& info)
: Plugin(info, MakeConfig(kNumParams, kNumPrograms))
{
  TRACE;
//  GetParam(kGain)->InitDouble("Gain", 100., 0., 100.0, 0.01, "%");
  
  mDSP.SetMaxChannelCount(0, 2);
  mDSP.Init();
  FaustGen::CompileCPP();
  mDSP.SetAutoRecompile(true);
  mDSP.CreateIPlugParameters(this, 0, kNumParams);```

kNumParams is set in advance to >= the number of params in your faust .dsp. If not it will probably crash

**Comment by olilarkin** [comment]
If you change the number of parameters in your faust .dsp at runtime, hosts wont update their parameter list. need to do some work on this, since i think i could at least get it working in reaper, maybe in some vst3 hosts where functionality for changing parameter count etc exists

**Comment by olilarkin** [comment]
closing this issue since its more suitable for discussion on slack or forum
