### ISSUE TITLE
OnDragResize should always be called from GUI thread

### ISSUE THREAD

**Issue by Youlean** [iPlug2/iPlug2#475]
I had some issues in Pro Tools if I was resizing the GUI on mouse event call since it will block the audio thread. Not sure if this is the problem with iPlug2 but, it might be wise to mark GUI for resizing and then to resize on the next GUI call (in next IsDirty() call for example). That's how I am handling the resizing in my fork.

**Comment by olilarkin** [comment]
unless you do something very wrong, i don't see why OnDragResize would be called from the audio thread.
