### ISSUE TITLE
VST3 Key Down/Up not working

### ISSUE THREAD

**Issue by baktery** [iPlug2/iPlug2#477]
**Describe the bug**
onkeydown/up is not working on VST3 plugins.

**To Reproduce**
Register a keyboard handler function with IGraphics::SetKeyHandlerFunc(). It works fine as standalone app but it seems like it's not implemented for VST3.

Tested on Windows with NanoVG with master branch sources from March 21.

**Comment by olilarkin** [comment]
it probably depends on the host which might filter key events first. In some cases you have to explicitly allow keyboard events to go to the plugin ui. what hosts are you testing in?

**Comment by baktery** [comment]
I'm using Live 10. Other plugins are receiving key events.

VST3 SDK's CPluginView::onKeyDown() is called by Live but IPlug2 is not reacting to it because the function is not overloaded by IPlug2VST3_View.

**Comment by olilarkin** [comment]
just pushed a fix, please try it and let me know

**Comment by olilarkin** [comment]
https://github.com/iPlug2/iPlug2/commit/f402e88688f7e071e66cefde1d77dff238854122

**Comment by baktery** [comment]
Ok. I tried it. Two things about it:

1) I'm not getting the correct iplug VK code. Pressing cursor down key kVK_CLEAR is get instead of kVK_DOWN. It seems like keyMsg has to be also translated.

When I press cursor down received Steinberg::char16 key is 0, it seems ok (not been a text key). But Steinberg::int16 keyMsg is 14 and should be converted to 40.

2) I had to overload the OnKeyDown/Up function in my main plugin class:

```
bool MyPlugin::OnKeyDown(const IKeyPress& key)
{
    if (GetUI())
    {
        GetUI()->OnKeyDown(0,0,key);
    }
    return true;
}

bool MyPlugin::OnKeyUp(const IKeyPress& key)
{
    if (GetUI())
    {
        GetUI()->OnKeyUp(0,0,key);
    }
    return true;
}
```

I don't know a lot about IPlug2 architecture but maybe it would be a good idea to include this function definitions in the parent IPlugVST3 implementation.

**Comment by baktery** [comment]
Note that the previous functions are not 100% correct, it just a fast test. Return value of OnKeyUp/Down should be returned instead of the hardcoded true.

**Comment by olilarkin** [comment]
branch to try... 

https://github.com/iPlug2/iPlug2/tree/VST3/Keyhandling

**Comment by olilarkin** [comment]
hmm key codes still not right on windows

**Comment by olilarkin** [comment]
think it should work now

**Comment by baktery** [comment]
Well done! Now it works fine.

**Comment by olilarkin** [comment]
merged on master
