### ISSUE TITLE
IEditableTextControl text dissapears after pressing ESC key

### ISSUE THREAD

**Issue by baktery** [iPlug2/iPlug2#480]
**Describe the bug**
When an IEditableTextControl edition is cancelled with the escape key the previously existing text disappears and when you edit it again the old "disappeared" text appears again.

**To Reproduce**
1. Click with the left mouse button over a IEditableTextControl, write some text (for example "hello") and press enter to confirm it.
2. Click again with the left mouse button over the same IEditableTextControl, write another text (for example "world") and after it press the ESC key
3. Text disappears instead of showing again the first introduced text ("hello" in the example)

Also, after it, if you click again over the control to edit it again you will see the first text ("hello"), It seems like the original introduced text is properly stored but not redrawn in the 3rd step.

**Expected behaviour**
When edit text is canceled old text should appear again.

Reproduced on Windows standalone app using NanoVG. Didn't try other platforms.

**Comment by baktery** [comment]
Note that the issue does not happen when using a ICaptionControl control.

**Comment by baktery** [comment]
Issue also happens on Win VST3.

**Comment by olilarkin** [comment]
fixed in a797b7900153177ef91749d260ca596c219cd5ad
