### ISSUE TITLE
Error building FaustDSP example on MacOS

### ISSUE THREAD

**Issue by iovaris** [iPlug2/iPlug2#483]
**Git Hash**: 944965814bc1f5fd2b3878cb180b1143d3249f72
**OS:** MacOS 10.15.4
**Xcode:** 11.4 (11E146)
**Error:**
```
In file included from FaustCode.hpp:13:
/../../Plug2/IPlug/Extras/Faust/IPlugFaust.h:20:10: fatal error: 'faust/gui/UI.h' file not found
#include "faust/gui/UI.h"
         ^~~~~~~~~~~~~~~~
1 error generated.
```

**Steps to reproduce:**
```
git clone https://github.com/iPlug2
cd iPlug2/Examples
python duplicate.py IPlugFaustDSP MyFirstPlugin Test
cd MyFirstPlugin
xcodebuild -project projects/MyFirstPlugin-macOS.xcodeproj -target AU -configuration Release
```

Just an issue with the Faust example, IPlugEffect built correctly with these same steps.

**Comment by olilarkin** [comment]
please see the readme for that example,

at the moment it is necessary to install faust to your system, and that is why you have that error

https://github.com/iPlug2/iPlug2/blob/master/Examples/IPlugFaustDSP/README.md
