### ISSUE TITLE
Keyboard input not receiving non-ASCII characters (win/web)

### ISSUE THREAD

**Issue by baktery** [iPlug2/iPlug2#484]
**Describe the bug**
When a IEditableTextControl is been edited (writing text with the keyboard) non-basic-ASCII characters are supported but when you confirm the text with the enter key they string is cropped to the first non-basic-ASCII character. Also, after it, if you edit it again to modify the text the first introduced string with all the non-basic-ASCII characters appears again.

**To Reproduce**
Edit a IEditableTextControl and write non-basic-ASCII characters. For example an extended ASCII character like ç or a non-ASCII character like €.

**Expected behaviour**
Different scenarios would be ok:
1. Non supported character are filtered when typing them
2. Non supported characters filtered and removed permanently from the string when text edit finished.
3. Complete support non-basic-ASCII characters: no characters are filtered in this case and you can see the extended characters also in regular text controls (full utf8 support)
 
Reproduced on Windows as standalone app and VST3 using NanoVG.

**Comment by olilarkin** [comment]
loving the detailed issue reports but really like PRs the best :-)

**Comment by olilarkin** [comment]
There are a couple of issues here.

The most significant is that NANOVG, CAIRO, AGG and SKIA backends are not drawing non-ascii characters. with LICE the characters get drawn.

Platform Text entries and ITextEntryControl (the IGraphics text entry "special control") already filter characters when the text entry prompt is created linked to a parameter, see e.g. ICaptionControl. It would be an improvement if a custom filter could be set for doing a generic text entry, but that processing can also be done on text entry completion (e.g. 2 above).

**Comment by olilarkin** [comment]
seems to only be an issue on windows

**Comment by olilarkin** [comment]
nope, web too (nanovg and canvas)

**Comment by baktery** [comment]
I think I found the problem on Windows. At least it's working here...

I changed the CreateWindow and SendMessage functions (to create and to get text from the edit control) to the Unicode versions and I convert between unicode<->utf8 before/after calling them.

**Comment by olilarkin** [comment]
Awesome can you make a pr?

**Comment by baktery** [comment]
yep, will do it

**Comment by baktery** [comment]
PR sent!

**Comment by olilarkin** [comment]
So this is actually multiple issues. 

c5c009db5ed6d504d9aa5a934799d1eb4a4d4121 fixes Win32 platform text entry. 

We are left with problems when using the ITextEntryControl, or getting raw keyboard input (see IKeyboardTestControl where we are not getting non-ascii characters.

**Comment by olilarkin** [comment]
fixed in 57cc46b435c57395679f4abb9f1ab4c1de897fd7
