### ISSUE TITLE
IPopupMenu::Item checked flag not working with submenus

### ISSUE THREAD

**Issue by baktery** [iPlug2/iPlug2#485]
**Describe the bug**
When setting as checked a IPopupMenu::Item that contains a submenu the check is not visible in the native Windows popup menu.

**To Reproduce**
Mark as checked with IPopupMenu::Item::SetChecked(true) a IPopupMenu::Item and add it to the IPopupMenu with a submenu calling to IPopupMenu::AddItem(const char* str, IPopupMenu* pSubmenu, int index = -1)

This item will not appear as checked on Windows platforms.

**Expected behaviour**
In the native Windows popup menu the item is checked.

Reproduced on Windows 10 as standalone app and VST3 using NanoVG.

**Additional context**
It seems like in the same case the "enabled" and "title" flags will fail too.

In IGraphicsWin::CreateMenu() function, it seems like flags are not properly set:

```
      if (pMenuItem->GetSubmenu())
      {
        HMENU submenu = CreateMenu(*pMenuItem->GetSubmenu(), pOffsetIdx);
        if (submenu)
        {
          <<<<<HERE FLAGS SHOULD BE SET, SIMILAR TO THE ELSE BLOCK>>>>>>
          AppendMenu(hMenu, flags|MF_POPUP|MF_ENABLED, (UINT_PTR)submenu, (const TCHAR*)entryText.Get());
        }
      }
      else
      {
        if (pMenuItem->GetEnabled())
          flags |= MF_ENABLED;
        else
          flags |= MF_GRAYED;
        if (pMenuItem->GetIsTitle())
          flags |= MF_DISABLED;
        if (pMenuItem->GetChecked())
          flags |= MF_CHECKED;
        else
          flags |= MF_UNCHECKED;

        AppendMenu(hMenu, flags, offset + inc, entryText.Get());
      }
```

I tried this and it seems to work:

```
      if (pMenuItem->GetSubmenu())
      {
        HMENU submenu = CreateMenu(*pMenuItem->GetSubmenu(), pOffsetIdx);
        if (submenu)
        {
          if (pMenuItem->GetEnabled())
            flags |= MF_ENABLED;
          else
            flags |= MF_GRAYED;
          if (pMenuItem->GetIsTitle())
            flags |= MF_DISABLED;
          if (pMenuItem->GetChecked())
            flags |= MF_CHECKED;
          else
            flags |= MF_UNCHECKED;

          AppendMenu(hMenu, flags|MF_POPUP, (UINT_PTR)submenu, (const TCHAR*)entryText.Get());
        }
      }
      else
      {
        if (pMenuItem->GetEnabled())
          flags |= MF_ENABLED;
        else
          flags |= MF_GRAYED;
        if (pMenuItem->GetIsTitle())
          flags |= MF_DISABLED;
        if (pMenuItem->GetChecked())
          flags |= MF_CHECKED;
        else
          flags |= MF_UNCHECKED;

        AppendMenu(hMenu, flags, offset + inc, entryText.Get());
      }
```

**Comment by baktery** [comment]
PR sent

**Comment by olilarkin** [comment]
Am I correct in my understanding that you want to enable checking of submenus like this:

![image](https://user-images.githubusercontent.com/655662/79068329-123f7300-7cbe-11ea-9560-493562b45266.png)

I am trying to work out if this is possible with macOS submenus. If so we should implement it there too. If not, i am not sure if we should add it or not. Probably yes, but with a note saying it is not cross platform

https://developer.apple.com/documentation/appkit/menus_cursors_and_the_dock?language=objc

**Comment by olilarkin** [comment]
ok it does work on macos

**Comment by baktery** [comment]
Yes, that's it

**Comment by olilarkin** [comment]
merged
