### ISSUE TITLE
Control binded to a param not redrawn when automated (Live/VST3)

### ISSUE THREAD

**Issue by baktery** [iPlug2/iPlug2#488]
**Describe the bug**
When a IKnobControl is binbed to a param and the param is automated from a DAW the IKnobControl is not updated with the new values of the param.

If I manually rescale the plugin window while the param is been automated a redraw is forced and the knob is properly updated.

**To Reproduce**
1. Duplicate the IPlugEffect example and compile it as VST3.
2. Create a new track on Ableton with the plugin
3. Automate the Gain parameter
4. Play the song
5. Gain parameter been automated in Live is not updated in the plugin (if you resize the plugin window manually from the windows corner the knob is redrawn and the param value is updated).

**Expected behaviour**
Knob is updated with the new param value automatically.

Tested on Windows 10 as VST3 64bit with NanoVG. Ableton Live 10.

**Comment by olilarkin** [comment]
grrr... i feel there is something very funky with the VST3 implementation in Live

**Comment by baktery** [comment]
I can say that at least IEditorDelegate::OnParamChange is called by Live

**Comment by olilarkin** [comment]
pretty certain this is a bug in live.

from:

https://steinbergmedia.github.io/vst3_doc/vstinterfaces/vst3Automation.html

Automation Playback
In VST 3, automation playback is the task of the Plug-in and it is the host's task to provide the automation data. The only way for a parameter change to arrive in the processor is the processing call. Indeed, receiving parameter changes from the edit controller and playing back automation data is one and the same thing.
Of course the need to do all transformations from the normalized GUI representation to the DSP representation produces some overhead. Performing sample accurate automation requires even more overhead, since the DSP value must be calculated for each single sample. While this can not be avoided totally, it is the choice of the Plug-in implementation of how much processing time should be spent on automation accuracy. The host always transmits value changes in a way that allows a sample accurate reconstruction of the underlying automation curve. The Plug-in is responsible for the realization.

**GUI playback
The host is responsible for updating the Plug-in GUI when automation data is transmitted to the processor. This is realized by frequent calls of Steinberg::Vst::IEditController::setParamNormalized.**

Live automation does not call setParamNormalized

**Comment by olilarkin** [comment]
odd, it sends setParamNormalized for AGain (vst3 example) but not for iPlug plugins

**Comment by baktery** [comment]
Ok, I see something (maybe?). IPlugVST3::getParamNormalized() is always retuning 0.0.

If I return a different value each time, then it calls setparamnormalized while automatization is going:
```
ParamValue PLUGIN_API IPlugVST3::getParamNormalized(ParamID tag)
{
  //if (tag >= kBypassParam)
  //  return EditControllerEx1::getParamNormalized(tag);

  float s_v = 0.0f;
  s_v += 0.25f;
  if (s_v > 1.0f)
  {
    s_v = 0.0f;
  }
  return s_v;
  //return IPlugVST3ControllerBase::GetParamNormalized(this, tag);
}
```

**Comment by baktery** [comment]
also knob value is updated

**Comment by olilarkin** [comment]
aha good catch.

we can probably do away with IPlugVST3::getParamNormalized()

and just let it call the base EditControllerEx1::getParamNormalized()

assuming the VST3 param is in-sync with the IPlug param

**Comment by baktery** [comment]
So, this is your proposal:

```
ParamValue PLUGIN_API IPlugVST3::getParamNormalized(ParamID tag)
{
  return EditControllerEx1::getParamNormalized(tag);
}
```

Here it works.

**Comment by olilarkin** [comment]
basically yest

**Comment by olilarkin** [comment]
I commented out the getParamNormalized() overrides. I don't think this will have any adverse side affects, but will think about it some more.

**Comment by olilarkin** [comment]
unfortunately commenting that out broke VST3 in cubase. re-opening this

https://github.com/iPlug2/iPlug2/issues/183

**Comment by AlexHarker** [comment]
I think I wrote those and they are definitely needed, but I can't remember exactly why. I think that we only store the actual parameter in the IParam which uses its own field for the value not the one that the default getter uses.

If it is always returning zero then it implies that the tag might not be finding a parameter. If someone could make a project to test on I can take a look.

**Comment by olilarkin** [comment]
I can't reproduce this anymore. @baktery can you?

**Comment by baktery** [comment]
Hehe, I just discovered something new about this issue... maybe it will help to find a solution.

Are you trying to reproduce it as an effect (after another effect or instrument), aren't you? I just noticed that only fails using the plugin as instrument! Here as effect it is working fine but as instrument the issue can be reproduced.

**Comment by olilarkin** [comment]
can confirm. I swear i had it working with IPlugInstrument earlier though

**Comment by baktery** [comment]
I tried it again, more feedback:

Effects are also failing, the problem is that it's not determinist. at least I can't see a clear pattern.

Sometimes it seems to work 100% fine, you see that the controls are following the automation very smoothly. 

Sometimes, the same automation that worked fine before, does not work 100% fine. For example you see that controls are updated but from time to time and if you resize the plugin window you see that they didn't have the latest value, when resized the proper value is shown.

And sometimes it never works, controls are never updated until you force it resizing the plugin window.

Another thing I noticed with the IPlugEffect example is that sometimes Knob control value is updated but not the knob position, for example:

![image](https://user-images.githubusercontent.com/7185257/80854983-f71caf00-8c3c-11ea-9098-e4ed79e728fb.png)

In this case resizing the window does nothing, knob position is not updated to the proper position.

 Again, I can't see a pattern to reproduce it. Sometimes the knob position is updated, sometimes only the text value and sometimes nothing is updated.

**Comment by AlexHarker** [comment]
If you get text charging without the knob changing then it sounds like it might be a drawing/window update issue. There is no way either the knob, or the text could update without the correct value reaching the control, so I think the getParameter stuff might be a red herring, and what we are seeing here is the window not refreshing properly.

Platform and graphics backend?

**Comment by AlexHarker** [comment]
The resizing thing/window reopening thing also points to graphics drawing, not updates of the values. I don't think this is anything to do with the latter. (The window resize was mentioned in the first post and all that does is redraw the controls - it doesn't update their values). So we're looking at a very different issue about why the window doesn't update correctly.

**Comment by baktery** [comment]
> Platform and graphics backend?

Windows 10 VST3 64bit with NanoVG. Ableton Live 10.

**Comment by AlexHarker** [comment]
Would you be able to test on windows/Ableton with some other backends?

**Comment by baktery** [comment]
> Would you be able to test on windows/Ableton with some other backends?

Sure, I'll test it with Skia.

**Comment by baktery** [comment]
Same issue using Skia instead of NanoVG.

![autom](https://user-images.githubusercontent.com/7185257/80867335-febb7280-8c93-11ea-8435-fc0c012e6b49.gif)

**Comment by baktery** [comment]
We have two issues there.


1) This bug report original issue 👍 

2) Sometimes out of sync between the text value and knob position.

About the second one, I checked the sources and the knob position (rotation) and each of them read the value from a different source. Text uses IParam direcly with the function GetParam() and rotation uses GetValue() (which uses something like an internal control-cached value, mVals).

With the following draw code both elements show the same value:

```
void IVKnobControl::DrawWidget(IGraphics& g)
{
  float widgetRadius; // The radius out to the indicator track arc
  
  if(mWidgetBounds.W() > mWidgetBounds.H())
    widgetRadius = (mWidgetBounds.H()/2.f);
  else
    widgetRadius = (mWidgetBounds.W()/2.f);
  
  const float cx = mWidgetBounds.MW(), cy = mWidgetBounds.MH();
  
  widgetRadius -= (mTrackSize/2.f);

  IRECT knobHandleBounds = mWidgetBounds.GetCentredInside((widgetRadius - mTrackToHandleDistance) * 2.f );

  // THIS WAY, CURRENT ONE, ROTATION IS NOT SYNC WITH TEXT VALUE
  //const float angle = mAngle1 + (static_cast<float>(GetValue()) * (mAngle2 - mAngle1));

  // THIS WAY, ROTATION AND TEXT VALUE ARE SYNC OK
  const float value = GetParam()->GetNormalized();
  const float angle = mAngle1 + (static_cast<float>(value) * (mAngle2 - mAngle1));

  DrawIndicatorTrack(g, angle, cx, cy, widgetRadius);
  DrawPressableShape(g, /*mShape*/ EVShape::Ellipse, knobHandleBounds, mMouseDown, mMouseIsOver, IsDisabled());
  DrawPointer(g, angle, cx, cy, knobHandleBounds.W() / 2.f);
}
```

**Comment by AlexHarker** [comment]
Thanks - that's really helpful. I was previously wrong, as I don't know the vector controls very well.

So - there are a couple of things this points to, but I have a couple more questions so we can isolate this better.

1 - I presume this is a non-distributed VST3 build? (I'm actually not sure of the current state of VST3 in this regard. It's possible that question is not one you can easily answer.

2 - When do you *hear* the automation working - always / only when the knob moves / whenever the text updates (or some other option)

When the text and knob display different values that implies an issue in terms of the control being updated - this could be a threading issue - @olilarkin knows more about this part of iplug2 than I do. The change you make above will always sync the text and knob, but it's not clear if the parameter is also missing updates (That is what question 2 is about).

**Comment by olilarkin** [comment]
It happens in both distributed and non-distributed VST3 in Live on win & mac.

**Comment by olilarkin** [comment]
GUI problem disappears in Non-distributed VST3, if I comment this in IPlugVST3_ProcessorBase.cpp

```//#ifdef PARAMS_MUTEX
//                mPlug.mParams_mutex.Enter();
//#endif
//                mPlug.GetParam(idx)->SetNormalized(value);
//
//                // In VST3 non distributed the same parameter value is also set via IPlugVST3Controller::setParamNormalized(ParamID tag, ParamValue value)
//                mPlug.OnParamChange(idx, kHost, offsetSamples);
//#ifdef PARAMS_MUTEX
//                mPlug.mParams_mutex.Leave();
//#endif```

**Comment by olilarkin** [comment]
But then OnParamChange() doesn't get called, meaning in iPlug instrument, DSP doesn't get updated.

Theory:
Before every call to IPlugVST3::setParamNormalized() Live calls IPlugVST3::getParamNormalized() and if the returned value is the same as what live thinks the parameter should be, it doesn't send setParamNormalized().

The audio-thread parameter changes update the iPlug parameter with the new value, prior to Live calling IPlugVST3::getParamNormalized(), which then returns the same value and setParamNormalized() doesn't get called, meaning the DSP/ sound gets changed but not the UI. 

The text display beneath the IVKnobControl gets its value from the IParam, if for instance you mouse-over it triggers an update, but the knob itself doesn't change because SendParameterValueFromDelegate() never got called to update its mVal

**Comment by AlexHarker** [comment]
This branch is an attempt to fix this - still more to discuss with VST3 to ensure that things are being done correctly

https://github.com/iPlug2/iPlug2/tree/VST3/parameter-management

**Comment by olilarkin** [comment]
Alex's branch seems to fix this, @baktery are you still around, and would you like to try?

**Comment by baktery** [comment]
Sure! I'll try it in the following days
