### ISSUE TITLE
using PLUG_CLASS_NAME macro in C++ class is FUGLY

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#50]
Only used for distributed VST3 to avoid a clash when compiling controller as a static lib. Is there another way?

**Comment by AlexHarker** [comment]
@olilarkin - did you mention a plan for this at some point?

**Comment by olilarkin** [comment]
i don't recall doing so

**Comment by olilarkin** [comment]
I am just going to close this. VST3 distributed builds are rarely essential. We can cope with the FUGLYness
