### ISSUE TITLE
IPlug2 instruments crash vst3 Reaper midi learn (all recent versions)

### ISSUE THREAD

**Issue by gvampgh** [iPlug2/iPlug2#507]
The IPlugInstrument vst3 example (and others) crashes Reaper 5 / 6 on windows 10, regardless of audio output device and reaper version. E.g. CC 16 messages are ok (knobs on my Oxygen keyboard) and learned correctly. Sliders cause crashes, the id AND index of the "virtual iplug2 vst3 midi parameters" are out of bounds. VST2 is ok by the way.

Reproduce:
- add track in reaper, add IPlugInstrument
- Aim track, input device e.g. external midi keyboard, all channels of it, cc messages must be enabled in midi device preferences
- Right mouse button on a control (e.g. Gain), Learn, move slider on a midi keyboard -> crash. It seems that the added Parameters by IPlug2 with Id > 65000 are out of bounds in any way.

![grafik](https://user-images.githubusercontent.com/48643530/80302523-d4a51480-87aa-11ea-8069-e971e43e2c2b.png)

![grafik](https://user-images.githubusercontent.com/48643530/80302559-f69e9700-87aa-11ea-958c-995b9f7b616a.png)

![grafik](https://user-images.githubusercontent.com/48643530/80302581-2057be00-87ab-11ea-92d6-3814993213db.png)

![grafik](https://user-images.githubusercontent.com/48643530/80302677-c1467900-87ab-11ea-98b1-e709bce6573e.png)

**Comment by olilarkin** [comment]
Have you go the very latest version of reaper? I have tried to reproduce this but I can't make it crash

**Comment by olilarkin** [comment]
what is the MIDI CC number that causes a crash? you say it works for some and not others?

**Comment by gvampgh** [comment]
Yes, I have tested an older version 5 of reaper and the newest installed today, both crash. VST2 shows the below CC messages. My 9 sliders have theses CC messages below. I have recognized that the problematic controls have channel numbers > 1. All my knobs have channel number 1 as well and are working correctly.

MIDI Chan 2 CC 7 Crash
MIDI Chan 2 CC 8 Crash
MIDI Chan 2 CC 10 Crash
MIDI Chan 2 CC 91 Crash
MIDI Chan 3 CC 7 Crash
MIDI Chan 3 CC 8 Crash
MIDI Chan 3 CC 10 Crash
MIDI Chan 3 CC 91 Crash
MIDI Chan 1 CC 7  OK

**Comment by olilarkin** [comment]
OK makes more sense.

You need to define VST3_NUM_MIDI_IN_CHANS=16 and VST3_NUM_CC_CHANS=16 as processor macros in order to add enough VST3 MIDI CC parameters to handle all 16 midi channels.

Nevertheless this shouldn't crash, so looking into it.

**Comment by gvampgh** [comment]
I set both to 16 in IPlug\VST3\IPlugVST3_Defs.h (config.h didn't work, maybe I have to do a complete rebuild) and this instantly fixed it, thank you, Oli ! Maybe consider this to be default settings, I could do the small pr, if you want.

**Comment by olilarkin** [comment]
No, sorry. I hate having 16 * 128 extra parameters!

you can override the setting via a preprocessor macro  in xcconfig or .props file like i said
