### ISSUE TITLE
Horizontal ISVGSliderControl offset

### ISSUE THREAD

**Issue by JanezKrizaj** [iPlug2/iPlug2#527]
I tried to use horizontal ISVGSliderControl but the handle did not move properly. The handle did not move from the center to the left and on the right side, the handle disappeared.

In IControls.cpp I changed line 1388 from:
float offs = (float) value * mTrackBounds.W();
to:
float offs = (-0.5f + (float) value) * mTrackBounds.W() * 0.8f;

I am not sure if this is a universal solution but it works for me very well.

**Comment by olilarkin** [comment]
What svgs were you using?

**Comment by JanezKrizaj** [comment]
I used svgs from IPlugControls example, rotated  90°. The offset factor I used (0.8) depends on the size of the handle. Seems if the handle is only one pixel wide, there is no need to use the factor.

On more slightly related issue is with vertical ISVGSliderControl, mouse click snaps on the bottom of the handle, but it should snap in the middle of the handle. Horizontal ISVGSliderControl mouse click snaps in the center of the handle if I do not use the offset factor.

**Comment by olilarkin** [comment]
thanks, looks like the bug is in ISVGSliderControl::OnResize()

**Comment by olilarkin** [comment]
Please try this commit on master

https://github.com/iPlug2/iPlug2/commit/e621231a5c81480bd422bb0995dc30c872723956

snapping not yet changed

**Comment by JanezKrizaj** [comment]
Thanks, horizontal slider functional :-)  
(Horizontal slider MouseClick snaps on the right border of the handle (vertical slider, bottom border of the handle), it is hard to notice with small-sized graphics but with a large slider, it becomes obvious.)
I am also very happy to see some new stuff in the IPlugControll example.
