### ISSUE TITLE
Cairo [ed: Also SKIA CPU, AGG] backend not drawing with Logic Pro X 10.5

### ISSUE THREAD

**Issue by hor-net** [iPlug2/iPlug2#535]
**Describe the bug**
All the plugins i made with IPlug2 and Cairo only show a black windows with the new Logic Pro X. If I switch to another backend they work fine. 

**To Reproduce**
Just build IPlugEffect as audio unit using Cairo as backend and try to open it with Logic 10.5

**Expected behaviour**
I expect the GUI to be shown when I open the plugin window

**Screenshots**
![Screenshot 2020-05-18 at 12 03 33](https://user-images.githubusercontent.com/704273/82200781-be98f880-98ff-11ea-8950-15107f61f0c9.png)

**IMPORTANT DETAILS**
Audio Unit only
macOS
CAIRO

**Comment by olilarkin** [comment]
appears to be fixed by adding

```
  self.wantsLayer = YES;
```

to the IGraphics view

**Comment by AlexHarker** [comment]
Does this affect the Cairo bug in later OSes to do with missing/unbalanced stack states?

**Comment by hor-net** [comment]
> Does this affect the Cairo bug in later OSes to do with missing/unbalanced stack states?

Is there any specific test I can do to check this? I'm going to run some tests on various DAW/macOS combo to make sure that everything is ok so I can do that check too

**Comment by olilarkin** [comment]
dont think its fixed by this. move the plugin ui from one screen to another
it will crash
