### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by qzic** [iPlug2/iPlug2#538]
Is there a better place to ask questions like this?  If so, please point me there.

Could you explain how to setup aax on windows. I'm  new to vc++ ide.
I'm looking at the properties of AAXLibrary.vcxproj but I don't see where to do what you suggest in the README.md

"On Windows you will need to set the Libs/AAXLibrary/WinBuild/AAXLibrary.vcxproj project to link statically to the MSVC runtime library - change to /MT rather than /MD"

I'm getting this type of error 

 IPlugAAX_Parameters.h(147,44): error C3646: 'AAX_OVERRIDE': unknown override specifier (compiling source file ..\..\..\IPlug\AAX\IPlugAAX_Parameters.cpp)

**Comment by olilarkin** [comment]
Hello,

the [forum](https://iplug2.discourse.group/) is the place for newbie questions, github issues is for bug reports

i clarified the instructions here https://github.com/iPlug2/iPlug2/blob/master/Dependencies/IPlug/AAX_SDK/README.md

but that error seems unrelated. Make sure you have the AAX_SDK_2p3p2 in the correct place.
