### ISSUE TITLE
Studio One macOS freeze using ICaptionControl's dropdown

### ISSUE THREAD

**Issue by hor-net** [iPlug2/iPlug2#540]
**Describe the bug**
When using a plugin that includes the ICaptionControl and the control is linked an enum, the dropdown with the choices is shown. Showing the dropdown and choosing options works fine, when you quit Studio One the software hangs forever

**To Reproduce**
Build IPlugControls-macOS, no matter if VST, VST3 or AU, open it in studio one and click on any control that shows a dropdown, it doesn't matter if you select an option or just click outside the control do dismiss the dropdown. Quit Studio one, it doesn't matter if you save the project or not, Studio One will freeze.

**Expected behaviour**
I Expect he software to quit correctly as it does if no dropdown is ever shown/clicked

**IMPORTANT DETAILS**
* It relates to ALL plugin format
* macOS
* ALL graphics backend.

**Additional context**
I've tested it with both the custom popup menu control ad the system one and the issue happens in both cases. I'll try to drop a line to Studio One's team if the bug is confirmed by you.

**Comment by olilarkin** [comment]
confirmed. there is a std::bad_cast in the stack trace
