### ISSUE TITLE
AudioUnit framework needs to be linked before the AudioToolbox - 10.15 SDK

### ISSUE THREAD

**Issue by Youlean** [iPlug2/iPlug2#545]
It seems that this is required when building with latest SDK.
More info here: https://forum.juce.com/t/plug-in-built-with-xcode-11-fails-to-load-on-yosemite-10-10/35912/40

This line should be changed: https://github.com/iPlug2/iPlug2/blob/cbd9268d130707d615e3755ecd8d4c34dfb4c7a7/common-mac.xcconfig#L143

It should be:
`AU_FRAMEWORKS = -framework AudioUnit -framework AudioToolbox -framework CoreAudio -framework CoreMIDI`

**Comment by olilarkin** [comment]
hopefully fixed in 6aa7f2776fb64f14af575b0adbb295f2e62bafbb
