### ISSUE TITLE
Bad silder dragging behavior when hide mouse is disabled

### ISSUE THREAD

**Issue by mmontag** [iPlug2/iPlug2#551]
**Describe the bug**
Undesirable slider dragging behavior when hide-mouse is disabled. The cursor pushes the slider from a distance.

![capture_2020-05-30_19 46 46](https://user-images.githubusercontent.com/946117/84004589-9f9aee80-a920-11ea-9683-44034cd8686d.gif)

**Expected behaviour**
Expect control not to move until the mouse moves back inside the control area. 

Workaround: 

![image (1)](https://user-images.githubusercontent.com/946117/84004850-12a46500-a921-11ea-9064-e1fcdd9afb10.png)

@AlexHarker

**Comment by AlexHarker** [comment]
The fix looks to be using the original code but taking the first branch if the cursor is not hidden, as well as if this is a touch gesture @olilarkin - does that seem right? Are there other cases in the IVControls where we should do the same?
