### ISSUE TITLE
Clean up Presets vs. Programs

### ISSUE THREAD

**Issue by mmontag** [iPlug2/iPlug2#555]
In some places `Program` and `Preset` appear to be used interchangeably. 

In example code, i.e. https://github.com/iPlug2/iPlug2/blob/master/Examples/IPlugInstrument/IPlugInstrument.h#L6,  we use `kNumPrograms`.
in the `MakeConfig` this argument is `nPresets`. https://github.com/iPlug2/iPlug2/blob/master/IPlug/IPlug_include_in_plug_src.h#L336

**Comment by olilarkin** [comment]
agreed, i think i will replace program with preset

**Comment by olilarkin** [comment]
done on master

**Comment by mmontag** [comment]
awesome 👍
