### ISSUE TITLE
Plugin::OnParamChangeUI is called even if the UI isn't available.

### ISSUE THREAD

**Issue by Bindernews** [iPlug2/iPlug2#559]
Problem is exactly as it says in the title. The first line of my `OnParamChangeUI` method is `if (!GetUI()) { return; }` because the method is being called both before UI is first displayed and when parameters are changing due to automation, but the UI is not currently visible. This seems quite silly.

**To Reproduce**
Implement `OnParamChangeUI` then try to call `GetUI()`. It'll crash both on plugin startup and later on unless you check to make sure the UI is available.

**Expected behaviour**
Method should not be called if UI isn't available. I think adding a quick `if (plugin->GetUI()) { ... }` around each place this is called would do the trick.

**Formats**: VST2, VST3, not sure about the others.
**Platforms**: Windows for certain, haven't tested on Mac.

**Comment by olilarkin** [comment]
OnParamChangeUI . UI refers to UI / Main thread, NOT Graphics. You need to test for the existence of IGraphics if you are going to touch it
