### ISSUE TITLE
Resizing editor - dimensions and mouse scaling should be correctly restored

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#56]
Steps to reproduce:

- create a instance of the plug-in
- resize with the corner resize
-  close the plug-in interface
-  reopen the interface

=  dimensions are same as when closed, but mouse coordinates are wrong

**Comment by AlexHarker** [comment]
Fixed in ca50b32ea278f867e9841cae78f1cf01fc95aaed (will open new issues about recall when the plug is reloaded)
