### ISSUE TITLE
IVButtonControl doesn't return to normal appearance on mouse up

### ISSUE THREAD

**Issue by mmontag** [iPlug2/iPlug2#561]
When not using a splash animation action function, `IVButtonControl` remains highlighted (in pressed state) on mouseup.

**Comment by olilarkin** [comment]
Yes, you can either call SpashClickActionFunc in your lambda or use IControl:SetEndanimationFunc to set an action that happens after the animation

**Comment by mmontag** [comment]
Sorry about this, maybe I should explain myself a little better...

With current behavior, the button is designed to run a brief animation on click. But it doesn't render a different apparance for a pressed state. 

My request is for a conventional button behavior, where the button remains in a pressed visual state until mouse up. The IVButtonControl doesn't offer this ability right now, but I think it would be a nice option.
