### ISSUE TITLE
OSCReceiver and OSCSender cannot be used at the same time

### ISSUE THREAD

**Issue by cristianvogel** [iPlug2/iPlug2#580]
discussed with @olilarkin at Slack. Making a bug report here. 

Inheriting  OSCReceiver like this in my code 
`NEL_VirtualControlSurface::NEL_VirtualControlSurface(const InstanceInfo &info)
    : Plugin(info, MakeConfig(kNumParams, kNumPresets))
    , OSCReceiver(9090)`

blocks the initialisation of any localhost OSCSender instance

**Comment by olilarkin** [comment]
fixed on master
