### ISSUE TITLE
WDL_HeapBuf GetSize() crashes on call to OSCSender::SetDesination

### ISSUE THREAD

**Issue by cristianvogel** [iPlug2/iPlug2#588]
Testing OSCSender right now.
I am sending in a valid IP address and port, but the program halts inside 
`423 if (strcmp(ip, mDestIP.Get()) && port != mPort)` 
of IPlugOSC.cpp

**Comment by olilarkin** [comment]
could you git pull and try again ?

**Comment by olilarkin** [comment]
and again, pushed too soon

**Comment by cristianvogel** [comment]
Its still happening on line 57 of WDL_HeapBuf
