### ISSUE TITLE
Ableton Live VST3 window size error if size set by a control whilst opening the window (Windows only)

### ISSUE THREAD

**Issue by AlexHarker** [iPlug2/iPlug2#593]
**Describe the bug**
If when the window is created a control resizes/rescales Ableton Live VST3 on windows does not respect this and resizes the window to the old size. Reaper does not exhibit this error.

This happens because getSize() is called before attachment and onSize() is called post attachment with the old size. This is different behaviour to that on Mac.

**To Reproduce**
Create a control that rescales or resizes IGraphics in the OnInit() method.
Open the plugin window in Ableton Live on a VST3.

**Expected behaviour**
The plugin opens at the new size.

VST3 / Windows / Ableton Live - tested on skia only.

**Comment by rexmartin158** [comment]
Possibly related issue #769.

**Comment by AlexHarker** [comment]
This is nanovg only - this appears to be an Ableton bug - should consider reporting to them

**Comment by TBProAudio** [comment]
Fixed with release 11.2.
