### ISSUE TITLE
IPopupMenuControl doesn't position well/stay within bounds, triangles need improvement. 

### ISSUE THREAD

**Issue by dmsplugins** [iPlug2/iPlug2#595]
About a week ago or so, I saw a post on Slack about how to use the control, referencing the IPlugControls project.
It is a really nice control. Anyway, I know you are already aware of its issues as they are commented as Todo in the code.
I've spent about a week working on it and have gotten the triangles looking better and the menu panels staying within bounds.
I'm sending a PR.

**Comment by olilarkin** [comment]
work merged on master
