### ISSUE TITLE
GetMouseIsOut() convenience method to match GetMouseIsOver()

### ISSUE THREAD

**Issue by cristianvogel** [iPlug2/iPlug2#599]
I find `GetMouseIsOver()` is really quick and handy when attaching controls using lambdas. 
But I have to do quite a bit of work , if I then just want to change or redraw things differently when the mouse has left. 

Unless I've got the wrong idea, I would have to implement a new Class for my control , just to override the `OnMouseOut()` method which can get pretty hairy when there's alot of setup in the anonymous func and it also defeats the point of the `GetMouseIsOver()`  convenience.

**Comment by olilarkin** [comment]
You have the wrong idea i'm afraid. Creating custom controls should be seen as the norm, since it is very hard for IVControls etc to cover all bases. Also GetMouseIsOut() would be a very weird thing to add.

**Comment by cristianvogel** [comment]
ok, thanks. 

> Creating custom controls should be seen as the norm, since it is very hard for IVControls etc to cover all bases.

If this is the desired design patterns, then I think some custom controls examples should be included for newcomers to the Framework. Currently there's a lot of examples of ActionFunction , Lambda based control designing.
