### ISSUE TITLE
Cannot build IPlugSwift example

### ISSUE THREAD

**Issue by cristianvogel** [iPlug2/iPlug2#612]
Installed dependencies through podfile, but compiler throws 
```..../iPlug2/IPlug/IPlug_include_in_plug_src.h:338:268: Use of undeclared identifier 'PLUG_HOST_RESIZE'```

I made a build by adding `#define PLUG_HOST_RESIZE false` to config.h , but not sure if this is correct? Perhaps devs should put the correct def in place, so it compiles and runs.

**Comment by AlexHarker** [comment]
I believe this needs to be defined as a macro in config.h as 0 or 1.

Please try putting this in config.h and let us know what happens. I've not worked on this example, and it may not be fully up to date in other ways.

#define PLUG_HOST_RESIZE 0

**Comment by olilarkin** [comment]
fixed on master
