### ISSUE TITLE
The same midi messages for different events.

### ISSUE THREAD

**Issue by serkkz** [iPlug2/iPlug2#615]
When using an external MIDI keyboard, I get code 9 when I press the key and the same code when I release it.

```C++
void MyVST::ProcessMidiMsg(const IMidiMsg& msg)
{
  std::cout << "\n" << "Status: " << msg.StatusMsg();
}
```
When the keyboard is virtual, I get a 9 code when pressed. And when they released 8.

**Comment by olilarkin** [comment]
Some devices send a note-on message with a velocity of zero instead of a note off message.
