### ISSUE TITLE
IPlugAPIBase: mParamChangeFromProcessor etc should be private

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#617]
end users should not access these in their plugin class

**Comment by AlexHarker** [comment]
Do you have a set of exact proposed variables to make private?

**Comment by olilarkin** [comment]
`protected:
  WDL_String mParamDisplayStr;
  std::unique_ptr<Timer> mTimer;
  
  IPlugQueue<ParamTuple> mParamChangeFromProcessor {PARAM_TRANSFER_SIZE};
  IPlugQueue<IMidiMsg> mMidiMsgsFromEditor {MIDI_TRANSFER_SIZE}; // a queue of midi messages generated in the editor by clicking keyboard UI etc
  IPlugQueue<IMidiMsg> mMidiMsgsFromProcessor {MIDI_TRANSFER_SIZE}; // a queue of MIDI messages received (potentially on the high priority thread), by the processor to send to the editor
  IPlugQueue<SysExData> mSysExDataFromEditor {SYSEX_TRANSFER_SIZE}; // a queue of SYSEX data to send to the processor
  IPlugQueue<SysExData> mSysExDataFromProcessor {SYSEX_TRANSFER_SIZE}; // a queue of SYSEX data to send to the editor
  SysExData mSysexBuf;
};
`
These shouldn't be something the final plugin class can access, but the API classes need to IPlugAPP and so on

**Comment by AlexHarker** [comment]
We can use friends to allow access, or a few other patterns that can allow access to specific named classes if that is desirable.

**Comment by olilarkin** [comment]
Any of those other patterns nicer that #730 ?

**Comment by AlexHarker** [comment]
No - I think the other patterns would be overall less nice, and only worth it if we wanted to give access to selected items - as we are in the library here I don't think that is an issue, so that looks good to me.

**Comment by olilarkin** [comment]
merged
