### ISSUE TITLE
unify std::functions that take an iControl

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#618]
using IActionFunction = std::function<void(IControl*)>;
using IAnimationFunction = std::function<void(IControl*)>;

IGraphics::ForAllControls take std::function<void(IControl& control)

**Comment by AlexHarker** [comment]
Which one do you want to go with? Obviously either way breaks, probably more so if we go to references, but there's a decision to make either way.

**Comment by olilarkin** [comment]
These ones IGraphics::ForAllControls are less user facing, i would suggest changing them to pointers, if you agree

**Comment by AlexHarker** [comment]
I wouldn't object - do you want to do the PR? - happy either way.

**Comment by AlexHarker** [comment]
Merged the PR in 16d76c45306e9e77674f4a33d4ce2a5c3fedcab9.
