### ISSUE TITLE
Missing zlib path in cairo windows build

### ISSUE THREAD

**Issue by hor-net** [iPlug2/iPlug2#62]
I was building the cairo libs on windows and VS complained that zlib.h was unavailable.
Inspecting the cairo.vcxproj shows that the zlib path is missing from the includes.

Adding it solved my build issue:

<AdditionalIncludeDirectories>$(ProjectDir)..\;$(ProjectDir)..\..\glew\include;$(BUILD_DIR)\src\pixman\pixman;$(BUILD_DIR)\src\freetype\freetype\include;$(BUILD_DIR)\src\libpng;$(BUILD_DIR)\src\cairo\src;$(BUILD_DIR)\src\zlib;</AdditionalIncludeDirectories>

**Comment by AlexHarker** [comment]
I didn't need to adapt the solution to make this compile, so I'm not sure what is happening here.Were you compiling through the batch script?

**Comment by AlexHarker** [comment]
this seems to be something that could be checked/addressed alongside #114

**Comment by olilarkin** [comment]
i am going to close this, because on several machines i haven't had a problem.
