### ISSUE TITLE
Vector Knob Range Indicators

### ISSUE THREAD

**Issue by JanezKrizaj** [iPlug2/iPlug2#622]
In IControls.cpp at "void IVKnobControl::DrawIndicatorTrack …" after the line 578
I added two lines to draw range indicators:
    g.DrawRadialLine(GetColor(kX1), cx, cy, mAngle1,  radius + mTrackSize * 0.125 , radius + mTrackSize * 0.5, &mBlend, 3.f);
    g.DrawRadialLine(GetColor(kX1), cx, cy, mAngle2,  radius + mTrackSize * 0.125 , radius + mTrackSize * 0.5, &mBlend, 3.f);
works good for me, might be nice addition for release, but I believe it could be coded better ;-)
<img width="106" alt="Screenshot 2020-09-20 at 15 37 23" src="https://user-images.githubusercontent.com/33461940/93712601-3f3e5e80-fb57-11ea-861f-72990ad9e09d.png">

**Comment by olilarkin** [comment]
Thanks for this. I have an IKnobTicks control somewhere that does this and intermediate ticks which i will merge at some point
