### ISSUE TITLE
transparent color stops in gradients don't look the same in nanovg/skia/cairo

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#624]
```
    pGraphics->AttachPanelBackground(COLOR_WHITE);
    const IRECT b = pGraphics->GetBounds();

    pGraphics->AttachControl(new ILambdaControl(b,
      [](ILambdaControl* pCaller, IGraphics& g, IRECT& rect) {
      
       const IPattern pattern = IPattern::CreateLinearGradient(rect, EDirection::Horizontal, { {COLOR_TRANSPARENT, 0.f}, {COLOR_RED, 1.f} });
       g.PathRect(rect);
       g.PathFill(pattern)
    }, DEFAULT_ANIMATION_DURATION, false /*loop*/, false /*start immediately*/));
  };
```

<img width="524" alt="Screenshot 2020-09-26 at 12 20 01" src="https://user-images.githubusercontent.com/655662/94339682-9fb81a80-fff3-11ea-9235-f30f72f450f4.png">

**Comment by AlexHarker** [comment]
Can you try with (0, 255, 0, 0) instead of transparent on all backends and see what happens?

To my mind skia/cairo are most arguably correct, but I can see why nanovg is doing what you want in this case.

**Comment by olilarkin** [comment]
i tried transparent white (0,255,255,255)  and it produces the same output on all three

**Comment by AlexHarker** [comment]
Yes - that makes sense also. Looks like skia/cairo are somehow respecting the colour part in the transition (then also applying alpha) but NanoVG is not.
