### ISSUE TITLE
a bug in IRECT.GetVSliced()

### ISSUE THREAD

**Issue by binyamin555** [iPlug2/iPlug2#629]
When calling IRECT.GetVSliced(bot=false), it returns the wrong IRECT
The returned IRECT is shifted down by the new height

it is a bug in the function, so just call the function with bot=false

**Comment by olilarkin** [comment]
thanks. there was a bug but not quite what you said. this should fix

f427dc11d0565fc30bed2b16cfd1622557ac5f93
