### ISSUE TITLE
Low frame rate on Windows

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#63]
Just using the performance display, it seems I don't get over 40 frames per second on Windows, on my machine with an integrated GPU or on VM. Should investigate the timer that is used and see if there's a better option

**Comment by codecat** [comment]
Noticed this too - it's running at 30 FPS only. Also, maybe it's relevant, perhaps it should only render a frame when something has changed in the UI (like mouse events or ongoing animations) rather than render every single frame?

For example on laptops, this would keep the fans from spinning because it wouldn't be rendering all the time.

**Comment by AlexHarker** [comment]
Oli has been working on this but I'm not sure what the latest status is. In general we render individual items only when needed based on UI changes. I'd have to check exactly what happens in a frame if nothing has changed (it's different according to which graphics backend you are using, but it should be fairly minimal).

**Comment by codecat** [comment]
Oh, interesting. Well, I noticed in the standalone builds you can enable an FPS counter with a graph, which shows it running at 30 FPS. But perhaps turning that on will make it render continuously on purpose.

**Comment by codecat** [comment]
Perfect, thanks for the thorough answer! ❤️

**Comment by olilarkin** [comment]
you can try the branch graphics-winmmtimer, which gives a lovely reliable FPS, however we have to think of the implications of introducing another thread for drawing. Could be a problem, especially with animation, might be easy to trigger something on the wrong thread

**Comment by madronalabs** [comment]
The ease of triggering drawing from the wrong thread has been a real problem with juce all along, so I hope we can do better. I'm up for discussing this if you like.

**Comment by codecat** [comment]
Just tried that branch and it runs well at 60! (Not 144 on my 144hz monitor though, which is interesting to note, but not a huge issue.)

**Comment by AlexHarker** [comment]
The projects are set tun at 60 by default. IF you want to test a different speed you'll need to change PLUG_FPS in config.h - perhaps you did that, but my guess is that you are getting 60 because that is what the timer is set to.

**Comment by codecat** [comment]
Ah I see, I had not seen that define yet, thanks! 144 works beautifully as well. 👍

**Comment by alsms** [comment]
Interestingly, if configured to run at the default 60 FPS the program runs at about 32 FPS on Windows. If configured to run at slightly increased FPS (say 65), however, the program runs at 60FPS. Is there a timing issue with the graphics loop?

**Comment by codecat** [comment]
Are you on the `graphics-winmmtimer` branch?

**Comment by alsms** [comment]
Im on master.

**Comment by olilarkin** [comment]
I believe i now have the beginnings of a good solution to this on the graphics-winfps branch, where only InvalidateRect is called on the multimedia timer thread. This means there are two RECTs that are in contention - they are being written by the main thread timer and read by mmtimer thread. timeSetEvent seems to be deprecated, so should possible switch to CreateTimerQueueTimer, and hopefully same approach works

https://msdn.microsoft.com/en-us/library/ms682485(v=vs.85)

**Comment by olilarkin** [comment]
Please could you all try the graphics-winfps branch, which I hope now has a good solution using CreateTimerQueueTimer.

https://github.com/iPlug2/iPlug2/tree/graphics-winfps

**Comment by olilarkin** [comment]
hmmm framerate is pretty choppy on virtual machine

**Comment by olilarkin** [comment]
what do people think about the contention around IGraphicsWin::mValidRECT and IGraphicsWin::mInvalidRECT ? They are written by the main thread (WM_TIMER) and read by the multimedia timer thread. The multimedia thread calls InvalidateRect/ValidateRect, which as far as i can tell are threadsafe.

https://github.com/iPlug2/iPlug2/blob/graphics-winfps/IGraphics/Platforms/IGraphicsWin.cpp#L171

**Comment by codecat** [comment]
Sorry, I haven't had time to try this branch yet, I'll see what I can do later tonight.

**Comment by broms95** [comment]
Another option to throw out there (I can try later) that I've used it in the past is just use multimedia timer to post a message to the main thread.  This allows all your painting and validation logic to occur on the main thread.  Unlike WM_TIMER or idle messages posting a message a WM_USER or registered message will wake up the main thread.

**Comment by olilarkin** [comment]
merged @broms95 work to improve this. define IGRAPHICS_VSYNC on windows to get nice smooth 60FPS
