### ISSUE TITLE
IFlexBox initial position is always in topleft corner.

### ISSUE THREAD

**Issue by MartinBspheroid** [iPlug2/iPlug2#640]
Here is demo what happens in example with IRECT set to windows bounds: 
![FlexBad](https://user-images.githubusercontent.com/3605151/97118193-f2771600-1708-11eb-8e44-e5b34d0e321d.gif)
But layout breaks if you supply IFlexBox different initial IRECT than window bounds: 
![FlexWrong](https://user-images.githubusercontent.com/3605151/97118271-56014380-1709-11eb-92b5-bc6914f6efc6.gif)
Recalculated layout always returns IRECTs aligned to 0,0, e.g. top left corner. Supplying additional parameters during initialization is fixing this and provides __more__ expected behavior...
![FlexRight](https://user-images.githubusercontent.com/3605151/97118323-b42e2680-1709-11eb-8f74-2391d40193b0.gif)
... but as you can see **YGFlexDirectionColumnReverse** is still misbehaving. Somehow it starts from the bottom line and continues downwards, instead of upwards (so it's invisible in the demo, but it's really there, according to my observations). 

Corresponding [PR here](https://github.com/iPlug2/iPlug2/pull/641)

**Comment by MartinBspheroid** [comment]
And [gist to reproduce](https://gist.github.com/MartinBspheroid/24e8af067229d37bf05f58145dd113e4)

**Comment by olilarkin** [comment]
thanks!

**Comment by olilarkin** [comment]
@MartinBspheroid i reverted this because it was wrong, and broke the flexbox example in IGraphicsTest

See this control, for how to use IRECT.inset to get the offsets right

https://github.com/iPlug2/iPlug2/blob/43a1dfe65d7af49ecc25b60a458aad06eb278634/IGraphics/Controls/Test/TestFlexBoxControl.h#L75

**Comment by olilarkin** [comment]
I quite like your control though, might adapt the example to use it, so thanks!

**Comment by MartinBspheroid** [comment]
Oh, i see now... I'm sorry about that I seem to miss that. And sure, go ahead, I'm sure it will help newcomers to get idea how to go about using flexbox in iplug2

**Comment by olilarkin** [comment]
https://github.com/iPlug2/iPlug2/commit/baf0383856e3a8dfc1f6c3c0ee65d207a3ce064a

**Comment by olilarkin** [comment]
https://github.com/iPlug2/iPlug2/commit/baf0383856e3a8dfc1f6c3c0ee65d207a3ce064a
