### ISSUE TITLE
Crash: IPlugEffect, OSX, CAIRO, resize

### ISSUE THREAD

**Issue by TBProAudio** [iPlug2/iPlug2#647]
Describe the bug
IPlugEffect compiled under OSX with CAIRO crashes during resizing

To Reproduce
Just compile IPlugEffect app and drag resize handle.
SigAbrt in IGraphicsCairo.cpp, UpdateCairoContext() => cairo_destroy(mContext);
 
Expected behaviour
No crash. 

Screenshots
na

IMPORTANT DETAILS
No crash under Windows 10

Additional context
na

**Comment by olilarkin** [comment]
duplicate of https://github.com/iPlug2/iPlug2/issues/245

**Comment by TBProAudio** [comment]
Sorry, just saw it :-(
