### ISSUE TITLE
Cursor locking failing in out-of-process AUv2/AUv3 on macOS Big Sur in Logic/GB

### ISSUE THREAD

**Issue by TBProAudio** [iPlug2/iPlug2#669]
**Describe the bug**
OnMouseDrag is called but dx/dy values seem to be wrong. So knobs do not really react on MouseDrag. 
MouseWheel/Down/Up work as expected.
(Due to still missing debug capabilities no further information on this)

**To Reproduce**
IPlugControls
ARM AU compile
Host Logic Pro X ARM

**Expected behaviour**
Normal OnMouseDrag behaviour.

**Screenshots**
NA

**IMPORTANT DETAILS**
Big Sur M1 11.1
AU ARM
Logic Pro X ARM latest

**Additional context**
ARM Standalone/VST2/VST3 work as expected
Reaper (ARM), AU (ARM) works as expected

**Comment by olilarkin** [comment]
I have seen this too

**Comment by olilarkin** [comment]
It seems this is todo with the code in IGraphicsMac::RepositionCursor(). If you disable hide cursor on drag in e.g. IKnobControlBase there is no problem

**Comment by TBProAudio** [comment]
Great, will check

**Comment by TBProAudio** [comment]
Works!!
Thank you so much.

**Comment by olilarkin** [comment]
disabling hiding? hopefully i can find a way to allow cursor hiding

**Comment by TBProAudio** [comment]
Yes, "mHideCursorOnDrag = false; " works as intended. I wrapped it with "#if defined(__arm64__)".
 
For me this solution is OK, thank you

**Comment by olilarkin** [comment]
Cursor locking disabled for -out-of-process AUv2s in LogicX/Garageband here

https://github.com/iPlug2/iPlug2/commit/7a422239a98b0a1020309b16c326f60b9eb02f82

They are only currently loaded out of process on Apple Silicon. May need another fix for AUv3. Will keep #566 open for that
