### ISSUE TITLE
WebView doesn't initialize with dimensions set in config.h

### ISSUE THREAD

**Issue by mazbox** [iPlug2/iPlug2#672]
This is on mac, running as macOS-APP - it looks like OpenWebView is being called with w and h = 600 - the window is the correct size but the webview is still 600x600.

I am able to force it by calling resize in the mEditorInitFunc, and that will scale the webview to the right size.

**Comment by mazbox** [comment]
Just as an addendum, IPlugWebUI *almost* works as mac vst3 out of the box, it just needs the web folder added to the "Copy Bundle Resources" build phase. It's amazing it works, hats off!

**Comment by olilarkin** [comment]
Cool, I’ll have a look. Great to have someone else looking at this code. By the way I would love to improve this example, and make it look a bit nicer if you have suggestions/code you’d like to contribute
