### ISSUE TITLE
WebView SAMFUI data

### ISSUE THREAD

**Issue by mazbox** [iPlug2/iPlug2#673]
When calling SAMFUI from javascript, IPlugWebViewEditorDelegate ignores the incoming data.

`      SendArbitraryMsgFromUI(json["msgTag"], json["ctrlTag"], json["dataSize"], /*dataSize > 0 ? json["data"] :*/ nullptr);
`

I'm wondering if this is because there's no nice + simple way to transfer things like structs between js and C++. Can I propose that it just passes a string to be parsed by the client code? (and just ignore the dataSize) - in terms of efficiency, it's going to need to be parsed anyway.

e.g. something like this: 
```
		const char *data = nullptr;
		int size = 0;
		std::string dataStr;
		if(json.count("data")>0 && json["data"].is_string()) {
			dataStr = json["data"].get<std::string>();
			size = dataStr.size();
			data = dataStr.c_str();
		}
		SendArbitraryMsgFromUI(json["msgTag"], json["ctrlTag"], size, data);
```

**Comment by olilarkin** [comment]
need to think more about this but i merged this for now

https://github.com/iPlug2/iPlug2/commit/fc2d99e700999f7862d9a763aad978a118cdb86d

**Comment by olilarkin** [comment]
I have encoded opaque data as base64 strings when going the other way.

**Comment by mazbox** [comment]
I found this: https://github.com/firejune/struct.js?files=1 - looks like a simple(ish) way to make binary structs in javascript, not the simplest solution, but going in the right direction maybe?

**Comment by mazbox** [comment]
Ok, messing about with it today, it's probably better to stick to binary data rather than strings, because it allows more flexibility - if that's the case, here's a version of the same code that assumes the "data" parameter to be base64 encoded: 

```C++

int size = 0;
WDL_TypedBuf<unsigned char> data;
		
if(json.count("data")>0 && json["data"].is_string()) {
			
	auto dStr = json["data"].get<std::string>();
	int dSize = dStr.size();
			
	// calculate the exact size of the decoded b64 data
	int numPaddingBytes = 0;
			
	if(dSize>=2 && dStr[dSize-2]=='=') {
		numPaddingBytes = 2;
	} else if(dSize>=1 && dStr[dSize-1]=='=') {
		numPaddingBytes = 1;
	}
			
	size = (dSize*3)/4 - numPaddingBytes;
	data.Resize(size);
	wdl_base64decode(dStr.c_str(), data.GetFast(), size);
}
		
SendArbitraryMsgFromUI(json["msgTag"], json["ctrlTag"], size, data.GetFast());
```

Please let me know if you want me to make a pull request of that.

Some helper functions I made in javascript are: 
```javascript
function B64toUint8Array(b64str) {
	return Uint8Array.from(window.atob(b64str), c => c.charCodeAt(0))
}

function B64ToInt32Array(b64str) {
	return new Int32Array(B64toUint8Array(b64str).buffer);
}

function Int32ArrayToB64(i32Array) {
	let uint8 = new Uint8Array(i32Array.buffer);

	var bin = String.fromCharCode.apply(null, uint8);
	return window.btoa(bin);
}
```

**Comment by olilarkin** [comment]
Done some work on this here https://github.com/iPlug2/iPlug2/commit/7a149961c32cdbd0398b04c0abe817fd1fe4e9eb

I wonder if the amount of heap allocations for these potentially large strings is problematic

**Comment by mazbox** [comment]
I agree - perhaps a way round it is to have some sort of lazy allocation
scheme - so for instance the WebViewEditorDelegate class has a persistent
working buffer for these things, and reallocates only if the buffer is too
small for the incoming data, and maybe there could be a way to declare how
much space should be in there upfront? e.g. instead of the SetMaxJSStringLength
just storing the desired max length, you could actually allocate the memory
too? I appreciate that there are going to be some use cases where this
wouldn't be optimal, but probably the biggest problem at the moment is if
you pass more data than mMaxJSStringLength the code just fails quietly due
to a malformed javascript string (as it gets cut off before the string is
correctly terminated with the ")
