### ISSUE TITLE
Trying to build the examples

### ISSUE THREAD

**Issue by tremblap** [iPlug2/iPlug2#676]
Hello

I'm trying to build a single example on Mac: the MacOS-AUv3 Framework (any of the AU as I don't want to download anything else than the iPlug2 framework) and I get this error:

Lexical or Preprocessor Issue Group
/IGraphics/IGraphicsPrivate.h:32:12: 'SkSVGDOM.h' file not found
/Volumes/machins/essai_cpp/iPlug2/IGraphics/IControl.cpp:16:10: In file included from /Volumes/machins/essai_cpp/iPlug2/IGraphics/IControl.cpp:16:
/IGraphics/IControl.h:35:10: In file included from ../../../IGraphics/IControl.h:35:
/IGraphics/IGraphics.h:48:10: In file included from ../../../IGraphics/IGraphics.h:48:
/IGraphics/IGraphicsStructs.h:27:10: In file included from ../../../IGraphics/IGraphicsStructs.h:27:

I tried to change to IGRAPHICS_NANOVG but I got other errors...

The macOS-AUv2 builds (but not v3 nor framework which require a dev account it seems)

**Comment by olilarkin** [comment]
AUv3 on macOS is not yet working, stick to AUv2 :-)

**Comment by tremblap** [comment]
Will do. iPlugEffect works with AUv2, but not the surround example. I'll try to find the issue but SkSVGDOM.h is not there it seems. I presume that if I manage to remove igraphics altogether I won't have that problem :)

**Comment by olilarkin** [comment]
Oh I’ll fix that

**Comment by tremblap** [comment]
Update: the visual library is definitely what is different here: IGRAPHICS_NANOVG for the surround example gives me Ld failed with nonzero exit code, quite exotic ;)

**Comment by olilarkin** [comment]
SurroundEffect was using skia, which you need to [download some extras for](https://github.com/iPlug2/iPlug2/tree/master/Dependencies)

git pull

https://github.com/iPlug2/iPlug2/commit/ee127460209f9aeb7ffd919d98821ab35be986a6

**Comment by tremblap** [comment]
I saw the dependencies indeed but tried to keep it lean (and the text made it feel like it was optional for fancy stuff - all I want is a no-gui example to get going with the dsp and ugly interface first - actually I have a tune in progress and I need to re-code something I had in SonicBirth which moving to ()$#*)$(@*$)@# catalina broke)

**Comment by olilarkin** [comment]
you can remove the #if IPLUG_EDITOR block, and set PLUG_HAS_UI to 0 in
config.h

**Comment by tremblap** [comment]
Thanks for the fix (which worked) and the for hint (which is next on the test list :)
