### ISSUE TITLE
VST3 not building correctly

### ISSUE THREAD

**Issue by aponplugins** [iPlug2/iPlug2#677]
**Issue**
Using the Windows guide, (https://github.com/iPlug2/iPlug2/wiki/02_Getting_started_windows), VST3 is built successfully but will not run. Ableton cannot find the example plugin and the debugger from JUCE claims to be unable to load the device.

**To Reproduce**
Follow the guide and build the IPlugInstrument example with no changes.

**Comment by olilarkin** [comment]
It’s working here on several systems. Please provide more details. Does the
app work?

**Comment by aponplugins** [comment]
Yes the app builds fine. I am using Visual Studio 2019, git 2.30.0.windows.1, and installed the VST SDK information with the python scripts included, as directed in the guide. I then built the VST3, and the build log in Visual Studio gives no errors or warnings. I directed Ableton to look for the plugin where the build log indicated (iPlug2\Examples\IPlugInstrument\build-win\). Upon scanning, no new plugins are found. In the JUCE audio debugger, the same folder is scanned, and the error message reads: "Note that the following files appeared to be plugin files, but failed to load correctly."

Thanks for the help.

**Comment by olilarkin** [comment]
Have you built 64-bit versions/are you trying in 64-bit hosts?￼

**Comment by aponplugins** [comment]
I scanned both 32 and 64 bit versions

**Comment by aponplugins** [comment]
Scratch that, looks like I haven't built a 64-bit version. How do I do so?

**Comment by olilarkin** [comment]
![image](https://user-images.githubusercontent.com/655662/103958836-f6320a80-5145-11eb-8db9-5ea9c9040527.png)

**Comment by aponplugins** [comment]
Awesome, works fine now! Thanks a ton for the help.

**Comment by olilarkin** [comment]
maybe i need to make that clearer in the wiki

**Comment by aponplugins** [comment]
Might as well, it's a simple fix

**Comment by olilarkin** [comment]
i did mention it, but i'll put it in bold

Now select "x64" from the "Solution Platforms" menu (instead of Win32) in order to build for the x64 architecture

**Comment by aponplugins** [comment]
Oh okay, I see it there now, I must've missed it. I wouldn't change it then, that's just my mistake. Sorry about that!
