### ISSUE TITLE
Context menu appears in wrong location when display is scaled.

### ISSUE THREAD

**Issue by Plygon** [iPlug2/iPlug2#679]
**Describe the bug**
When the Windows display is scaled, context menus incorrectly appear where they would if the display wasn't scaled.

**To Reproduce**
1. Build the vst3 version of a plugin (I used the example "IPlugEffect")
2. Go into Windows 10 display settings and set "Change the size of text, apps, and other items" to 150% or higher.
3. Load plugin in DAW (I've only tested with FL Studio)
4. Right click on a control. See that the context menu is in the wrong location.

**Expected behaviour**
The top left corner of FL Studio's context menu should line up with the pointer.

**Screenshots**
<img width="238" alt="Screenshot 2021-01-11 203652" src="https://user-images.githubusercontent.com/22244974/104258046-c6884880-544c-11eb-80b1-391a4c333dc0.png">

<img width="605" alt="129" src="https://user-images.githubusercontent.com/22244974/104192774-4b437a00-53ed-11eb-820f-eba733802056.png">
Because of Windows display scaling, the plugin is 1200 pixels wide - double what it normally is. Right-clicking the button 600 pixels from the left side causes the context menu to appear 300 pixels from the left side, rather than 600.

**IMPORTANT DETAILS**
* Observed on VST3
* Windows 10
* FL Studio
* IGRAPHICS_BACKEND: ALL

**Comment by olilarkin** [comment]
Thanks. We have to do some work to support windows scaling at settings such as 150%. right now the UI size is getting quantised to 100% or 200% scaling

**Comment by olilarkin** [comment]
could you try this branch and see if it fixes the issue? https://github.com/iPlug2/iPlug2/tree/graphics/floatscreenscale

**Comment by Plygon** [comment]
Thanks!
It now scales correctly - even handles switching between two monitors with different scales! But the problem of the context menu in the incorrect position is still here. The top left corner of the menu should be right where the mouse is when I click, but it's too far left and up.

(I couldn't get the example plugin to load for some reason, so this is the one I'm working on)

![context menu](https://user-images.githubusercontent.com/22244974/104531303-e26e2480-55db-11eb-85b8-aba0af40ea09.gif)

(and here it is working as expected with 100% scaling)

![context menu](https://user-images.githubusercontent.com/22244974/104531497-45f85200-55dc-11eb-9d8c-14acdcd58a66.gif)

**Comment by Plygon** [comment]
I found a simple fix for my case.
IGraphics.cpp line 999 has:
`PopupHostContextMenuForParam(pCapturedControl, paramIdx, x, y);`

I replaced it with:
`PopupHostContextMenuForParam(pCapturedControl, paramIdx, x * GetTotalScale(), y * GetTotalScale());`

**Comment by olilarkin** [comment]
cool i am going to check this

**Comment by Plygon** [comment]
Scratch that - the scale from the corner resizer was already taken into consideration. It should be
`PopupHostContextMenuForParam(pCapturedControl, paramIdx, x * mScreenScale, y * mScreenScale);`

**Comment by olilarkin** [comment]
Think this should fix that https://github.com/iPlug2/iPlug2/pull/680/commits/f79b6e7accd8c34b34f944460a32375f65a0d9a5

**Comment by Plygon** [comment]
That did the trick, thank you!

**Comment by AlexHarker** [comment]
Is this issue now fixed? Can this be closed?

**Comment by olilarkin** [comment]
I just tested VST3 in latest FLStudio with 150% scaling and the context
menu is always in the correct place

**Comment by AlexHarker** [comment]
Closing based on @olilarkin's response above.
