### ISSUE TITLE
IPlugResponsiveUI Heap Corruption

### ISSUE THREAD

**Issue by alechk4** [iPlug2/iPlug2#681]
**Output**
```Debug Error!

Program: ...lugResponsiveUI\build-win\app\x64\Debug\IPlugResponsiveUI.exe

HEAP CORRUPTION DETECTED: before Normal block (#723) at 0x0000025FD6431C60.
CRT detected that the application wrote to memory before start of heap buffer.


(Press Retry to debug the application)
Assertion failed!

Program: ...veUI\build-win\app\x64\Debug\IPlugResponsiveUI.exe
File: D:\Users\Alechk4\Documents\JUCE\iPl...\IGraphi...ate.cpp
Line: 90

Expression: pControl

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)Assertion failed!

Program: ...veUI\build-win\app\x64\Debug\IPlugResponsiveUI.exe
File: D:\Users\Alechk4\Documents\JUCE\iPl...\IGraphi...ate.cpp
Line: 90

Expression: pControl
[...]
```

**To Reproduce**
- Build Examples/IPlugResponsiveUI.cpp with Visual Studio 2019
- Resize the window horizontally multiple times.
- (Possibly unrelated) Sometimes the keyboard is drawn on top of the imgui widget, even though the clicks are captured correctly by imgui.
- Click on the X to exit
- Many error alerts will spawn, saying "(Press Retry to debug the application - JIT must be enabled)Assertion failed!"

**IMPORTANT DETAILS**
* What plug-in format does it relate to: APP and VST3
* What platform does it relate to: Windows
* What IGRAPHICS_BACKEND does it relate to: IGRAPHICS_NANOVG (default)

**Comment by olilarkin** [comment]
wasn't able to reproduce... what file at line 90 was pControl invalid?

**Comment by alechk4** [comment]
I had to guess because I can't expand the ellipses. The file must be IGraphicsEditorDelegate.cpp:
```C++
void IGEditorDelegate::SendControlMsgFromDelegate(int ctrlTag, int msgTag, int dataSize, const void* pData)
{
  if(!mGraphics)
    return;
  
  IControl* pControl = mGraphics->GetControlWithTag(ctrlTag);
  
  assert(pControl);
  
  if(pControl)
  {
    pControl->OnMsgFromDelegate(msgTag, dataSize, pData);
  }
}
```

**Comment by olilarkin** [comment]
Closed since I have removed IMGUI support

**Comment by mbwilding** [comment]
> 

Why was ImGui removed? Just started using IPlug2 and will be implementing ImGui myself.

**Comment by olilarkin** [comment]
> > 
> 
> 
> 
> Why was ImGui removed? Just started using IPlug2 and will be implementing ImGui myself.

I wasn't happy with how it was integrated, cluttering the IGraphics code. It would be better to do it in an IControl or if you want to do the whole UI with ImGui, use something like PUGL or GLFW on top of iPlug2
