### ISSUE TITLE
IGraphics::MouseUp crashes when IGraphics::Resize is called thereafter

### ISSUE THREAD

**Issue by gvampgh** [iPlug2/iPlug2#684]
ReleaseMouseCapture in IGraphics::Resize crashes in this constellation:

- MouseUp event of control triggered
- IGraphics::OnMouseUp iterates through mCapturedMap, calls OnMouseUp of control
- Overriden custom method resizes UI by calling IGraphics::Resize
- IGraphics::Resize calls ReleaseMouseCapture, empties current iterating mCaptureMap and so later crashes IGraphics::OnMouseUp

Fixed in own fork by removing ReleaseMouseCapture in IGraphics::Resize, but I'm not sure if this call is important for other things.

**Expected behaviour**
Resizing should be possible by a control mouse action.

* What plug-in format does it relate to - ALL
* What platform does it relate to - Windows/macOS

**Comment by AlexHarker** [comment]
I think a better fix would be to change the following line in OnMouseUp:

mCapturedMap.erase(itr);

to

mCapturedMap.erase(mod.touchID);

This second form or erase will first check if the key still exists. There is a similar approach in OnTouchCancelled(). We could also make a helper method for this to promote this approach, but that's perhaps not worth it for two calls.

@olilarkin - any thoughts here?
