### ISSUE TITLE
IKnob/SliderControlBase::OnMouseWheel rounding errors

### ISSUE THREAD

**Issue by gvampgh** [iPlug2/iPlug2#690]
Due to rounding errors, Knobs & sliders get stuck at some circumstances.

**To Reproduce**
Use IPlugExamples on Windows
Change first parameter to GetParam(kParamGain)->InitInt("Gain", 100, 1, 100, "%");
Move sliders or knobs with **mouse wheel** under 28% and then above again, it stucks at 28%
The value is v = 28.999999999999996 at this line:

```
      v += d > 0 ? step : -step;
      v = Clip(v, l, h);
      **v = v - std::fmod(v, step);**
      v -= l;
      v /= range;
```

**Expected behaviour**
Normal mouse wheel behaviour

**Screenshots**
![grafik](https://user-images.githubusercontent.com/48643530/106365387-92aa8f80-6335-11eb-90b2-a26d609c42cc.png)

**IMPORTANT DETAILS**
* What plug-in format does it relate to - ALL
* What platform does it relate to - Windows (at least)
* What IGRAPHICS_BACKEND does it relate to, ALL

**Comment by TBProAudio** [comment]
`v = v - std::fmod(v, step);` 
seems to be the problem.

```
#define __dround(x, n) (std::round((x) * pow(10.0, (n))) / pow(10.0, (n)))
v = __dround(v, log10(1.0 / step));  // step != 0
```
should do it better.

**Comment by gvampgh** [comment]
This looks a little bit overdosed to me. :-) Adding a quarter of the step size here fixed it at least for my own UI and IPlugExamples (on Windows). I'm still not sure if this works for all combinations/step sizes and min/max values. BTW, I recognized that at least the ISliderControlBase has the same problem/needs the same fix.

```
      const double step = pParam->GetStep();
      **v += pParam->GetStep() * 0.25;**
      v += d > 0 ? step : -step;
```
