### ISSUE TITLE
(winexport.def) VST3_SDK file missed at compilation - Adding the solution in the wiki

### ISSUE THREAD

**Issue by PudreteDiablo** [iPlug2/iPlug2#692]
I downloaded the latest version of VST3_SDK (February 06, 2021) from the official [developers page of steinberg](https://www.steinberg.net/en/company/developers.html). In the compilation with Visual Studio an error was found blocking the build of the vst ~> "Cannot read the file: iplug2\Dependencies\IPlug\VST3_SDK\public.sdk\source\main\winexport.def". For some reason, the original zip file provided by steinberg doesn't include that file, so I search it by myself and I found it in [this repository](https://git.kx.studio/falkTX/Carla/src/commit/6fa44324dde982e31fa54a9df0db675491de8c08/source/includes/vst3sdk/public.sdk/source/main)

The file only contains the next code:
```
EXPORTS
	GetPluginFactory
	InitDll
	ExitDll
```

I was thinking you could add this possible error with its solution on the wiki (Windows).

**Comment by olilarkin** [comment]
You might have an old version of iPlug2. This was fixed here

https://github.com/iPlug2/iPlug2/commit/d1cbb54c6a46ff4d2e9d6248587c4c938401b508
