### ISSUE TITLE
IPlugEffect vst3 not working on windows 10

### ISSUE THREAD

**Issue by ivanhuay** [iPlug2/iPlug2#694]
**Describe the bug**
IPlugEffect  vst3 doesn't load on Reaper after build.

platform: Windows 10, vst3 

**Screenshots**
![image](https://user-images.githubusercontent.com/5782286/108138600-1639df80-709d-11eb-8bfc-77d651e8177a.png)

**Additional context**
I tried changing the PLUG_CHANNEL_IO but it didn't work. 
IPlugSideChain works fine

**Comment by olilarkin** [comment]
The problem here is the plug-in ID stored in the .RPP file. If you re-insert the plug-in it should be OK

**Comment by ivanhuay** [comment]
@olilarkin Reaper doesn't read the plugin at all but it is on the right VST3 folder. I tried with the Re-Scan and clearing cache but it didn't work

**Comment by olilarkin** [comment]
It definitely works here. Are you sure you are building x64 version and trying in x64 reaper?

**Comment by intonarumori** [comment]
@olilarkin I'm experiencing the same error after following the wiki guide on duplicating IPlugEffect.
Reaper doesn't find my new duplicated VST3 but can load IPlugEffect fine. I'm looking for a difference in the source files/reaper template and cannot see anything. Any ideas?

**Comment by intonarumori** [comment]
>Any ideas?

I had to resave the Reaper file and it started working. Seems like a simple string replacement is not enough for Reaper when duplicating the example project. Maybe it generates some checksum based on the plugin name.
Hope this helps others.

**Comment by olilarkin** [comment]
Di you definitely build the x64 version? You could try changing PLUG_UNIQUE_ID in config.h manually to a new 4char value

**Comment by intonarumori** [comment]
@olilarkin The only think that worked was resaving the Reaper project. Changing the ID did not help.
I diffed the old and new Reaper files and the name and manufacturer IDs are identical, it's only the internal Reaper stuff that is changing. Again, maybe a checksum or something dependent on the name length etc.

Not sure where you could warn the user about this, maybe in the Wiki, not sure.
