### ISSUE TITLE
IShaderControl default SkSL shader not worked

### ISSUE THREAD

**Issue by SachiSakurane** [iPlug2/iPlug2#698]
**Describe the bug**
Failed to compile the shader, which is set by default in `IShaderControl`.

**To Reproduce**
I followed the wiki to set up macOS.

https://github.com/iPlug2/iPlug2/wiki/03_Switching_graphics
```
EXTRA_ALL_DEFS = OBJC_PREFIX=vIPlugEffect SWELL_APP_PREFIX=Swell_vIPlugEffect IGRAPHICS_SKIA IGRAPHICS_METAL
```

Attach control `IShaderControl` with same the parents control bounds.
```
pGraphics->AttachControl(new IShaderControl(b));
```

`SkRuntimeEffect::Make` fails to compile the shader, and the following text is passed as the return value to `errorText`.
https://github.com/iPlug2/iPlug2/blob/999d399d71c9b3b6481d102d9e0d9116fc8440e5/IGraphics/Controls/IShaderControl.h#L137
```
error: 7: 'main' must return: 'vec4', 'float4', or 'half4'
```

**Expected behaviour**
Set the default shader compilable.

**IMPORTANT DETAILS**
* What plug-in format does it relate to - ALL.
* What platform does it relate to - ALL.
* What IGRAPHICS_BACKEND does it relate to, IGRAPHICS_SKIA.

**Additional context**
It's hard to tell with alpha how well the shaders are working.
https://github.com/iPlug2/iPlug2/blob/999d399d71c9b3b6481d102d9e0d9116fc8440e5/IGraphics/Controls/IShaderControl.h#L78

**Comment by olilarkin** [comment]
thanks for the fix, merged
