### ISSUE TITLE
Xcode error : AAX unable to open file

### ISSUE THREAD

**Issue by jellohouse** [iPlug2/iPlug2#701]
When trying to build and run one of the example projects in Xcode on Mac I get the following error:

`...../iPlug2/Dependencies/IPlug/AAX_SDK/Libs/AAXLibrary/MacBuild/AAXLibrary_common_debug.xcconfig: unable to open file (in target "AAX" in project ...)`

Has anyone else encountered this error before? 
How can it be solved?

**Comment by olilarkin** [comment]
yes. It's because you don't have the AAX SDK installed. So you can't build the AAX target or the All target in the Xcode project. AAX SDK can be obtained here https://www.avid.com/alliance-partner-program/aax-connectivity-toolkit
