### ISSUE TITLE
Any MakeGraphics() scale factor other than 1.0 crashes Pro Tools

### ISSUE THREAD

**Issue by Fender19** [iPlug2/iPlug2#708]
MakeGraphics() works in VST, VST3 and AU formats with any scale size - rendering the plugin larger or smaller (per scale factor) on the screen.

This does not work in Pro Tools (AAX).  Any scale factor other than 1.0 crashes PT when attempting to launch the plugin.  Occurs in both Mac and Windows.  This likely means that GetScaleForScreen(PLUG_WIDTH, PLUG_HEIGHT) that returns anything other than 1.0 will fail as well.

Xcode debug shows the crash at "this->CreateViewContainer ();"  with bad access  

VS2019 debug shows the problem is in IPlugAAX::EditorResize(int viewWidth, int viewHeight):
`Exception thrown: read access violation.
pViewInterface->mAAXViewContainer was nullptr.;`

**Comment by AlexHarker** [comment]
Can you confirm the file? The line on it's own is not super clear. Even more useful (If you can provide it) would be a stack trace.

**Comment by TBProAudio** [comment]
maybe this helps:

```
bool IPlugAAX::EditorResize(int viewWidth, int viewHeight)
{
  if (HasUI())
  {
    IPlugAAXView_Interface* pViewInterface = (IPlugAAXView_Interface*) GetAAXViewInterface();
    AAX_Point oEffectViewSize;
      
    oEffectViewSize.horz = (float) viewWidth;
    oEffectViewSize.vert = (float) viewHeight;
    
    if (pViewInterface && (viewWidth != GetEditorWidth() || viewHeight != GetEditorHeight()))
    {
      if (pViewInterface->GetViewContainer()) // TBPROAUDIO 19102020, seems to crash if UI start with scaling != 1.0
      {
        pViewInterface->GetViewContainer()->SetViewSize(oEffectViewSize);
      }
    }

    SetEditorSize(viewWidth, viewHeight);
  }
  
  return true;
}
```

**Comment by Fender19** [comment]
Yes, that's the file and the problem area.  Either **pViewInterface** or **GetViewContainer()** is returning a null ptr for some reason.

**Comment by AlexHarker** [comment]
It looks like this code snippet is a fix because GetViewContainer() checked before the pointer is dereferenced. @TBProAudio - is that correct that you've fixed it? Can you also confirm that the interface then opens with the correct scaling?

I'd be inclined to accept a PR for this if submitted as the change seems pretty uncontroversial

**Comment by Fender19** [comment]
Yes!  I can confirm that this fixes it on Windows - will try Mac now but assume the best.

Thomas you have, once again, come to the rescue!  Much appreciated.

**Comment by olilarkin** [comment]
Added the fix on master
