### ISSUE TITLE
Adding img resources to Targets creates duplicate copies in build component package

### ISSUE THREAD

**Issue by Fender19** [iPlug2/iPlug2#709]
According to iPlug2 instructions - and how it worked in iPlug1 - all of the PNG image files in the Resource/img folder in the Xcode project need to be attached to the associated project Targets by checking the Targets boxes.

I have have discovered that doing that creates a duplicate set of PNG files in the builds - one directly under the Resources folder and another set in a "img" subfolder within the resources folder.  This can make the built plugin file nearly twice the necessary size.  Not sure what, if any, side affects can occur as a result of two copies in two places.

What's more disturbing, is that I have found we don't _need_ to check the target boxes.  All of the PNG files listed in the project IMG folder get copied to the build folder regardless of Targets not set - and the plugin works.  

So not selecting something is including it anyway and selecting it includes it twice.

Not sure if this is known issue but I don't see it discussed anywhere on the forum.

**Comment by olilarkin** [comment]
Which instructions? They may be out of date. ￼

**Comment by olilarkin** [comment]
As I mentioned elsewhere, the "prepare_resources-mac.py" python script copies in resources in Resources/img etc. 

Here are the current "instructions" for adding a resource

https://github.com/iPlug2/iPlug2/wiki/06_Load_a_resource

**Comment by Fender19** [comment]
OK, I must be mistaken then - but that is different from iPlug1 which required the Targets to be selected.

BTW - the current instructions you linked are also not correct as there is no "Compile-time directives" box at the bottom - or anywhere else - in my main.rc file.  I have added the references to the #ifndef APSTUDIO_INVOKED section and it works.

That section also says "Generated from the TEXTINCLUDE 3 resource." but nothing ever gets "generated" here, AFAIK.

**Comment by olilarkin** [comment]
it's referring to the dialog box in visual studio not the .rc file itself. Closing this, but if you see there are some out of date instructions, we'll remove/update them

**Comment by Fender19** [comment]
*>>select "View" -> "Resource View"*

I was meaning to ask about this also - there is no "Resources View" dialog
box in my Xcode menu.  Where are you viewing this dialog box?

[image: Screen Shot 2021-03-21 at 11.50.42 AM.png]


*Jeff Rippe*


*Chief EngineerRaising Jake Studios*

*Los Angeles, CA  USA*
*www.raisingjakestudios.com <http://www.raisingjakestudios.com>*

**Comment by olilarkin** [comment]
that is about Visual studio. i updated the indentation on the page to make it clearer

**Comment by Fender19** [comment]
Not sure you saw my previous email - there is no "Resources View" dialog
box in my Xcode menu under File->

Where are you pulling up that menu?

[image: Screen Shot 2021-03-21 at 11.50.42 AM.png]

*Jeff Rippe*


*Chief EngineerRaising Jake Studios*

*Los Angeles, CA  USA*
*www.raisingjakestudios.com <http://www.raisingjakestudios.com>*

**Comment by olilarkin** [comment]
As I said previously that text is referring to Visual Studio
