### ISSUE TITLE
Self managed host bypass

### ISSUE THREAD

**Issue by pthvogt** [iPlug2/iPlug2#714]
iPlug2 manages the host bypass by itself, preventing `ProcessBlock()` to be called.

Sometime one wants to mange the bypass by oneself, e.g. to support a click free bypass or to update some GUI elements like a spectroscope.

Therefore we should enable the iPlug2 user to specify that `ProcessBlock()` should be called, regardless of the `GetPypassed()` state. If enabled `ProcessBlock()` has to call `GetBypassed()` and provide some code to bypass the processing.

PR for this will follow!

**Comment by TBProAudio** [comment]
excellent idea:

Following functions are required in IPlugProcessor.h:
 ```
void SetCanHandleByPass(bool state) { bcanhandlebypass = state; }     
bool GetCanHandleByPass(void) { return bcanhandlebypass; }            
```
e.g. VST2 needs to be modified like this:

```
void VSTCALLBACK IPlugVST2::VSTProcessDoubleReplacing(AEffect* pEffect, double** inputs, double** outputs, VstInt32 nFrames)
{
  TRACE
  IPlugVST2* _this = (IPlugVST2*) pEffect->object;
  _this->VSTPreProcess(inputs, outputs, nFrames);
  if (_this->GetBypassed() && !_this->GetCanHandleByPass())               
  {
    _this->PassThroughBuffers((double)0.0, nFrames);  // double precision
  }
  else
  {
    ENTER_PARAMS_MUTEX_STATIC
      _this->ProcessBuffers((double)0.0, nFrames);
    LEAVE_PARAMS_MUTEX_STATIC
      _this->OutputSysexFromEditor();
  }
}

```
Needs to be done for VST3/AU/AAX in a very similar way ...

Also "effCanDo" and "effSetBypass" needs to be modified for VST2.

**Comment by pthvogt** [comment]
I've found the GetBypased()-logic only in VST3 and AU, therefore my PR only addresses these two places.

**Comment by pthvogt** [comment]
I searched again through the source: Only AUv2 and VST2 sets the bypass flag, therefore I think we don't need to add this logic to other interfaces.

**Comment by TBProAudio** [comment]
I looked through all formats, the following logic is always required:

```
if (_this->GetBypassed() && !_this->GetCanHandleByPass())               
  {
 //... passthrough
 }
  else
  {
// ... process
  }
```
If it finally works depends on the DAW. 
e.g. Reaper ignores everything and does its own bypass ...

**Comment by olilarkin** [comment]
Thanks for the contribution. I feel that this is something that individuals can add if they need it. I'd rather not complicate the base classes so i'm going to chose not to make this design choice
