### ISSUE TITLE
Improve SVG support

### ISSUE THREAD

**Issue by AlexHarker** [iPlug2/iPlug2#73]
Doesn't read gradient colours for radial gradients correctly
Doesn't appear to represent fill-opacity anywhere

**Comment by olilarkin** [comment]
options include

RESVG, a rust library, that supports SVG text, with cairo/skia backends: https://github.com/iPlug2/iPlug2/tree/graphics/resvg

Use Skia's SVG functionality: 
https://github.com/iPlug2/iPlug2/tree/graphics/skiasvg

**Comment by olilarkin** [comment]
Skia backend will now use Skia's SVG code. It doesn't do text like RESVG but it seems to handle a lot more svgs than nanosvg
