### ISSUE TITLE
SetLatency() in VST3 fails in Ableton Live 10 - suggested fix

### ISSUE THREAD

**Issue by Fender19** [iPlug2/iPlug2#731]
Issue discovered in Ableton Live with VST3 version: plugin fails on loading due to issue with SetLatency().

I checked iPlug1 SetLatency() and found it included a check for null ptr.  I added the check to IPlug2 IPlugVST3::SetLatency(int latency) and it fixed it.

IPlugVST3.cpp - CURRENTLY in iPLUG2:
```
void IPlugVST3::SetLatency(int latency)
{
  IPlugProcessor::SetLatency(latency);

  FUnknownPtr<IComponentHandler>handler(componentHandler);
  handler->restartComponent(kLatencyChanged);
}
```

IPlugVST3.cpp - SUGGESTED FIX:
```
void IPlugVST3::SetLatency(int latency)
{
  IPlugProcessor::SetLatency(latency);

  FUnknownPtr<IComponentHandler>handler(componentHandler);
  if (handler != nullptr)//add
  {                      //add
      handler->restartComponent(kLatencyChanged);
  }                      //add
}
```

**Comment by TBProAudio** [comment]
There much more DAWs having problems with VST3 latency settings.
This why we
1) always `#define PLUG_LATENCY 0` in config.h and do the latency setting later
2) check componentHandler as well, as this could be also invalid:

```
void IPlugVST3::SetLatency(int latency)
{
  if (componentHandler != nullptr)                                // Check
  {
    FUnknownPtr<IComponentHandler>handler(componentHandler);
    if (handler != nullptr)                                               // Check
    {
      IPlugProcessor::SetLatency(latency);                       // Set IPlugBase here only, otherwise out of sync
      handler->restartComponent(kLatencyChanged);
    }
  }
}
```

**Comment by Fender19** [comment]
TBPro - your code takes the suggested "fix" one step further (and better than what I proposed).  Currently there is no check for handler in the IPlugVST3.cpp function for SetLatency().

**Comment by olilarkin** [comment]
merged
