### ISSUE TITLE
Window goes into resize loop when dragged across monitors in Windows

### ISSUE THREAD

**Issue by sstillwell** [iPlug2/iPlug2#734]
**CHECK**
Done

**Describe the bug**
When dragging a plugin window across monitors in REAPER, plugin window can go into a resize loop growing to enormous size

**To Reproduce**
Steps to reproduce the behaviour.
Configure a Windows system with multiple monitors, where at least one is HiDPI and another is standard DPI.  Drag plugin slowly across the border between those two monitors.  When the center point of the window crosses the boundary, a resize is triggered, which can move the center point back to the original monitor, which triggers a resize again...this can end up looping ad nauseam.

**Expected behaviour**
Plugin window should only resize once when dragged across monitor boundaries, regardless of that monitor's HiDPI status.

**Screenshots**

**IMPORTANT DETAILS**
* What plug-in format does it relate to - VST2, VST3, AUv2, AUv3, AAX, APP or ALL? - ALL
* What platform does it relate to - Windows/macOS/iOS/Linux or ALL? - Windows
* What IGRAPHICS_BACKEND does it relate to, IGRAPHICS_NANOVG, IGRAPHICS_SKIA or ALL? - Tested with SKIA, unknown for other backends.

**Additional context**

Will supply PR to work around per Justin Frankel of Cockos, Inc. (Author of REAPER)

**Comment by olilarkin** [comment]
fix merged in bb88892c81c0f03d36086c6ef7b6e2af2a854a01, untested
