### ISSUE TITLE
VST3 buses labelled incorrectly in Reaper (IPlugSideChain example)

### ISSUE THREAD

**Issue by Fender19** [iPlug2/iPlug2#736]
Sidechaining works nicely in iPlug2 - except there seems to be a bug causing the bus labels to be named incorrectly in VST2 and VST3 versions.

As an example, The IPlugSideChain example project in Reaper:

-     In the VST3 version the all input pins (including main inputs L/R) are labeled "Aux". 
-     In the VST2 version the opposite happens - all input pins (including sidechain/aux)  are labeled "input".

Pin labeling in IPlugProcessor.cpp "GetBusName()" appears correct - but it doesn't seem to be enacted - something else is re-labeling/overriding the input pin labels.  I've searched through the code but do not see the cause/fix.

![IPlugSideChain VST2](https://user-images.githubusercontent.com/45048592/116629541-5079f580-a906-11eb-9267-2e1336b0dd7a.png)
![IPlugSideChain VST3](https://user-images.githubusercontent.com/45048592/116629554-54a61300-a906-11eb-8b10-247a47c0bbfb.png)

**Comment by AlexHarker** [comment]
The input labels in VST2 look to be hard coded (see case effGetInputProperties:) - it looks like this should be calling through to GetBusName(). VST3 is less clear, as the VST3 processor base does call through to GetBusName().

**Comment by AlexHarker** [comment]
Sorry - VST2 will call through to GetChannelLabel() if present and fallback to "Input %d" - so there's something to investigate there. Only VST2 using the channel label, so perhaps this is now out of date, or needs combining with the bus name?

**Comment by Fender19** [comment]
I'm afraid I cannot offer a solution as I don't understand the cause.  In the meantime I tried to override the bus names using GetBusName() as shown in the example project:

```
void IPlugSideChain::GetBusName(ERoute direction, int busIdx, int nBuses, WDL_String& str) const
{
  **//could customize bus names here**
  IPlugProcessor::GetBusName(direction, busIdx, nBuses, str);
}
```

I loaded a WDL_String str("Test") into the above but it had no effect.   Running that still showed buses labeled as I posted above, i.e., it had no effect.

The audio works fine - which is my main concern - but the pin labels could be confusing for some users.

**Comment by olilarkin** [comment]
VST3 issue seems to be a bug with Reaper. In VST3PluginTestHost the label is OK

**Comment by olilarkin** [comment]
In VST2 you need to set the channel labels

https://github.com/iPlug2/iPlug2/commit/0e9691ebe58506aabe48d3ece63e4cbd08b2316d

**Comment by AlexHarker** [comment]
It seems odd to me that channel labels and bus labels exist - do they do different things or could they be combined into one thing?

**Comment by Fender19** [comment]
> 
> 
> In VST2 you need to set the channel labels
> 
> [0e9691e](https://github.com/iPlug2/iPlug2/commit/0e9691ebe58506aabe48d3ece63e4cbd08b2316d)

OK, thank you for that info (please consider adding it to the iPlugSideChain example) however conditional code kinda defeats the purpose of a framework, i.e., all versions should match automatically from IPlugProcessor.cpp, IMO.  Perhaps something in iPlugVST.cpp and iPlugVST3.cpp could be tweaked to do this?

> 
> 
> VST3 issue seems to be a bug with Reaper. In VST3PluginTestHost the label is OK

In Mixbus 6 all 4 inputs of VST2 version show up as "Audio In".  In Cakewalk all 4 inputs on both VST and VST3 versions main inputs show up as "input 1" and sidechain shows up as "input 2".  So it seems the DAWs themselves rename these pins.

**Comment by olilarkin** [comment]
> It seems odd to me that channel labels and bus labels exist - do they do different things or could they be combined into one thing?

They do different things. e.g. a first order ambisonic plugin might have 1 bus with channels labelled WXYZ. Its only going to work for VST2 though.

Please contact the DAW manufacturers if it bothers you

**Comment by olilarkin** [comment]
It was an iPlug2 issue w.r.t. VST3 labelling in Reaper, 919305b fixes is

**Comment by Fender19** [comment]
> Please contact the DAW manufacturers if it bothers you.

That's kind of a snide thing to say.  I'm simply trying to make plugins that work properly for people and help improve iPlug2 **_if possible_** by reporting it here.
