### ISSUE TITLE
Allow UIs to be drawn only at strict @1x and @2x sizes, to maximize sharpness

### ISSUE THREAD

**Issue by sstillwell** [iPlug2/iPlug2#741]
It would be nice if IGraphics' previous behavior could be conditionally used, allowing it to choose between @1x and @2x screen sizes based on HiDPI screen scaling (below 150% use @1x, above 150% use @2x) - for bitmap based UIs this will maximize sharpness.

I propose a change (PR to come) allowing you to define IGRAPHICS_QUANTISE_SCREENSCALE to enable previous behavior.  Absence of this new value will continue to work as current master code is defined (scales UI to match screen scale)

**Comment by olilarkin** [comment]
added in 7128892b43d2c77939869366651ad78ca15b0bc4
