### ISSUE TITLE
Mouse mod.A not working in Pro Tools/AAX

### ISSUE THREAD

**Issue by rexmartin158** [iPlug2/iPlug2#744]
**Describe the bug**
Mouse mod.A is not working in Pro Tools (AAX) - should reset a control to its default value but does not.

**To Reproduce**
Hold down Alt key and click on any rotary or slider control.  

**Expected behaviour**
Control should reset to default value but does not.

**IMPORTANT DETAILS**
Occurs on both Mac and Windows.  Debugger shows IControl OnMouseDown() is never called when Alt key is held down so code below has no effect:

`void IControl::OnMouseDown(float x, float y, const IMouseMod& mod)
{
  #ifdef PROTOOLS
  if (mod.A)
  {
    SetValueToDefault(GetValIdxForPos(x, y));
  }
  #endif
`

Changing mod.A above to mod.C or mod.S does work so this appears to be some sort of conflict with mod.A and Pro Tools.

**Additional context**
IPlugEffect exhibits same mis-behavior in Pro Tools - gain knob ignores mod.A + Click - but does reset with double click which is non-standard for AAX

**Comment by rexmartin158** [comment]
The problem seems to be in IPlugAAX::UpdateParameterNormalizedValue().   The code updates the parameter value to the correct default value but the control is not redrawn.  This  creates a serious UI problem where the control doesn't match the actual working parameters.

it looks like this code on line 249 of IPlugAAX.cpp should be updating the control
`  // Now the control has changed
  result = mPacketDispatcher.SetDirty(paramID);
`
but tracing SetDirty() to AAX_CPacketDispatcher.h in VS 2019 shows "function definition for SetDirty not found" which likely explains why the control doesn't get updated.  

So is something missing from the 2.3.2 AAX SDK - or maybe it doesn't work right when updated/converted to v142 toolset - or something else entirely?

**Comment by olilarkin** [comment]
Thanks for the report. Please pull the master branch, it should be fixed

**Comment by rexmartin158** [comment]
> 
> 
> Please pull the master branch, it should be fixed

Yes, it works!  Thank you.
