### ISSUE TITLE
Stepped parameter buggy due to PR #720

### ISSUE THREAD

**Issue by pthvogt** [iPlug2/iPlug2#759]
In `IKnobControlBase::OnMouseWheel()` and `ISliderControlBase::OnMouseWheel()` the difference d is applied twice (in different amounts).

Reason:

In both methods there exists an extra if-block for the stepped case. In the old code (before #720) the value of the parameter was fetched again at the begin of the if-block, in the new implementation we just use the already altered value.

In both if-blocks the line
`v = pParam->FromNormalized(v);`
should be changed to
`v = pParam->FromNormalized(GetValue());`

**Comment by AlexHarker** [comment]
Yes - I see the issue - I missed that step when looking at this. Can you make a PR? Your fix is probably the easiest way to go.

**Comment by pthvogt** [comment]
PR #761
