### ISSUE TITLE
SKIA CPU: More bitmaps = lower frame rate, even though amount of drawing unchanged

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#768]
This is an odd one.

Testing [this](https://github.com/Snipet/SK100) open source iPlug2 plugin, I found a very low framerate (testing with SKIA CPU on macOS). 

It uses lots of different PNG image strips, one for each knob. Strangely if I set all knobs to use the same png, the framerate is OK.

**Comment by AlexHarker** [comment]
The VU meter png is relatively big - could that be relevant?

**Comment by olilarkin** [comment]
No, my tests involved removing all bitmaps except the background and the knob/s

**Comment by olilarkin** [comment]
fixed in 8dd3f1e
