### ISSUE TITLE
Building IPlugEffect example VST3 distributed target is not working (MacOS) 

### ISSUE THREAD

**Issue by madronalabs** [iPlug2/iPlug2#770]
**To Reproduce**
- clone iPlug2
- open XCode project
- choose MacOS-VST3 (Distributed) target or VST3 Controller Library target

I get the following compile error:
```
In file included from /Users/randy/dev/iPlug2/Examples/IPlugEffect/IPlugEffect.cpp:2:
/Users/randy/dev/iPlug2/IPlug/IPlug_include_in_plug_src.h:321:60: error: unknown type name 'VST3Controller'
  return static_cast<Steinberg::Vst::IEditController*>(new PLUG_CLASS_NAME(info));
                                                           ^
```

I've only tried this on MacOS.

The MacOS-VST3 target is working.

**Comment by olilarkin** [comment]
Hi Randy, see the note about changing "IPlugEffect" class name to PLUG_CLASS_NAME, here https://github.com/iPlug2/iPlug2/wiki/Distributed-Plugins

**Comment by madronalabs** [comment]
Thanks for your help. I have this working now and the link you provided made it clear. 

You left a comment by the error but I could not figure out what it meant:

```
  //If you are trying to build a distributed VST3 plug-in and you hit an error here "no matching constructor...",
  //you need to replace all instances of PLUG_CLASS_NAME in your plug-in class, with the macro PLUG_CLASS_NAME
```

First, my error was not "no matching constructor" so I wasn't sure if the comment applied. 
Second, you have " replace all instances of PLUG_CLASS_NAME " and there were none. 

Possibly something like the following could help you avoid answering this newbie question in the future:

```
  // If you are trying to build a distributed VST3 plug-in and you hit an error here like "no matching constructor..." or 
  // "error: unknown type name 'VST3Controller'", you need to replace all instances of the name of your plug-in class
  //  with the macro PLUG_CLASS_NAME.
```
