### ISSUE TITLE
SetParameterValue() appears it should update host - but does not

### ISSUE THREAD

**Issue by rexmartin158** [iPlug2/iPlug2#771]
**Describe the bug**
It appears that calling SetParameterValue() from code should - according to its function definition - inform the host of the parameter change but it does not.  Parameter change takes place in plugin but does not appear/update in host write automation.

```
void IPlugAPIBase::SetParameterValue(int idx, double normalizedValue)
{
  Trace(TRACELOC, "%d:%f", idx, normalizedValue);
  GetParam(idx)->SetNormalized(normalizedValue);
  InformHostOfParamChange(idx, normalizedValue);    //  < should update host with new parameter value?
  OnParamChange(idx, kUI);
}
```

**To Reproduce**
Call SetParameterValue() in plugin code to manually set a parameter based on some action, computation, etc.

**Expected behaviour**
Host should acknowledge parameter change and show the change in write automation data - but it does not. 

**Additional Information**
There does not appear to be any function for InformHostOfParamChange() defined in IPlugAPIBase - so I don't know if it is incomplete or defined somewhere else.  This is the only appearance of that function that I can find searching code.

`virtual void InformHostOfParamChange(int paramIdx, double normalizedValue) {}`

**Comment by olilarkin** [comment]
"called from the UI in the middle of a parameter change gesture"

You need to call BeginInformHostOfParamChange()/ EndInformHostOfParamChange() around it

**Comment by rexmartin158** [comment]
Apologies for the misunderstanding but thank you for the clarification!
