### ISSUE TITLE
Duplicating DAW track with resized plugin doesn't copy plugin size

### ISSUE THREAD

**Issue by rexmartin158** [iPlug2/iPlug2#773]
**Describe the bug**
Duplicating a track in a DAW when a plugin has been resized doesn't copy the size of the plugin - i.e., plugin on duplicated track loads at default size.

**To Reproduce**
1. Load plugin (iPlugEffect or iPlugControls) on a track in Reaper or other DAW.
2. Resize the plugin up or down with corner resizer
3. Duplicate the track
4. Plugin on duplicated track doesn't match size of plugin on source track.  

NOTE: The plugins parameter settings **_do_** get copied - which is the most important - but plugin size does not.  So host is capturing/copying parameter data but not size data.

**Expected behaviour**
A copy of the plugin on the duplicated track, i.e., at the same size and with same settings.

**IMPORTANT DETAILS**
* What plug-in format does it relate to - tested on Win10
* What platform does it relate to - all (VST2, VST3, AAX)
* What IGRAPHICS_BACKEND does it relate to: tested with IGRAPHICS_NANOVG

**Comment by olilarkin** [comment]
You need to serialise the editor size if you want that behaviour

**Comment by rexmartin158** [comment]
> 
> 
> You need to serialise the editor size if you want that behaviour

Thank you for the info.  Does that require implementing chunks or is it just a setting somewhere?

**Comment by olilarkin** [comment]
yes
