### ISSUE TITLE
imGui crash: Fonts.Size > 0 

### ISSUE THREAD

**Issue by alechk4** [iPlug2/iPlug2#774]
**Describe the bug**

imGui crashes if I copy paste the IPlugResponsiveUI  VST effect in Reaper.

```
(Press Retry to debug the application - JIT must be enabled)Assertion failed!

Program: ...UI\build-win\vst3\x64\Debug\IPlugResponsiveUI.vst3
File: D:\Users\Alechk4\Documents\JUCE\iPlug2\Depe...\imgui.cpp
Line: 6966

Expression: g.IO.Fonts->Fonts.Size > 0 && "Font Atlas not built. Did you call io.Fonts->GetTexDataAsRGBA32() / GetTexDataAsAlpha8()?"
```

**To Reproduce**
Build the IPlugResponsiveUI example and debug it in Reaper.
In the FX window: Right click -> Copy Selected FX, Right Click -> Paste FX.

**Expected behaviour**
Another instance of IPlugResponsiveUI should be loaded normally.

**IMPORTANT DETAILS**
* What plug-in format does it relate to - VST3 (possibly ALL)
* What platform does it relate to - Windows 10
* What IGRAPHICS_BACKEND does it relate to - IGRAPHICS_NANOVG

**Comment by olilarkin** [comment]
Closed since I have removed IMGUI support
