### ISSUE TITLE
Position wobble/jitter in multi-frame bitmaps stacked horizontally

### ISSUE THREAD

**Issue by rexmartin158** [iPlug2/iPlug2#781]
**Describe the bug**
Multi-frame bitmaps stacked horizontally "wobble/jitter" when indexed

**To Reproduce**
Build any plugin type using a horizontally stacked bitmap control.  

**Expected behaviour**
Position of multi-frame bitmap should not move - only frames should change

**Screenshots**
Knob control using horizontally stacked bitmap (knob position wobbles/jitters):

![horizontal stack - position jitter](https://user-images.githubusercontent.com/84396036/128235050-230281c2-dd3b-4171-b7df-62b556be1bc5.gif)

Exact same knob control but stacked vertically (solid location/no jitter):

![vertical stack - no jitter](https://user-images.githubusercontent.com/84396036/128235073-a59db62a-59ad-406b-a140-843ac40604b1.gif)

**IMPORTANT DETAILS**
* What plug-in format does it relate to - ALL
* What platform does it relate to - ALL
* What IGRAPHICS_BACKEND does it relate to: occurs with both NanoVG and Skia

**Additional context**
Anyone else noticed/experienced this behavior?  I originally had these bitmaps stacked horizontally so I could get more frames in the NanoVG 16384 total pixel limit - but it appears there is a flaw somewhere that horizontal stacking causes position jitter.  Checked in Skia and also occurs there.

Bitmaps shown here are even-sized (136 x 176 pixels, 93 frames for 12:00 symmetry)

**Comment by AlexHarker** [comment]
Are you able to provide a bitmap (here or privately) that I can use to test? The wobble looks pretty obviously/bad so something definitely seems wrong here, and if that's appearing in both backends then that's surprising, but hopefully would be apparent on testing.

**Comment by AlexHarker** [comment]
I attach here a horizontal bitmap that is 128 * 128 per frame with 97 frames. All the frames are the same identical outline circle. If I load this into a IBKnobControl (using IPlugControls) then I do not see any wobble - happy for this to be checked at your end @rexmartin158, but I can't currently reproduce.

 ![base97](https://user-images.githubusercontent.com/4799074/145495228-fbbac70d-43e3-457c-94fd-dfc8f96c2a74.png)

**Comment by AlexHarker** [comment]
Here's the results I get on my machine

https://user-images.githubusercontent.com/4799074/145495571-8ffc1ac6-2e54-439d-8cb6-659ed7b45098.mov

.

**Comment by rexmartin158** [comment]
@AlexHarker 

> I do not see any wobble

In the process of putting together a demo for you I decided to generate the "knob" bitmaps with solid as well as transparent backgrounds in both horizontal and vertically stacked versions.  That way I could see if the entire bitmap was moving around or if just the "knob" inside the bitmap was moving around.

In the example below all bitmaps were generated from the same artwork - only difference being horizontal vs. vertical frame stacking.  In this case, the vertically stacked bitmap is the one with the problem whereas in my example at this top of this thread the jitter was appearing in the horizontally stacked version.

![Bitmap shift](https://user-images.githubusercontent.com/84396036/145648368-b9416eeb-2d75-4fca-805d-6df46248d6b6.gif)

So with this test I concur - iPlug is not the cause of this jitter.  There is apparently something wrong in the multi-frame bitmap software I am using (Knobman).

I am sorry for the false alarm.  I am closing this report as "resolved - user issue".  Thank you.

**Comment by AlexHarker** [comment]
No problem - thanks for checking this out!
