### ISSUE TITLE
[REQ] Set license on GH

### ISSUE THREAD

**Issue by forart** [iPlug2/iPlug2#782]
Hi there, this project is awesome !

Since we've collected it in our [HyMPS project list](https://github.com/forart/HyMPS) (in the [AudioLIBs section](https://github.com/forart/HyMPS/blob/main/AudioLIBs.md)), can you please set licensing terms on this git ?

Thanks in advance !

**Comment by olilarkin** [comment]
https://github.com/iPlug2/iPlug2/blob/master/LICENSE.txt

**Comment by forart** [comment]
Hi there, thanks for reply.

If we understood correctly, the license is not officially supported by GH...

Our "problem" is that it does not generates the correct badge: 
![](https://flat.badgen.net/github/license/iPlug2/iPlug2/?label=LICENSE)
(generate string: https://flat.badgen.net/github/license/iPlug2/iPlug2/?label=LICENSE)

Thanks anyway for your work !
