### ISSUE TITLE
Control MIDI Note duration in code

### ISSUE THREAD

**Issue by gildurao** [iPlug2/iPlug2#783]
Hello,

In the plugin that I am developing, I have a need to send MIDI messages in code, rather than listening to a user's keyboard or other MIDI controller.

I started with the IPlugInstrument project as a base for mine and so far I've succeeded in sending Note ON messages, but of course they keep playing forever. What I did was ignore what comes in from the keyboard in ``ProcessMidiMsg`` and just send a random note:

```cpp
  IMidiMsg message = IMidiMsg();

  message.MakeNoteOnMsg(52, 5, 0, 0);

  mDSP.ProcessMidiMsg(message);
  SendMidiMsg(message);
```

Right now I'm having trouble in sending a Note OFF message after a certain time. I'm new to C++ so this probably explains my difficulty. I've tried to use Timers, threads, Callables and just a simple sleep command. I was wondering if iPlug2 already supports this out of the box and I may have missed it or if someone could guide me towards how to achieve it (feel free to close the issue if you feel like it does not belong here, I understand it and accept it).

**Comment by olilarkin** [comment]
Hello,

This is not really an "issue" with iPlug2. The forum or slack is the place to ask questions.

I will answer on the forum...

https://iplug2.discourse.group/t/create-midi-messages-programatically/465/5
