### ISSUE TITLE
Add "Getting_started_linux" on the iPlug2's wiki

### ISSUE THREAD

**Issue by MetalMaxMX** [iPlug2/iPlug2#784]
Hello! I've been eyeing iPlug2 for a while, though I'm a Linux user so trying to compile some of the examples has been a challenge due to a myriad of various instructions thrown here and there and on the iPlug2 forums/PR logs. I'd like to know if it was possible to add a section where a Linux user could get started with the compilation of iPlug2 itself, where: 

A) Would recommend a distro where is reliably demonstrated that one can compile the examples.
B) The steps and deps needed to download in order for iPlug2's examples to compile on the aforementioned distro.
C) ???
D) Profit! 

I'd also like to know if the project itself recommends a particular distro or the like to work with, as well as the minimum deps required to compile this. I'm asking because the Linux support is said to be somewhat there so I might as well go ahead and ask this! 

Cheers
MetalMaxMX

**Comment by olilarkin** [comment]
IPlug2 doesn't yet support Linux, so that's why there is no guide￼

**Comment by olilarkin** [comment]
Most of the info about the work in progress is on this thread

https://github.com/iPlug2/iPlug2/issues/105

**Comment by olilarkin** [comment]
A guide will be added when linux is supported
