### ISSUE TITLE
Windows app - accelerators not working

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#79]
Stand-alone app features shortcuts for various debug options and triggering the preferences dialogue, but these aren't working on Windows

**Comment by olilarkin** [comment]
any Win32 experts in the house? all looks like the accelerator tables in the examples are set correctly to me in IPlugInstrument where i was experimenting:
https://github.com/iPlug2/iPlug2/blob/master/Examples/IPlugInstrument/resources/main.rc#L173
https://github.com/iPlug2/iPlug2/blob/master/Examples/IPlugInstrument/resources/main.rc#L89

**Comment by olilarkin** [comment]
handling in the app (not working) :
https://github.com/iPlug2/iPlug2/blob/master/IPlug/APP/IPlugAPP_main.cpp#L55
https://github.com/iPlug2/iPlug2/blob/master/IPlug/APP/IPlugAPP_main.cpp#L105

**Comment by AlexHarker** [comment]
I'll try to take a look if no-one else knows what the issue is.

**Comment by AlexHarker** [comment]
So - the code you've linked to isn't the issue.

The issue is IsDialogMessage() takes the messages and they never get to TranslateAccelerators(). I'm not quite sure why IsDialogMessage() is there, so I don't feel comfortable making a change, but that's the issue.

**Comment by AlexHarker** [comment]
Fixed in a23d73a4dac75a67a15d72a3750543f2d28ed6d2 and cf92414dafc67feb9ccc3fa2c7924c45533a71d6.
