### ISSUE TITLE
PNGS and SVGS that are drawn in a different scale than their actual size are not antialiased anymore

### ISSUE THREAD

**Issue by janhase88** [iPlug2/iPlug2#795]
when drawing pngs and svgs smaller then their actual scale usually in skia they where scaled with antialiasing and still looked fine, i updated to the latest iplug2 and prebuild libraries and now the images are pixelated / not antialiased anymore (skia, win10 x64).

**Comment by olilarkin** [comment]
Could you update to the latest tip and see if this commit fixed it?

https://github.com/iPlug2/iPlug2/commit/ab2726c498652170c5c3048ec308dca5806a7780

**Comment by olilarkin** [comment]
@janhase88 Did it fix it?

**Comment by janhase88** [comment]
@olilarkin no, still pixelated (updated iplug just now)

**Comment by olilarkin** [comment]
Could you provide an example?

**Comment by janhase88** [comment]
```
class PaintPNG : public IControl {
public:
  PaintPNG(IRECT r) : IControl(r) {}

  void Draw(IGraphics& G) override {
    std::string BitmapPath = "c:/smiley.png";
    IBitmap Bitmap = G.LoadBitmap(BitmapPath.c_str());;
    DrawBitmapScaledAndPositioned(G, this->GetRECT(), Bitmap, 0, 1);
  }

  void DrawBitmapScaledAndPositioned(IGraphics& G, IRECT TargetRect, IBitmap TargetBitmap, IBlend* Blend, float Scale) {
    //#  DrawBitmapScaledAndPositioned
    
    IRECT BitmapRect = IRECT(0, 0, TargetBitmap.W(), TargetBitmap.H());
    float ratio = RectGetFitRatio(TargetRect, BitmapRect);
    TargetBitmap.GetAPIBitmap()->SetBitmap(TargetBitmap.GetAPIBitmap()->GetBitmap(), TargetBitmap.W(), TargetBitmap.H(), 1, (1. / ratio));
    G.DrawBitmap(TargetBitmap, TargetRect, 1, Blend);
  }

  inline double RectGetFitRatio(const IRECT& Master, const IRECT& Student) {
    //# RectGetFitRatio
    double Ratio = Master.W() / Student.W();
    if (Student.H() * Ratio > Master.H()) {
      Ratio = Master.H() / Student.H();
    }
    return Ratio;
  }
};
```

`pGraphics->AttachControl(new PaintPNG(b));`


for c:/smiley.png:

![smiley](https://user-images.githubusercontent.com/46456607/148863117-01da944c-c10a-439c-bf25-52220ede0342.png)

**Comment by janhase88** [comment]
https://iplug-users.slack.com/archives/C8ZF32KT4/p1641863439013500

**Comment by olilarkin** [comment]
Thanks very much, i'll investigate

**Comment by AlexHarker** [comment]
Findings looking at this (put into iPlugEffect on Mac.

1 - Skia CPU looks really smooth
2 - Skia Metal/GL3 looks more ragged but so does NanoVG Metal (but I haven't tried windows
3 - For some reason Skia is loading a 2x scaled bitmap on my retina screen (as I'd expect), but NanoVG is not - that needs investigating.
4 - I'd strongly advise against the way the code is written above setting the API Bitmap (that's not something you should really mess with outside of framework code) - below is a more correct and reliable way to do the scaling (the rest of the code can stay the same)

```
void DrawBitmapScaledAndPositioned(IGraphics& G, IRECT TargetRect, IBitmap TargetBitmap, IBlend* Blend, float Scale) {
    //#  DrawBitmapScaledAndPositioned
    
    IRECT BitmapRect = IRECT(0, 0, TargetBitmap.W(), TargetBitmap.H());
    float ratio = RectGetFitRatio(TargetRect, BitmapRect);
    G.PathTransformTranslate(TargetRect.L, TargetRect.T);
    G.PathTransformScale(ratio, ratio);
    G.DrawBitmap(TargetBitmap, BitmapRect, 1, Blend);
  }
```

**Comment by AlexHarker** [comment]
@janhase88 - if you get a chance can you try with skia CPU and the pre-built libraries and let us know if that changes anything?

**Comment by janhase88** [comment]
i tried the G.PathTransformScale method for:
` <EXTRA_ALL_DEFS>IGRAPHICS_SKIA;IGRAPHICS_GL2</EXTRA_ALL_DEFS>`
and can confirm that the png now is scaled antialiased and looks smooth as desired. Thank you :-)

whereas with:
` <EXTRA_ALL_DEFS>IGRAPHICS_NANOVG;IGRAPHICS_GL2</EXTRA_ALL_DEFS>`
the drawn png is still pixelated when scaled down with G.PathTransformScale

if you are refering to the layoutchanges of the iplugeffect gain knob and text in the upper right picture, then this is caused due to the debug live edit mode - i just moved them there manually for no reason. the PaintPNG control was attached with an irect of the plugsize, so i could see how the png behaves drawn in different sizes, when the icontrol size is changed with the debug live edit mode.

**Comment by janhase88** [comment]
retested today with newest libs - issue is still present

**Comment by AlexHarker** [comment]
I can't reproduce here. I attach a screenshot from iPlugControls (as an app) running on skia GL2 on windows. The bitmaps controls look fine to me. Do you see any issues with them?

<img width="931" alt="Screenshot 2022-02-14 at 21 34 34" src="https://user-images.githubusercontent.com/4799074/153950403-329bf442-88e7-456a-a320-6c7142ed9b1d.png">

**Comment by AlexHarker** [comment]
Two more pictures where I'm scaling the knobs to the control size as well. So as far as I can see scaling up is fine. Your example above is a significant scaling down, and perhaps that is working a bit differently, but none of my tests earlier on Mac looked anywhere near as bad as that, so I think to investigate further I'd really need a an example project pushed to a branch so we could make sure we are testing exactly the same thing.

<img width="769" alt="Screenshot 2022-02-14 at 22 33 50" src="https://user-images.githubusercontent.com/4799074/153958486-45a5044d-671a-4131-9f93-f181334ec091.png">

<img width="1060" alt="Screenshot 2022-02-14 at 22 34 09" src="https://user-images.githubusercontent.com/4799074/153958506-b921e083-ec65-403a-90a9-1d764ddb9803.png">

**Comment by janhase88** [comment]
@AlexHarker it looks really good on Mac. 

i tested the following: 
in the "good results" iplug-master folder i redownloaded the libs via `download-prebuilt-libs.sh`
and built iplugeffect then, which resulted in several errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'experimental/svg/model/SkSVGDOM.h': No such file or directory (compiling source file ..\..\..\IGraphics\Controls\IControls.cpp)	IPlugEffect-app	A:\4_programming\vst\0_Iplug2\iPlug2-master_saved10.01.2022\IGraphics\IGraphicsPrivate.h	32	
Error	C1083	Cannot open include file: 'experimental/svg/model/SkSVGDOM.h': No such file or directory (compiling source file ..\IPlugEffect.cpp)	IPlugEffect-app	A:\4_programming\vst\0_Iplug2\iPlug2-master_saved10.01.2022\IGraphics\IGraphicsPrivate.h	32	
Error	C1083	Cannot open include file: 'experimental/svg/model/SkSVGDOM.h': No such file or directory (compiling source file ..\..\..\IPlug\APP\IPlugAPP_dialog.cpp)	IPlugEffect-app	A:\4_programming\vst\0_Iplug2\iPlug2-master_saved10.01.2022\IGraphics\IGraphicsPrivate.h	32	
Error	C1083	Cannot open include file: 'experimental/svg/model/SkSVGDOM.h': No such file or directory (compiling source file ..\..\..\IGraphics\Platforms\IGraphicsWin.cpp)	IPlugEffect-app	A:\4_programming\vst\0_Iplug2\iPlug2-master_saved10.01.2022\IGraphics\IGraphicsPrivate.h	32	
Error	C1083	Cannot open include file: 'experimental/svg/model/SkSVGDOM.h': No such file or directory (compiling source file ..\..\..\IGraphics\IGraphicsEditorDelegate.cpp)	IPlugEffect-app	A:\4_programming\vst\0_Iplug2\iPlug2-master_saved10.01.2022\IGraphics\IGraphicsPrivate.h	32	
Error	C1083	Cannot open include file: 'experimental/svg/model/SkSVGDOM.h': No such file or directory (compiling source file ..\..\..\IGraphics\IGraphics.cpp)	IPlugEffect-app	A:\4_programming\vst\0_Iplug2\iPlug2-master_saved10.01.2022\IGraphics\IGraphicsPrivate.h	32	
Error	C1083	Cannot open include file: 'experimental/svg/model/SkSVGDOM.h': No such file or directory (compiling source file ..\..\..\IGraphics\IControl.cpp)	IPlugEffect-app	A:\4_programming\vst\0_Iplug2\iPlug2-master_saved10.01.2022\IGraphics\IGraphicsPrivate.h	32	
Error	C1083	Cannot open include file: 'experimental/svg/model/SkSVGDOM.h': No such file or directory (compiling source file ..\..\..\IGraphics\Controls\ITextEntryControl.cpp)	IPlugEffect-app	A:\4_programming\vst\0_Iplug2\iPlug2-master_saved10.01.2022\IGraphics\IGraphicsPrivate.h	32	
Error	C1083	Cannot open include file: 'experimental/svg/model/SkSVGDOM.h': No such file or directory (compiling source file ..\..\..\IGraphics\Controls\IPopupMenuControl.cpp)	IPlugEffect-app	A:\4_programming\vst\0_Iplug2\iPlug2-master_saved10.01.2022\IGraphics\IGraphicsPrivate.h	32	
```
which leads me to the conclusion, that the new libs by now became incompatible with the "good-result" iplug-master folder.

unfortunatly i am a total git newby. but i trimmed the working "good results" iplug-master folder to least minimal zip file-size and uploaded it, with everything in it, so you can maybe revert it to a comment and investigate?

https://www.dropbox.com/s/cd23v8ouvd0uvpw/iPlug2-master_good-skia-results.zip?dl=1

**Comment by janhase88** [comment]
@AlexHarker pls review my upper comment

**Comment by janhase88** [comment]
*deleted my previous comment to get more precise and conclusive here:

i can not revert my version to a commit, but i uploaded it with everything in it here (93 MB):
https://www.dropbox.com/s/cd23v8ouvd0uvpw/iPlug2-master_good-skia-results.zip?dl=1

i compared your screenshots to the size of the smiley in my screenshot and it appears, that your smiley is about twice as big as mine. so if the smiley is drawn twice the size on your screen it uses double the amount of pixels, which would make it look sharper. i think you would get the same pixelated result as my worst, if you would draw it half the size where the other way around if i paint it twice the size i should get your result.

size comparison: my worst result on the left, yours on the right:
![Screenshot from 2022-02-17 16-17-43](https://user-images.githubusercontent.com/46456607/154524134-33cb4c1e-ad5f-457b-a4c5-dd1a54d57fd1.png)

for more detailed testing we can use this update of reproduction step 3:
3. open IPlugEffect.h and insert under
`using namespace igraphics;`
following code: 
```
#include "IControl.h"
#include <sstream>
#include <string>
#include <iostream>
#include <iomanip> 
class PaintPNG : public IControl {
public:
  PaintPNG(IRECT r) : IControl(r) {}

  void Draw(IGraphics& G) override {
    std::string BitmapPath = "c:/smiley.png";
    IBitmap Bitmap = G.LoadBitmap(BitmapPath.c_str());
    IRECT Cell;
    int numrows = 3;
    int numcols = 3;
    int row = 0;
    int col = 0;
    float scale = 1;
    std::string Info;
    IText T;
    T.mFGColor = COLOR_GREEN;
    for (int c = 0; c < numrows * numcols; c++) {
      Cell = RectGetTableCell(GetRECT(), numrows, numcols, col, row);
      ++col;
      if (col > numcols - 1) {col = 0; ++row;}
      G.DrawRect(COLOR_BLACK, Cell);
      IRECT CellDraw = Cell.GetScaledAboutCentre(1. / (c + 1));
      DrawBitmapScaledAndPositioned(G, CellDraw, Bitmap, 0, 1);
      Info = "Width: " + NumToString(CellDraw.W(), 0) + " | Height: " + NumToString(CellDraw.H(), 0);
      G.DrawText(T, Info.c_str(), RectGetSliced(Cell, 1, 5, 4));
    }
    Info = "ScreenScale:" + NumToString(G.GetScreenScale(), 2) + " | DrawScale:" + NumToString(G.GetDrawScale(), 2);
    G.DrawText(T, Info.c_str(), RectGetSliced(GetRECT(),1,10,0));
    if (!G.ShowingFPSDisplay()) G.ShowFPSDisplay(true);
  }

  void DrawBitmapScaledAndPositioned(IGraphics& G, IRECT TargetRect, IBitmap TargetBitmap, IBlend* Blend, float Scale) {
    IRECT BitmapRect = IRECT(0, 0, TargetBitmap.W(), TargetBitmap.H());
    float ratio = RectGetFitRatio(TargetRect, BitmapRect);
    G.PathTransformSave();
    G.PathTransformTranslate(TargetRect.L, TargetRect.T);
    G.PathTransformScale(ratio, ratio);
    G.DrawBitmap(TargetBitmap, BitmapRect, 1, Blend);
    G.PathTransformRestore();
  }

  double RectGetFitRatio(const IRECT& Master, const IRECT& Student) {
    double Ratio = Master.W() / Student.W();
    if (Student.H() * Ratio > Master.H()) Ratio = Master.H() / Student.H();
    return Ratio;
  }

  IRECT RectGetSliced(const IRECT& R, bool HorizontalSlicing, int NumberOfSlices, int ReturnSliceNumber) {
    if (HorizontalSlicing) return IRECT(R.L, R.T + (R.H() / NumberOfSlices) * ReturnSliceNumber, R.R, R.T + (R.H() / NumberOfSlices) * (ReturnSliceNumber + 1));  
    else return IRECT(R.L + (R.W() / NumberOfSlices) * ReturnSliceNumber, R.T, R.L + (R.W() / NumberOfSlices) * (ReturnSliceNumber + 1), R.B);
  }

  IRECT RectGetTableCell(const IRECT& R, int NumColumns, int NumRows, int GetColumn, int GetRow) {
    return RectGetSliced(RectGetSliced(R, true, NumRows, GetRow), false, NumColumns, GetColumn);
  }

  template <class Val>
  inline std::string NumToString(Val val, size_t decimal_digits) {
    std::ostringstream ss; ss << std::fixed << std::setprecision(decimal_digits) << val; return ss.str();
  }
};
```
 this for the latest Iplug2 framework results in:

![IPlugEffect_ByWDEOx333](https://user-images.githubusercontent.com/46456607/154543455-2a831255-2e2e-4f70-ac0f-c4c16b10b34e.png)

And for the "good-result" Iplug2 results in:

![IPlugEffect_UQDzlZ6iJS](https://user-images.githubusercontent.com/46456607/154543564-4a9e2e2d-e0e8-40ff-bead-85e8a724a0e9.png)

**Comment by janhase88** [comment]
@AlexHarker @olilarkin 

i found that when in IGraphicsSkia.cpp in void IGraphicsSkia::DrawBitmap on line 502 
`samplingOptions = SkSamplingOptions(SkFilterMode::kLinear, SkMipmapMode::kLinear);`
is added the anitaliasing in skia is working again. i tested this with skia gpu and cpu.

**Comment by janhase88** [comment]
It's fixed with the recent skia lib update - all graphics are now drawn sharp and antialiased as expected. Issue can be closed.
