### ISSUE TITLE
Press Keys for macOs version

### ISSUE THREAD

**Issue by AlexanderLahutsin** [iPlug2/iPlug2#802]
https://iplug2.discourse.group/t/press-key-commnd-c-v-and-etc/521/6

GetKeyState:

Command + C
Command + V
Enter (VK_RETURN)

I noticed that no such implementations were found. The plugin cannot copy and paste data into a text input. There is no software implementation of checking the keystrokes of these keys.

I think that this functionality is simply necessary...

**Comment by olilarkin** [comment]
Either with the platform native text entry or the IGraphics text entry (AttachTextEntryControl()) cmd-v is working in the app target. If it doesn't work in the plug-in then it is probably because the host intercepts the key press.

If you are missing some win32 api for something custom then 🤷
