### ISSUE TITLE
(WAM) Makedist-web.sh scripts fail with recent emscripten

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#804]
"AudioWorkletGlobalScope.WAM" etc is not a valid identifier

modfiy this line in emsdk in order to compile (make it return True)

https://github.com/emscripten-core/emscripten/blob/89c98c744f555dfe53220944b087367b76890bb7/tools/shared.py#L668

**Comment by mrkev** [comment]
I created a PR on emscripten, let's see if it gets merged https://github.com/emscripten-core/emscripten/pull/21115
