### ISSUE TITLE
Using DPF's VST3 implementation

### ISSUE THREAD

**Issue by SeleDreams** [iPlug2/iPlug2#810]
I noticed that iPlug2 to make vsts requires to use steinberg's vst3 sdk, the steinberg sdk being under a dual licence gpl/commercial makes it a bit tricky to use with more open licenced projects

that's why i think it might be a good idea to support DPF as DPF has its own vst3 implementation under ISC licence which is an MIT-like licence, their vst3 implementation is in their develop branch

https://github.com/DISTRHO/DPF/

**Comment by SeleDreams** [comment]
https://github.com/DISTRHO/DPF/tree/develop/distrho/src/travesty this is a direct link to their vst3 implementation named travesty

**Comment by olilarkin** [comment]
Thanks for letting me know about that but I don't think we should use a reverse engineered sdk, but a fork of iPlug2 could of course
