### ISSUE TITLE
(WIN) WebView: calling SendArbitraryMsgFromDelegate() from C++ causes a heap corruption

### ISSUE THREAD

**Issue by adam-hanna** [iPlug2/iPlug2#811]
https://github.com/iPlug2/iPlug2/blob/88b61dd31cdd6cecabd6b42826c9e9853381ca25/IPlug/Extras/WebView/IPlugWebViewEditorDelegate.h#L69

Needs quotes around the `%s`. E.g.

`str.SetFormatted(mMaxJSStringLength, "SAMFD(%i, %i, '%s')", msgTag, dataSize, base64.data());`

**Comment by olilarkin** [comment]
thanks!
