### ISSUE TITLE
OnMouseDblClick isnt called on double click with right mouse button (skia, standalone, winx64)

### ISSUE THREAD

**Issue by janhase88** [iPlug2/iPlug2#818]
OnMouseDblClick isnt called on double click with right mouse button (skia, standalone, win10x64)

possible fix:
IGraphicsWin.cpp on Line 466 add:  `case WM_RBUTTONDBLCLK:`

**Comment by AlexHarker** [comment]
This is also the case for the Mac platform according to the code (but not the web platform) - we will need to decide what the correct functionality is.

**Comment by olilarkin** [comment]
@olilarkin will add for mac and win
