### ISSUE TITLE
Blend modes need reworking

### ISSUE THREAD

**Issue by AlexHarker** [iPlug2/iPlug2#84]
There are more options than provided here and LICE support is poor. Naming is not very meaningful, so work to be done here to modernise.

**Comment by AlexHarker** [comment]
Mostly done on blend-cleanup branch, although this has a few breaking changes (deleted ColorDodge and renamed Clobber and None).

I've decided not to support complex blend modes which NanoVG would not be able to support. If complex blending is really necessary it could be added later should someone make a case for it.

There is a minor outstanding concern that NVG_COPY doesn't seem to function as expected (copy in other APIs works fine) - the test blend control needs a rewrite (along with a bitmap that has variable alpha across its surface) and everything needs checking.

**Comment by olilarkin** [comment]
this got merged. @AlexHarker happy to close?

**Comment by AlexHarker** [comment]
Not yet - still some things to check and colours don't match between APIs (or possibly with iPlug 1) - high up my list post text wrangling.

**Comment by olilarkin** [comment]
https://github.com/iPlug2/iPlug2/pull/432
