### ISSUE TITLE
gen~ support?

### ISSUE THREAD

**Issue by lewlepton** [iPlug2/iPlug2#853]
just a quick question, regarding gen~ from cycling74s Max.
its a really nice bit of tech that makes making audio tools just a wee bit easier. so I was wondering if this at all could be featured, as well as Faust support. since gen~ can export code, can that be used in iPlug2.
or if it can be done already, is there by chance any info on it?

many thanks for the hard work on this tool, by the way. ive had it on my mind for a while & felt Id like to finally jump in & try it now it has grown more

thanks again
x

**Comment by AlexHarker** [comment]
I think @olilarkin might have done something with this at some point in terms of automation, but it isn't really that hard to make a binding manually if you have some C++ experience. What sort of support did you have in mind?

**Comment by lewlepton** [comment]
it was, I guess, having it create or make links with iPlug2.
so I have my gen~ patch, with some access for sliders or toggles, which I can export to code, but then generate to an iPlug2 project so I could put in things like sliders from iPlug2 etc to bind with the gen~ code. if that makes sense. which I could put to a plugin/app

I was playing around with the JUCE/gen~ stuff & that was an utter pain & in all honesty felt completely out of date with its exporting

**Comment by lewlepton** [comment]
also thanks for the really quick reply 🖤

**Comment by lewlepton** [comment]
I guess an example of some sort would be nice, just to even help people get off the ground. I may look into it myself, but first getting used to iPlug2 & seeing how it works 🖤

**Comment by olilarkin** [comment]
I am going to close this. I don't really want to add a gen~ example to the iPlug2 repo at this stage

**Comment by lewlepton** [comment]
Cool spot. I’m gonna have a work on it further & make it better & work kinks out 👍
