### ISSUE TITLE
Path to fl incorrect causing error on debug

### ISSUE THREAD

**Issue by Wistpotion** [iPlug2/iPlug2#861]
**Describe the bug**
After using the script to set fl as the host for debugging, upon starting a debug session there is an error.

**To Reproduce**
Run the select_host.py script and select fl. If the path to FL is different from the one that select_host.py thinks, then the error will occur. My path to fl is `C:\Program Files\Image-Line\FL Studio 20\FL64.exe` as well as `C:\Program Files\Image-Line\FL Studio 20\FL.exe`. The path in the error message (for x64 debugging) was: `Program Files (x86)\Image-Line\Fl Studio 20\FL64.exe`.

**Expected behaviour**
The path should be correct.

**IMPORTANT DETAILS**
* What plug-in format does it relate to - VST2, VST3, AUv2, AUv3, AAX, APP or ALL?
All.
* What platform does it relate to - Windows/macOS/iOS/Linux or ALL?
Might be all, but I'm running windows so I can't be sure.
* What IGRAPHICS_BACKEND does it relate to, IGRAPHICS_NANOVG, IGRAPHICS_SKIA or ALL? 
All.

**Additional context**
This was super easy to solve, I just went into the common-win.props file and changed the path to be hardcoded to the correct path. I thought I'd report it just in case someone else has the problem. Making it a bit clearer that you can modify the file yourself would be nice, but it not that big of a deal. Also, the script checking if the path actually exists and giving feedback if it doesn't would be nice.

**Comment by olilarkin** [comment]
Thanks, I have updated the wiki to explain how you can modify the common-win.props if your paths are different

https://github.com/iPlug2/iPlug2/wiki/02_Getting_started_windows
