### ISSUE TITLE
[REQUEST] more 'simple iPlug2 tutorials/examples'

### ISSUE THREAD

**Issue by lewlepton** [iPlug2/iPlug2#862]
I am looking for something to help. but having a good starting point on how to use iPlug2 would be incredibly welcomed

there is some great content already, but having things as simple examples with text, such as asset positioning & things that give current users & new users a better feel on how iPlug2 works.
I feel thats what is missing a lot, also since the example code is not commented, it can make it hard to get to grasp what is happening

I am working up to making really simple examples for myself to learn from & to keep looking at the remember, if they end up being more useful ill send a pull request for you to see. but if there is something that does appear beforehand, with a better understanding, then thats even better

but simpler walk-thru examples of the framework & comments/wiki would be incredibly welcomed. though I understand if time & the such is not being favourable to do it & things like this are put at the side for development

again, thanks for all the hard work on this interesting framework 🖤

**Comment by olilarkin** [comment]
Of course this would be nice, but we don't need to track it as an issue here. Sadly I don't have enough time for all the things. I have been meaning to do an iPlug2 tutorial based on a popular iPlug1 tutorial by martin finke, but not got around to it yet.

**Comment by lewlepton** [comment]
thats fair enough.
im currently trying to make things easier at the moment with knowing what is what & trying to make some form of an easier way of understanding the main base parts. so far its going ok, but I need to make sure I remember what is what, hahaha

**Comment by AlexHarker** [comment]
I'd say in any case this is covered by #470 as an issue, (which is marked help wanted). We would welcome contributions in this area, but when we do have time it is more likely to go to more low-level dev work. Writing good documentation is both a skill in and of itself and a time-consuming task.

Another route that could be taken is for someone to cover iPlug2 outside of the eco-system of the repo/discourse etc. and just host their own tutorials on whatever space they wished.
