### ISSUE TITLE
WAM v2 support?

### ISSUE THREAD

**Issue by KnappSas** [iPlug2/iPlug2#868]
Hi,
I'm starting to have a look into Web Audio Modules right now and checked the iPlug2 examples as I found out they seem to be the old version of the Web Audio Modules. This was confusing for me first, because on first sight it looked much more complicated to implement a host for version 1 of WAMs.

Do you know if anyone is working on supporting WAM v2 in iPlug2?

**Comment by olilarkin** [comment]
I'm waiting to see what the WAM2 C++ API looks like. AFAIK there is no C++ example yet
