### ISSUE TITLE
IPlugEffect example does not output any audio on x64 VST3 / FL 20.1 / Windows

### ISSUE THREAD

**Issue by codecat** [iPlug2/iPlug2#87]
I built the example IPlugEffect as a VST3 plugin, and it was automatically copied to my 64 bit VST3 folder. Now I have FL set up to output some audio through an insert, but putting IPlugEffect in between to change the gain seems to output no audio at all.

![image](https://user-images.githubusercontent.com/136534/50574175-4a7db380-0de3-11e9-876f-1bfb946b5da7.png)

**Comment by codecat** [comment]
Actually, I also don't have any audio outputting in the standalone app. Seems like the input is always zeroes. I narrowed it down in IPlugAPP, where the inputs connections are being set to false:

https://github.com/iPlug2/iPlug2/blob/23f51fd5559549036ae9134e99e44ae709c74ba5/IPlug/APP/IPlugAPP.cpp#L102

Not sure if that's also the case in the VST3 code, but it might be?

**Comment by olilarkin** [comment]
fixed in https://github.com/iPlug2/iPlug2/commit/ec673e7d8a5ec96d9ad52073e2e95b18f67ce27b, will look at the app now...
