### ISSUE TITLE
IVSwitchControl can't represent all enums correctly

### ISSUE THREAD

**Issue by Kylotan** [iPlug2/iPlug2#870]
**Describe the bug**
If you use `InitEnum` with an enum with 10 entries, then use an IVSwitchControl to control it, you won't be able to select the 10th entry, due to floating point imprecision.

**To Reproduce**
1. Create a param and set it up with InitEnum, passing a list of 10 entries
2. Create an IVSwitchControl that references that enum
3. Build and run the plugin.
4. Click the switch control to cycle through the enums, to reach the final value.

**Expected behaviour**
You should be able to select the final (10th) enum value.
Instead, it wraps back around to the first one.

**IMPORTANT DETAILS**
Relates to all plugin formats and all platforms.
Bug is in `ISwitchControlBase` so probably affects all graphics backends.

**Additional context**
The bug is in `ISwitchControlBase::OnMouseDown` and in how this value translates to an enum.
By attempting to 'step' the value numerically, the floating point error will accumulate and the final value of `val` will be `1.0000000000000002` rather than `1`, meaning it hits the wrap-around condition instead of selecting the last value.
Similar problems could happen with any situation where the number of enum states is not a power of 2 and therefore might incur some precision errors.

A simple workaround for most cases is to change the line to read `if(val > 1.0001)`
This is perhaps not strictly correct as it permits a value greater than 1, but it does allow access to the last enum value.

**Comment by olilarkin** [comment]
Thanks, looking into it

**Comment by olilarkin** [comment]
Fixed on master
