### ISSUE TITLE
vestige.h for support of VST2

### ISSUE THREAD

**Issue by Nolram12345** [iPlug2/iPlug2#871]
A while back now Steinberg has deprecated and fully removed the VST2 SDK. This is a problem for numerous reasons, such as VST3 not being supported by a couple DAWs. 
However, there is a community-made reverse-engineered VST2 header that allows for compatibility called Vestige. Is it possible to use it with iPlug 2 ? If not, would it be possible to do such ?

You can find more details in this issue : https://github.com/steinbergmedia/vst3sdk/issues/51

**Comment by olilarkin** [comment]
I don't know about vestige, and I don't know if it would work or not. iPlug2 supports VST3 as do most hosts now, so I would suggest just to focus on that.

**Comment by Nolram12345** [comment]
Well, that's the exact problem I currently have - a few hosts do not support VST3 yet, such as Reason. But maybe there are other ways to compile for it, this just seems like the least dubious way to do it.

Thanks Steinberg.
