### ISSUE TITLE
CLAP issues (clap branch only)

### ISSUE THREAD

**Issue by Full-Bucket** [iPlug2/iPlug2#876]
**Describe the bug**
CLAP integration on the iPlug2-clap branch is incomplete:
* GUI may crash in CLAP plug-ins because of unloaded bitmaps.
* CLAP plug-ins do not output sound and do not react on (note) events.

**To Reproduce**
Compile a plug-in for the CLAP target and check in CLAP-aware host.

**Expected behaviour**
CLAP plug-ins should
* not crash,
* process audio and
* react on (note) event

**Screenshots**
N/A

**IMPORTANT DETAILS**
Relates to CLAP on all platforms for all graphic backends.

**Additional context**

**Comment by olilarkin** [comment]
It's on a branch, hence WIP, and not really issue-worthy. If you've fixed some stuff though, feel free to make a PR to the clap branch

**Comment by Full-Bucket** [comment]
Awesome, I try to do so... new to all this github stuff, sorry

**Comment by olilarkin** [comment]
No worries, cool that you're trying it :-)
