### ISSUE TITLE
(CMake) Standalone app build issues

### ISSUE THREAD

**Issue by markortu** [iPlug2/iPlug2#885]
Hi, I have detected two small problems in the cmake configuration when trying to build the standalone application on windows.

- The postbuild-win.bat.in is using the variable IPLUG2_APP_NAME instead of PLUG_NAME for the NAME field and this is causing the output of that binary to be _empty_.

- In APP.cmake the res_dir is not being set for WIN32. As a consequence the application does not create the window correctly and throws the error **1813 ERROR_RESOURCE_TYPE_NOT_FOUND**. The solution is as simple as setting the resources path just like in the other configs:
`set(res_dir "${CMAKE_BINARY_DIR}/${PLUG_NAME}-app/resources")`

I have created a PR with two small changes that fix this issue!

**Comment by olilarkin** [comment]
Thanks for the contribution. This work has been merged on the CMake branch. I found I also had to add the fonts and img paths to CMAKE_RC_PATHS in order to find the files

`  set(CMAKE_RC_FLAGS "/I${dir}/resources /I${dir}/resources/fonts /I${dir}/resources/img ${CMAKE_RC_FLAGS}")`
