### ISSUE TITLE
CLAP: Upon DAW preset change, parameter value(s) don't get reflected on the GUI

### ISSUE THREAD

**Issue by heebje** [iPlug2/iPlug2#889]
When using a CLAP build, both in Reaper as well as in Bitwig, when changing the plugin's preset in the DAW, the positions of the controls on the GUI don't change.
When using a VST3 build, they do (as they should).

Internally, the parameter values do change, so this is a bug that only affects the GUI, not the audio processing.

Way to reproduce problem:
* Be on clap branch;
* Duplicate IPlugEffect;
* Compile *-clap;
* Launch in Reaper;
* Create 2 presets in reaper with different parameter values;
* Change between those presets, and notice that the knob doesn't move (but the audio does change as it should).
* Do the same with *-vst3, and notice how the knob does move, as it should.

![CLAP_Checker](https://user-images.githubusercontent.com/16598068/184714441-66369c47-2c98-45e0-9abd-da7f8d777ade.gif)

**Comment by AlexHarker** [comment]
Thanks for the report. I'll take a look at why this is happening.

**Comment by heebje** [comment]
Thank you :)

**Comment by AlexHarker** [comment]
This is fixed by 42b827f1788ab72073f145304a0b91fdfb7329dd.

**Comment by heebje** [comment]
This works :) Thanks Alex!

**Comment by AlexHarker** [comment]
No problem - thanks for reporting.
