### ISSUE TITLE
Objective C crashes with VST3 on module deletion

### ISSUE THREAD

**Issue by AlexHarker** [iPlug2/iPlug2#89]
This is a problem that goes back to IPlug 1 and surreal machines have had reports of this "in the wild" but it's clearly apparent on VST3PluginTestHost with IPlugEffect.

It's not 100% reliable if you are creating and deleting multiple plugs, but if you create asingle  plug and then delete it immediately and then move away from the app and back a crash on window mousing seems to occur. I have only been able to reproduce once all instances of the plug are removed and the crash occurs after the module gets removed. The stack gives search_method_list as the crash point. I get the crash whether or not the plug has a custom UI, although without a get a timer related crash first, which can be fixed by deleting the timer for the terminate() method.

**Comment by AlexHarker** [comment]
This appears to be related to SWELL

**Comment by AlexHarker** [comment]
Work started on removing SWELL from plugins on the appropriate branch. Still a few issues with LICE.

**Comment by hor-net** [comment]
May this be related to the redefinition of NSButton made in swell-dlg (if my memory serves me well) ?

**Comment by AlexHarker** [comment]
Sounds about right, but my preference is to get rid of SWELL entirely for plugins - that is fine for everything but LICE which relies heavily on SWELL for text.

**Comment by AlexHarker** [comment]
Thanks for the explanation of the issue BTW. As we might be tied to SWELL for a few things to do with LICE and the Faust Editor my testing does show that the NSButton extensions are the cause of the crash, and if commented out these go away. I'll investigate whether we can get a change in SWELL to allow us to opt out of this functionality.

**Comment by olilarkin** [comment]
should be fixed by 205bf256b703e379c1b34df0bf4e3210b2fd4065

**Comment by AlexHarker** [comment]
Closing this as I've tested in the test host and I cannot reproduce the crash. That includes running the tests that will open and close many versions of the plugin, so I consider this fixed now.
