### ISSUE TITLE
Remove graphics sources on iPlug2_Core cmake library

### ISSUE THREAD

**Issue by markortu** [iPlug2/iPlug2#906]
Some graphics dependencies are being added in the **iPlug2_Core** cmake library, we should add it only in **iPlug2_IGraphicsCore** ([it is already included](https://github.com/iPlug2/iPlug2/blob/cmake/Scripts/cmake/IGraphics.cmake#L37)). This is causing **iPlug2_NoGraphics** to fail, as the necessary graphics sources are not included in that option.

**Comment by AlexHarker** [comment]
@olilarkin - The PR looks like this issue is now dealt with. If so can you close this issue? I wasn't confident enoughin my assessment to close this.
