### ISSUE TITLE
Draw function in custome controls being called when other control is changed

### ISSUE THREAD

**Issue by yoozmusic** [iPlug2/iPlug2#908]
**Describe the bug**
Draw function in custom controls being called repeatedly while other control is changed.

**To Reproduce**
duplicate IPlugEffect, create a custom control inheriting from IControl, override the Draw function and print a massage from there to see when it's being called, Attach the control, Build and move the knob.

**Expected behaviour**
the Draw function should be called only when the control is set dirty.

**Screenshots**

**IMPORTANT DETAILS**
Tested on win11 and mac m1  12.3.1
IGRAPHICS_NANOVG and IGRAPHICS_SKIA
App and vst2 probably the rest of the formats as well

**Additional context**
This caused many unnecessary Draw calls to I suspect all of my custom controls. Using iSender to send info to meters also cause the unnecessary Draw calls.

**Comment by olilarkin** [comment]
Are your controls linked to the same parameter by any chance?

**Comment by yoozmusic** [comment]
It happened also when the control is not connected to any parameter.

**Comment by olilarkin** [comment]
are the bounds of the control overlapping? in which case this is expected

**Comment by olilarkin** [comment]
Yes, define  IGRAPHICS_DISABLE_VSYNC in the .props file as a preprocessor macro for all targets
