### ISSUE TITLE
PromptForFile window kept behind plugin window on mac

### ISSUE THREAD

**Issue by svantana** [iPlug2/iPlug2#913]
On mac, the NSPanel created by PromptForFile can be stuck behind the plugin window. Apple's documentation states vaguely that this behaviour can be dependent on the window size and other factors.

Tested on AU and VST plugin GUIs, Ableton Live 10.6, MacOS 12.6, 2019 Intel Macbook.

The problem seems to go away when adding `setFloatingPanel: YES`. (see accompaning PR).

**Comment by olilarkin** [comment]
Thanks, I think I introduced this bug in https://github.com/iPlug2/iPlug2/commit/b71e9c29cfade09db3071332c7132d96ea57c104, and that it's not an issue if you supply the IFileDialogCompletionHandlerFunc for async operation. i'll investigate soon

**Comment by olilarkin** [comment]
danke
