### ISSUE TITLE
Mac app showing unwanted line on the bottom after resize

### ISSUE THREAD

**Issue by yoozmusic** [iPlug2/iPlug2#915]
**Describe the bug**
Mac app showing unwanted line on the bottom after resize.
This happens after updating to latest version of IPlug2

**To Reproduce**
Update IPlug, build a mac app and use the corner resize.

**Screenshots**
<img width="660" alt="Screenshot 2022-12-09 at 13 45 00" src="https://user-images.githubusercontent.com/68813442/206696798-c0699320-e299-439a-beee-4635aaffd642.png">

**IMPORTANT DETAILS**
this happens on mac app only with both IGRAPHICS_NANOVG and IGRAPHICS_SKIA

**Comment by olilarkin** [comment]
Is this on a M1Pro/Max macbook with a notch by any chance? I have noticed it to on my M1Pro 14" but not on another machine.

**Comment by yoozmusic** [comment]
Yes it is on m1Pro 14" with a notch. But it sure wasn't there before I did pull to the latest version. All my older builds don't have that.

**Comment by olilarkin** [comment]
should be fixed on master
