### ISSUE TITLE
IContainerBase overwrites mHide of its children

### ISSUE THREAD

**Issue by svantana** [iPlug2/iPlug2#921]
When setting hide state of an IContainerBase, its child controls have their hide state overwritten. This is not the behavior that is usually seen in similar systems. It makes it cumbersome to have child controls be hidden by default (e.g. nested tabbed views).

An alternative could be something like: 
```
bool IControl::IsHidden() const
{
  IContainerBase *parent = GetParent();
  if (parent && !mHide) {
      return parent->IsHidden();
  }
  return mHide;
}
```
This seems to work. I'm not creating a pull request because I'm not sure if there are other weird side effects of this.

**Comment by olilarkin** [comment]
Thanks for trying this. Gonna investigate.

**Comment by olilarkin** [comment]
I couldn't get the above to work, but I've solved the bug with the IVTabbedPagesControl here https://github.com/iPlug2/iPlug2/tree/controls/container
