### ISSUE TITLE
[CMake] Better resources & config management

### ISSUE THREAD

**Issue by edgjj** [iPlug2/iPlug2#928]
I honestly think CMake API should have another way of managing resources & plug-in configuration.

ATM we must have resources dir even in no actual resources scenario (.plist/.rc/.xib stuff). But we can generate all of these using pre-made templates + reworked prepare_resources-{os} scripts. For custom .xib/.rc scenarios we let user specify his own templates.

For actual resource management CMakeRC could be involved, so we can do this: 
```
set(RES_FONTS
    "resources/fonts/Roboto-Regular.ttf"
    "resources/fonts/Poppins-Regular.ttf"
    "resources/fonts/Poppins-Bold.ttf"
    "resources/fonts/Poppins-SemiBold.ttf"
    "resources/fonts/Poppins-Italic.ttf"
    "resources/fonts/Poppins-Thin.ttf"
    "resources/fonts/Poppins-ExtraLight.ttf"
    "resources/fonts/Overpass-SemiBold.ttf"
)

cmrc_add_resource_library(
    plug_fonts
    TYPE OBJECT
    NAMESPACE fonts
    WHENCE resources/fonts
    ${RES_FONTS}
)
```
Relating the config, we may avoid the need of actual config.h, and just set all the defines through add_definitions/add_target_definitions. For parts of iPlug where config.h is still included we just store empty config.h somewhere.

It may look like:
```
iplug_add_plugin(PluginName
    COPY_AFTER_BUILD
    GRAPHICS SKIA_GL2
    ICON ${RES_ICON}
    
    # config-specific things
    HAS_UI
    HAS_STATE_CHUNKS

    CHANNEL_LAYOUT "2-2"
    PLUGIN_CODE CODE
    MANUFACTURER_CODE MANU
    BUNDLE_MFR "Acme Inc."

    MIN_HEIGHT 128
    WIDTH 1000
    HEIGHT 500

    VST3_CATEGORIES Fx Dynamics
    AAX_CATEGORY Effect

    COMPANY "Acme Inc."
    URL "https://acme.com"
    SUPPORT_URL "https://acme.com/contacts"
    EMAIL "alice@acme.com"
    COPYRIGHT "Copyright 2023 Acme Inc."

    # enclosing data
    FORMATS VST3 AU2
    SOURCES ${SRC_FILES}
    INCLUDES ${SRC_INCLUDES}
    LIBS ${SRC_LIBS}
)
```

**Comment by olilarkin** [comment]
Thanks for the idea, but I prefer the careful tailored Xcode and Visual Studio projects so would not be using cmake like that. If you make it work on your branch and it looks great, I'll reconsider:-)

**Comment by olilarkin** [comment]
But I'll review your comment about the plists when I get back to working on cmake support

**Comment by edgjj** [comment]
> Thanks for the idea, but I prefer the careful tailored Xcode and Visual Studio projects so would not be using cmake like that. If you make it work on your branch and it looks great, I'll reconsider:-)

It already works :) The pseudo I showed is almost the same thing I already use in my CMake projects, with the difference that real implementation also supports building installers (which is kinda questionable).

TBH I planned this issue for discussion, not an actual feature request, with aim that more people can suggest ideas about this and we can reach some "gold standard" API
