### ISSUE TITLE
CLAP builds fail with the message: 'attempting to reference a deleted function'

### ISSUE THREAD

**Issue by heebje** [iPlug2/iPlug2#939]
CLAP builds fail with the following message:

1>C:\Users\Heeb\AppData\Local\Temp\iplug2\IPlug\CLAP\IPlugCLAP.h(222,28): error C2280: 'clap::helpers::HostProxy<clap::helpers::MisbehaviourHandler::Ignore,clap::helpers::CheckingLevel::None>::HostProxy(const clap::helpers::HostProxy<clap::helpers::MisbehaviourHandler::Ignore,clap::helpers::CheckingLevel::None> &)': attempting to reference a deleted function (compiling source file ......\IPlug\CLAP\IPlugCLAP.cpp)

The line in .\IPlug\CLAP\IPlugCLAP.h (line 222) where the error occurs reads:

ClapHost GetClapHost() { return _host; }

IPlugEffect-app and IPlugEffect-vst3 compile and work correctly, as expected.

Steps to reproduce:

1. Clone fresh iPlug2 repo;
2. Switch to clap branch;
3. Download necessary CLAP dependencies using the download-iplug-sdks.sh script;
4. Try compiling IPlugEffect example.

Expected behaviour: Clean compilation.

Plug-in format: CLAP.

Platform: Windows.

IGRAPHICS_BACKEND: IGRAPHICS_NANOVG.

**Comment by AlexHarker** [comment]
What branch are you on? The clap stuff isn't fully finished, but I though tI left it in a building state, although I haven't tested on windows in ages. Would like to wrap this up soon, so please give details of the branch and I'll take a look

**Comment by AlexHarker** [comment]
CLAP is still a moving target so this is to do with changes in the CLAP helpers repo - there was a nice easy fix though which is here 206cd947ad4a12cb8e0295a1ae155ce3dd869482

Thanks!
