### ISSUE TITLE
iOS crash on simulator when system output other than macbook speakers or headphones

### ISSUE THREAD

**Issue by demym** [iPlug2/iPlug2#944]
Hi,

i'm experimenting the following crash running the iOS app with AUV3 on simulator; if the output of the device (in this case a macbook) is on something other that macbook speakers or macbook headphones, the app crashes almost immediately on simulator, with the following messages:

<img width="872" alt="Screenshot 2023-03-27 at 10 15 31" src="https://user-images.githubusercontent.com/13074812/227882194-5d6a76f2-d66b-4a53-9c8a-88a193f44e4f.png">

Even if it's only on simulator, i experimented the same on real iphone device: if no external audio interface is connected, the app and plugin launch (at least), otherwise it crashes. That's the main reason i'm writing about it.

Thanks very much in advance !

**Comment by olilarkin** [comment]
We now catch the exception that occurs in the simulator for plugins that require the microphone input. Unfortunately there the mic input node gets an invalid samplerate and channel count. I believe this is a bug with the latest simulator. Instrument example works. Regarding AVAudioEngine fixes on device, that will be improved in #1056 

see 82487e0ea73d5f85ff2312fe138fcdb2b84b0b4c
