### ISSUE TITLE
C++ 14 compatibility

### ISSUE THREAD

**Issue by masqutti** [iPlug2/iPlug2#951]
https://github.com/iPlug2/iPlug2/blob/82230dadc36139ea0bbd843a8fedc5fb8c2b98c0/IGraphics/Controls/IControls.cpp#L1593
https://github.com/iPlug2/iPlug2/blob/82230dadc36139ea0bbd843a8fedc5fb8c2b98c0/IGraphics/Controls/IControls.cpp#L1603

Would it be possible to change these structured bindings into C++ 14 compatible style ie.
```
        auto peak = d.vals[c].first;
        auto avg = d.vals[c].second;
```
These 2 lines are the only reason iPlug2 does not build with C++ 14 which would be cool for backwards compatibility, especially on MacOS. :relaxed:

**Comment by olilarkin** [comment]
changed in [bc5aae0](https://github.com/iPlug2/iPlug2/commit/bc5aae0998c1cabc060a144adde56d7080d1317c), thanks
