### ISSUE TITLE
LoadFont() is unable to load TTF font

### ISSUE THREAD

**Issue by nojasm** [iPlug2/iPlug2#953]
I tried loading a custom font. I added it to **resources/fonts**, defined it in **config.h** as `FONT_FN "myfont.ttf"` and in **main.rc** just below `ROBOTO_FN` in the same format (also tried different things there without any success).

I am loading the font using `pGraphics->LoadFont("MyFont", FONT_FN)`, but this returns _false_ and any attempt of using `"MyFont"` does compile but creates an error when using a DAW (Ableton) obviously (sth. like "Did you really load the font correctly?").

Renaming the font to **"Roboto-Regular.ttf"** results in the correct font being used, but this is no solution for me. So does changing `#define ROBOTO_FN Roboto-Regular.ttf` to use my font. I also tried other fonts and OTF, all without success. I also attempted changing the _DEFAULT_FONT_ constant in the **config.h**.

I just started with audio development and I am a beginner when it comes to C/C++. I suppose that this is not a bug but rather my lack of experience.

**Comment by AlexHarker** [comment]
Hi @nojasm - are you making sure to include the font in the project correctly? That is the most likely source of the issue. If you let me know the platform you are on I can try to be more precise in guiding you through this.

If LoadFont() returns false then the font hasn't loaded. If you can point me to the font you are using I can also double check if there is an issue with the given font as I worked quite a lot on the custom font loading code.

For future reference the forum (https://iplug2.discourse.group) is best for discussion of how to do things and GitHub issues is best for things that you are fairly sure are bugs. Hopefully we can get you up and running with this font soon though!

**Comment by nojasm** [comment]
I am on Windows 10 x64 with VS 2019 and almost the latest iPlug2 commit. I double checked everything multiple times by now. A solution I found is setting ROBOTO_FN to point at my font instead in the config.h. It seams to me like using any other constant beside "ROBOTO_FN" causes the trouble. Maybe it has to do with it also being the DEFAULT_FONT (which again, I tried to modify too).

**Comment by olilarkin** [comment]
could you share a link to the font (privately if necessary) and we can check it?

**Comment by olilarkin** [comment]
It seems to work ok for me. I think i used a different ttf convertor.

![image](https://user-images.githubusercontent.com/655662/233769713-1f26cfb1-2d59-4d60-ae1c-610b41e7b25f.png)

here are the changes i made in git patch format. You can apply these changes to a clean checkout of iPlug2/master with the following command ...

```git apply --ignore-whitespace monobloco.patch```

[monobloco.patch](https://github.com/iPlug2/iPlug2/files/11300521/monobloco.patch)

**Comment by AlexHarker** [comment]
I think the issue here is not the font but making sure the resource gets included in your plugin build. Adding to main.rc and config.h should be enough, but it appears that something is not quite functioning correctly there - hopefully @olilarkin's changes above will help you find the missing step.
