### ISSUE TITLE
Setting a control's parameter index to kNoParameter makes its automation indicator light in Pro Tools incorrectly

### ISSUE THREAD

**Issue by sstillwell** [iPlug2/iPlug2#961]
**CHECK**
Is this an issue or just a question?  This is an issue.

**Describe the bug**
When a UI control without a parameter (e.g. a meter or literal non-editable text control) is instantiated with kNoParameter for its parameter index, then in Pro Tools that control's automation indicator will light if you automate the master bypass control,  This is confusing to the end user and clutters the UI.

**To Reproduce**
Launch Pro Tools
Instantiate an IPlug2 plugin
Using the Pro Tools UI, automate the master bypass parameter on that plugin
See all controls that have kNoParameter for the parameter index show an automation indicator, including any background graphic control. 

**Expected behaviour**
If a control is not associated with a parameter, it should never show an automation indicator.

**Screenshots**
<img width="803" alt="image" src="https://github.com/iPlug2/iPlug2/assets/794215/ff9ee784-d3a3-42ed-9c71-8149ddd16883">

**IMPORTANT DETAILS**
* What plug-in format does it relate to - AAX only?
* What platform does it relate to - Windows and macOS
* What IGRAPHICS_BACKEND does it relate to - ALL, as far as I know.

**Additional context**

**Comment by AlexHarker** [comment]
Does AAX define the bypass parameter as having a -1 index? That might explain the issue, but indeed, it shouldn't happen.

**Comment by AlexHarker** [comment]
Looks like *probably* the point that we should be checking for this is in AAX_CEffectGUI_IPLUG::SetControlHighlightInfo(). I suspect that paramIdx ends up as -1 and then it matches controls with no parameter.

It's worth noting that various IGraphics functions will respond to calls to do things to controls matching no parameter, or to find the first control matching this etc. We could check in all cases, but that's a much longer job, and I think it is probably most appropriate to leave that facility (in case it is useful) and check for situations like this one where t(I assume) he host uses that index for something else.

**Comment by sstillwell** [comment]
For what it's worth, I'll probably open another issue and associated PR to tie that indicator to the control's target rect rather than its bounds. When bitmap controls have shadows, reflections, etc. it can make that indicator appear in seemingly unrelated locations. Narrowing the target rect to the bounds of the control proper can make it appear in a much more rational location, and default behavior wouldn't change since target normally = bounds.

**Comment by AlexHarker** [comment]
That sounds likely sensible, although if you have very specific needs for position you can override DrawPTHighlight(). Maybe it would be useful to break out a helper function in the case that all you want to do is draw in a different position- thoughts @olilarkin ?

I can't build for AAX here, so @sstillwell could you test for paramIdx == -1 in the above method and if so, don't call through to the GUI and see if that fixes the issue listed here? Happy to see a PR also.

**Comment by sstillwell** [comment]
> Does AAX define the bypass parameter as having a -1 index (or rather a 0 index, as I think indices are offset in AAX by the look of it)? That might explain the issue, but indeed, it shouldn't happen.

If I remember correctly, the master bypass parameter is always parameter 0, but then in SetControlHighlightInfo we compute...

`   int paramIdx = atoi(paramID) - kAAXParamIdxOffset;`

where` kAAXParmIdxOffset` is 1, so we get a `paramIdx` of -1.  Bummer.

Conversely, though, when we add all of the IPlug parameters to AAX, we take the zero-based parameter ID from IPlug and add the same `kAAXParamIdxOffset` to the loop counter, so they always go from 1->NParams()+1

I'm worried that if we just filter for `paramIdx == 1` we'll wind up making the master bypass not show as automated when it is.  I'll test it, though, sure.

**Comment by sstillwell** [comment]
I think maybe a better place to do this is in `IControl::SetPTParameterHighlight(bool isHighlighted, int color)` where we can just refuse to set `mPTisHighlighted` if `mVals[0].idx == kNoParameter`

**Comment by sstillwell** [comment]
Okay, that DOES work, and it leaves the master bypass showing its proper automation state, so no negative impact.

What I did was:
`AAX_Result AAX_CEffectGUI_IPLUG::SetControlHighlightInfo(AAX_CParamID paramID, AAX_CBoolean iIsHighlighted, AAX_EHighlightColor iColor)
{
  IPlugAAXView_Interface* pViewInterface = (IPlugAAXView_Interface*) mPlug->GetAAXViewInterface();
  
  if (pViewInterface)
  {
    int paramIdx = atoi(paramID) - kAAXParamIdxOffset;

    if (paramIdx != -1) pViewInterface->SetPTParameterHighlight(paramIdx, (bool) iIsHighlighted, (int) iColor);
    return AAX_SUCCESS;
  }
  
  return AAX_ERROR_INVALID_PARAMETER_ID;
}
`
and what I wound up with was...
<img width="676" alt="image" src="https://github.com/iPlug2/iPlug2/assets/794215/a9def2c5-1321-4fdb-8394-6cab89022d93">

I'll call that a win.  Real controls with parameters have automation indicators, display-only controls have none.

**Comment by sstillwell** [comment]
Oh, by the way, that screenshot DOES include the mod I made to pull the indicator into the target rect rather than the control's bounds, and when I instantiate the control I make a call to set the target rect.  Those knobs have a rather large shadow extending to the ESE of the knob proper, so the automation indicator for Ceiling was appearing nearly in the Soft Clip control, etc.

**Comment by sstillwell** [comment]
The only concern that I have is that if another control on the plugin UI replicates the Pro Tools master bypass control (has the same `paramID` of zero and thus `paramIdx` of `kNoParameter`), it will not show an automation indicator, although the actual Pro Tools master bypass indicator outside the plugin's UI will, as shown above.

**Comment by sstillwell** [comment]
> That sounds likely sensible, although if you have very specific needs for position you can override DrawPTHighlight(). Maybe it would be useful to break out a helper function in the case that all you want to do is draw in a different position- thoughts @olilarkin ?

Actually, I went and reviewed my code - I DID override `virtual void DrawPTHighlight(IGraphics& g)`, as I have my own controls to do bitmap-stack knobs, etc. and it was easier to do there than modify IPlug2, which we try really hard not to do - we want to be able to consume it unmodified if possible.

```
  virtual void DrawPTHighlight(IGraphics& g)
  {
    if (mPTisHighlighted)
    {
      g.FillCircle(mPTHighlightColor, mTargetRECT.R-5, mTargetRECT.T+5, 2);
    }
  }
```

I'll make a PR updating the actual IPlug2 code, though...I do think it's sensible.

**Comment by AlexHarker** [comment]
> The only concern that I have is that if another control on the plugin UI replicates the Pro Tools master bypass control (has the same `paramID` of zero and thus `paramIdx` of `kNoParameter`), it will not show an automation indicator, although the actual Pro Tools master bypass indicator outside the plugin's UI will, as shown above.

I don't think you can actually make that work anyway, as you can't actually make an iPlug parameter that will be linked to this bypass parameter and respond correctly - only parameters that are correct iplug parameters will be mapped - you can see this here:

https://github.com/iPlug2/iPlug2/blob/2f6e65a3ace8fa18a4a29f52d3226f45a4abb54c/IPlug/AAX/IPlugAAX.cpp#L239

So I don't think this is a concern

**Comment by sstillwell** [comment]
Fair enough, but if kNoParameter == -1 it should certainly be possible to create one with paramIdx of 0...or am I missing something?

**Comment by AlexHarker** [comment]
You don't have control of the AAX paramid - it's just the iPlug paramIdx + 1 and the paramIdx's start at 0, so you can't make a control with an AAX paramid of 0 for real - you can assign a control to -1, but that has a special meaning in iplug, and the control won't respond to the automation or other host info back and forth (otherwise you'd have not only seen the indicator lights, but also all your controls would have been changing with the automation).

**Comment by AlexHarker** [comment]
We could build something into AAX that specifically maps the bypass parameter, possibly using another special value but it would need some thought to get it right
