### ISSUE TITLE
IGraphicsMac::PromptForDirectory may not return selected Directory

### ISSUE THREAD

**Issue by janhase88** [iPlug2/iPlug2#976]
In IGraphicsMac.mm in PromptForDirectory on line 543 a temporary variable "WDL_String path" is passed into doHandleResponse, but
this will not return the selected directory.
```
[panelOpen beginWithCompletionHandler:^(NSModalResponse response) {
      WDL_String path;
     doHandleResponse(panelOpen, response, path, nullptr);  //<== HERE
    }];
```

possible fix:

```
[panelOpen beginWithCompletionHandler:^(NSModalResponse response) {
     doHandleResponse(panelOpen, response, dir, nullptr);
    }];
```

**Comment by olilarkin** [comment]
There was a bug where the async/non async calls here were round the wrong way. It should be fixed in fb6c8fa363bfebcf42fd695ef7de7d0c62fa00fe. Closing this. If you still think there is a problem please let me know
