### ISSUE TITLE
Allow for non-recursive IDirBrowseControlBase::ScanDirectory

### ISSUE THREAD

**Issue by sdatkinson** [iPlug2/iPlug2#979]
In [Neural Amp Modeler](https://github.com/sdatkinson/NeuralAmpModelerPlugin)'s model and IR browser control class [`NAMFileBrowserControl`](https://github.com/sdatkinson/NeuralAmpModelerPlugin/blob/8c9182fb811a1ca233ef431216216168e1790226/NeuralAmpModeler/NeuralAmpModelerControls.h#LL144C7-L144C28), `ScanDirectory()` is called from `SetupMenu()`. [It acts recursively](https://github.com/iPlug2/iPlug2/blob/c259b038ca70a43266d388c56f837990e18a96be/IGraphics/IControl.cpp#L1120) in iPlug2's implementation, but this isn't what works best for my use case.

I'd like to be able to `ScanDirectory` non-recursively. Can iPlug2 support this for me?  Either making a boolean like `recursive` be an argument, or declaring the method as `virtual` so that I can override would work.

Thanks!

**Comment by olilarkin** [comment]
fixed in 7d993b2c607ae572483f131459b5a1053967c902 (on controls/container branch, which NAM Plug-in tracks)
