### ISSUE TITLE
`IDirBrowseControlBase::ScanDirectory` fails to find files whose names include the extension elsewhere in their path.

### ISSUE THREAD

**Issue by sdatkinson** [iPlug2/iPlug2#989]
**Describe the bug**
This surfaces https://github.com/sdatkinson/NeuralAmpModelerPlugin/issues/306, whose root cause is with [`DirBrowseControlBase::ScanDirectory()`](https://github.com/iPlug2/iPlug2/blob/b3a51573f45c830755ee4426d2d1eb04cf645359/IGraphics/IControl.cpp#L1120), which does not function as I think it's intended to.

The Issue is that files whose path contains the string contained in `mExtension` will _not_ match if the extension occurs anywhere _before_ the file extension (earlier in the file _or_ in the name of a containing directory).

**To Reproduce**
* Run NAM version 0.7.4
* Select a file in a directory containing the following files:
  * `5150.nam`
  * `birdie nam.nam`
  * `DR Pedal Platform.nam`
  * `Fender 65 Twin.nam`

**Expected behaviour**
All four files listed above should be pushed to `mFiles`.

**Screenshots**
See linked issue above.

**IMPORTANT DETAILS**
* Not specific to a plug-in format.
* Not specific to a platform.
* Not specific to a graphics backend.

**Additional context**
The issue can be resolved by replacing the [use of `strstr` here](https://github.com/iPlug2/iPlug2/blob/b3a51573f45c830755ee4426d2d1eb04cf645359/IGraphics/IControl.cpp#L1141) with `strrstr`, defined as follows (I'm not aware of a built-in alternative):

```c
// Find the last occurrence of str2 in str1.
// Return a pointer to the first character of the match.
// Return a pointer to the start of str1 if str2 is empty.
// Return a nullptr if str2 isn't found in str1.
const char* strrstr(const char* str1, const char* str2) {
  if (*str2 == '\0')
    return str1;
  
  const char* result = nullptr;
  
  while (*str1 != '\0') {
    if (std::strncmp(str1, str2, std::strlen(str2)) == 0)
      result = str1;
    
    str1++;
  }
  
  return result;
}
```
Testing this appears to resolve the problem in the downstream plug-in:

<img width="956" alt="image" src="https://github.com/iPlug2/iPlug2/assets/12240186/5dc103cd-3f1e-4c14-8867-d002b9c2cc95">

**Comment by olilarkin** [comment]
addressed in [b8473be](https://github.com/iPlug2/iPlug2/commit/b8473bea0c2df54260ea430b361e7254071bfd08)
