### ISSUE TITLE
Dirscan UTF8 is disabled, which is problematic for filenames with non ascii characters

### ISSUE THREAD

**Issue by sdatkinson** [iPlug2/iPlug2#991]
**Describe the bug**
This Issue surfaces up [a bug in `NeuralAmpModelerPlugin` (#307)](https://github.com/sdatkinson/NeuralAmpModelerPlugin/issues/307).

**To Reproduce**
* Enter [`IGraphicsWin::PromptForFile`](https://github.com/iPlug2/iPlug2/blob/b3a51573f45c830755ee4426d2d1eb04cf645359/IGraphics/Platforms/IGraphicsWin.cpp#L1579) with any values for `fileName` and `path`. `EFileAction` is `EFileAction::Open` and `ext` is `"nam"`, but I'm not sure either is necessary.
* Select the file located at `"C:\Users\steve\Downloads\6505+ Neural Amp Packß\6505+ Red ch - MXR Drive.nam"`.  I only think that the `"ß"` is necessary for the bug (perhaps a larger issue related to non-ASCII characters? Edit: `"α"` causes similar issues, with trivial details different in the expected ways)
* The returned values from the appear wrong:
  * `path.Get()` returns `"C:\\Users\\steve\\Downloads\\6505+ Neural Amp PackÃŸ\\"`
  * `fileName.Get()` returns `"C:\\Users\\steve\\Downloads\\6505+ Neural Amp PackÃŸ\\6505+ Red ch - MXR Drive.nam"`
  * ![image](https://github.com/iPlug2/iPlug2/assets/12240186/6b254444-86ee-4a87-980d-da34e064675c)

**The root cause appears to be that the data assigned to `ofn` during [`GetOpenFileNameW`](https://github.com/iPlug2/iPlug2/blob/b3a51573f45c830755ee4426d2d1eb04cf645359/IGraphics/Platforms/IGraphicsWin.cpp#L1660) is wrong.**  This is well outside of my expertise, but [Google tells me that using the Common Item Dialog is the preferred way of handling opening files?](https://learn.microsoft.com/en-us/windows/win32/api/commdlg/nf-commdlg-getopenfilenamew)

**Expected behaviour**
The gotten `path` and `fileName` should be `"C:\\Users\\steve\\Downloads\\6505+ Neural Amp Packß\\"` and `"C:\\Users\\steve\\Downloads\\6505+ Neural Amp Packß\\6505+ Red ch - MXR Drive.nam"`, respectively.

**Screenshots**
Above

**IMPORTANT DETAILS**
* What plug-in format does it relate to - _Standalone confirmed; possibly VST3 as well._
* What platform does it relate to - _Windows 11 confirmed. Not macOS. Possibly other Windows versions?_
* What IGRAPHICS_BACKEND does it relate to, IGRAPHICS_NANOVG, IGRAPHICS_SKIA or ALL? _Not sure._

**Additional context**
N/A

**Comment by olilarkin** [comment]
oh dear this is quite awful, especially since I live in Germany. Will try and fix it asap. Thanks for the report

**Comment by AlexHarker** [comment]
This looks like it's been handled for UT8 and UTF16 issues - it's important to consider how the string you are getting is being displayed in the end. I'm pretty sure that some of this came from previous changes in my branch of wld-ol that I tested heavily on some really weird paths, so we just try and trace this back.... I'm not sure if prompt for file was part of that testing or not though.

**Comment by olilarkin** [comment]
There is not a problem with PromptForFile, but rather the wdl dirscan class. This can initially be fixed by removing the #define WDL_NO_SUPPORT_UTF8 from IControl.cpp.

https://github.com/iPlug2/iPlug2/blob/b3a51573f45c830755ee4426d2d1eb04cf645359/IGraphics/IControl.cpp#L13

removing this means the file with ß in the name appears in the NAM UI. If you then click the name to show the popup menu the popup menu shows an incorrect name. To fix that issue we need to convert to wide string and use AppendPopupMenuW instead of AppendPopupMenuA in IGraphicsWin::CreatePlatformPopupMenu().

![image](https://github.com/iPlug2/iPlug2/assets/655662/4a7f5546-aeaa-49e7-bfd2-46c4e6c9e1cb)

**Comment by olilarkin** [comment]
Some WIP here: https://github.com/iPlug2/iPlug2/commits/unicode-fixes

**Comment by olilarkin** [comment]
PR: #991

**Comment by AlexHarker** [comment]
PR: #1044

**Comment by olilarkin** [comment]
merged fix
