### ISSUE TITLE
AUv3 never calls OnParamReset()

### ISSUE THREAD

**Issue by AlexHarker** [iPlug2/iPlug2#993]
**Describe the bug**
Engine parameters may never be received on AUv3, as OnParamReset() is never called.

**Expected behaviour**
OnParamReset() is called before the plugin starts procesing

@olilarkin can you take a look and see where you think is best to add this? I can add before the call to OnReset() and it fixes the issue for me, but there might be somewhere better to do this - it's more about initalising the plugin. I don't know AUv3 well enough to be sure I'm making the best positioning choice.

The call that is needed is trivial:

`  mPlug->OnParamReset(kReset);
`

**Comment by olilarkin** [comment]
does this method sound appropriate?

https://developer.apple.com/documentation/audiotoolbox/auaudiounit/1387620-allocaterenderresourcesandreturn?language=objc

**Comment by AlexHarker** [comment]
Yes - that aligns with what we do for AUv2.

**Comment by AlexHarker** [comment]
I'll put it in. I think that might be where I had it anyway, but I'll make a PR.

**Comment by olilarkin** [comment]
could you try #1004 and let me know if it works as you expect?
