### ISSUE TITLE
Time info AUv3 transport bug

### ISSUE THREAD

**Issue by Youlean** [iPlug2/iPlug2#995]
https://github.com/iPlug2/iPlug2/blob/a8f3246f5880e6e48f3b8f16eb98df358933f9bb/IPlug/AUv3/IPlugAUAudioUnit.mm#L623
https://github.com/iPlug2/iPlug2/blob/a8f3246f5880e6e48f3b8f16eb98df358933f9bb/IPlug/AUv3/IPlugAUAudioUnit.mm#L624

Shouldn't this be a bitwise check instead?

**Comment by AlexHarker** [comment]
Yes - it looks like the three "==" should be "&". The logical or is correct, but it could also be achieved by or'ing the two flags before the bit mask.

**Comment by Youlean** [comment]
I have tested in Logic on iPad and it's definitely a bitwise check

**Comment by AlexHarker** [comment]
Great - would you be able to make a PR @Youlean

**Comment by olilarkin** [comment]
fixed in f917334
