### ISSUE TITLE
"Windows" Get started in Wiki uses wrong URL

### ISSUE THREAD

**Issue by dschiller** [iPlug2/iPlug2#996]
In the WIKI at https://github.com/iPlug2/iPlug2/wiki/ the getting started tutorial for Windows points to https://github.com/iPlug2/iPlug2/wiki/01_Getting_started_windows but it should be https://github.com/iPlug2/iPlug2/wiki/02_Getting_started_windows.

**Comment by olilarkin** [comment]
thanks, fixed
